'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'batterySize', labels: { en: 'Battery Size (kWh)', it: 'Capacita batteria (kWh)', es: 'Tamano bateria (kWh)', fr: 'Taille batterie (kWh)', de: 'Batteriegroesse (kWh)', pt: 'Tamanho bateria (kWh)' }, defaultValue: '60', min: 20, max: 200 },
  { key: 'homeRate', labels: { en: 'Home Electricity ($/kWh)', it: 'Tariffa casa (€/kWh)', es: 'Tarifa hogar ($/kWh)', fr: 'Tarif domicile (€/kWh)', de: 'Hausstrom (€/kWh)', pt: 'Tarifa casa (R$/kWh)' }, defaultValue: '0.13', step: 0.01 },
  { key: 'publicRate', labels: { en: 'Public Charging ($/kWh)', it: 'Ricarica pubblica (€/kWh)', es: 'Carga publica ($/kWh)', fr: 'Recharge publique (€/kWh)', de: 'Oeffentliches Laden (€/kWh)', pt: 'Recarga publica (R$/kWh)' }, defaultValue: '0.35', step: 0.01 },
  { key: 'annualMiles', labels: { en: 'Annual Miles', it: 'Km annuali', es: 'Millas anuales', fr: 'Km annuels', de: 'Jaehrliche Km', pt: 'Km anuais' }, defaultValue: '12000' },
  { key: 'efficiency', labels: { en: 'Efficiency (mi/kWh)', it: 'Efficienza (km/kWh)', es: 'Eficiencia (mi/kWh)', fr: 'Efficacite (km/kWh)', de: 'Effizienz (km/kWh)', pt: 'Eficiencia (km/kWh)' }, defaultValue: '3.5', step: 0.1 },
];
const results = [
  { key: 'homeAnnualCost', labels: { en: 'Home Charging/Year', it: 'Ricarica casa/anno', es: 'Carga hogar/ano', fr: 'Recharge domicile/an', de: 'Heimladen/Jahr', pt: 'Recarga casa/ano' }, color: 'green' as const, format: 'currency' as const },
  { key: 'publicAnnualCost', labels: { en: 'Public Charging/Year', it: 'Ricarica pubblica/anno', es: 'Carga publica/ano', fr: 'Recharge publique/an', de: 'Oeffentlich/Jahr', pt: 'Recarga publica/ano' }, color: 'red' as const, format: 'currency' as const },
  { key: 'savingsVsPublic', labels: { en: 'Home vs Public Savings', it: 'Risparmio casa vs pubblica', es: 'Ahorro hogar vs publica', fr: 'Economies domicile vs public', de: 'Ersparnis Heim vs Oeffentlich', pt: 'Economia casa vs publica' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'costPerCharge', labels: { en: 'Home Cost Per Full Charge', it: 'Costo ricarica completa casa', es: 'Costo carga completa hogar', fr: 'Cout recharge complete', de: 'Kosten pro Volladung', pt: 'Custo recarga completa casa' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const bat = v.batterySize || 60; const home = v.homeRate || 0.13; const pub = v.publicRate || 0.35;
  const miles = v.annualMiles || 12000; const eff = v.efficiency || 3.5;
  const annualKwh = miles / eff; const homeCost = annualKwh * home; const pubCost = annualKwh * pub;
  return { homeAnnualCost: Math.round(homeCost), publicAnnualCost: Math.round(pubCost), savingsVsPublic: Math.round(pubCost - homeCost), costPerCharge: Math.round(bat * home * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('EV Charging Cost Calculator: Home vs Public Charging', ['Understanding your EV charging costs is essential for budgeting and maximizing savings. Home charging is typically 2-3x cheaper than public fast charging stations.', 'This calculator compares annual costs of home vs public charging based on your electricity rates, driving habits, and vehicle efficiency.', 'At average US rates, home charging costs about $0.04/mile compared to $0.10/mile for public DC fast charging. Over 12,000 miles/year, that is a $700+ difference.', 'For related tools, see our <a href="/${lang}/tools/ev-vs-gas-calculator">EV vs gas calculator</a> and <a href="/${lang}/tools/ev-savings-calculator">EV savings calculator</a>.'], [{q:'How much does it cost to charge an EV at home?',a:'At average US rates ($0.13/kWh), a full charge of a 60 kWh battery costs about $7.80, giving 200+ miles of range.'},{q:'Is home charging cheaper than public?',a:'Yes, typically 50-70% cheaper. Home charging costs $0.03-0.05/mile vs $0.08-0.15/mile for public fast charging.'},{q:'Should I install a Level 2 charger?',a:'Yes, if you can. Level 2 (240V) charges 5-10x faster than Level 1 (120V) and adds 25-30 miles of range per hour.'},{q:'Do public chargers cost more at peak hours?',a:'Many public networks charge more during peak hours (4-9 PM). Off-peak charging can save 20-30%.'}]),
  it: mkSeo('Calcolatore Costo Ricarica EV', ['Capire i costi di ricarica EV e essenziale per il budget. La ricarica a casa costa 2-3 volte meno delle colonnine pubbliche.', 'Questo calcolatore confronta i costi annuali di ricarica domestica vs pubblica.', 'A tariffe medie, la ricarica domestica costa circa 0,04€/km contro 0,10€/km per le colonnine veloci.', 'Consulta il <a href="/${lang}/tools/ev-vs-gas-calculator">calcolatore EV vs benzina</a>.'], [{q:'Quanto costa ricaricare a casa?',a:'A tariffe medie (0,13€/kWh), una ricarica completa da 60 kWh costa circa 7,80€.'},{q:'La ricarica domestica e piu economica?',a:'Si, tipicamente il 50-70% piu economica.'},{q:'Devo installare un caricatore Level 2?',a:'Si, carica 5-10 volte piu velocemente del Level 1.'},{q:'Le colonnine costano di piu nelle ore di punta?',a:'Molte reti applicano tariffe piu alte dalle 16 alle 21.'}]),
  es: mkSeo('Calculadora Costo Carga EV', ['Entender tus costos de carga EV es esencial. La carga en casa cuesta 2-3 veces menos que las estaciones publicas.', 'Esta calculadora compara costos anuales de carga en casa vs publica.', 'A tarifas promedio, la carga en casa cuesta $0.04/milla vs $0.10/milla en carga rapida publica.', 'Consulta la <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'Cuanto cuesta cargar en casa?',a:'A tarifas promedio ($0.13/kWh), una carga completa de 60 kWh cuesta unos $7.80.'},{q:'La carga en casa es mas barata?',a:'Si, tipicamente 50-70% mas barata.'},{q:'Debo instalar un cargador Level 2?',a:'Si, carga 5-10 veces mas rapido.'},{q:'Las estaciones publicas cuestan mas en horas pico?',a:'Muchas redes cobran mas de 4-9 PM.'}]),
  fr: mkSeo('Calculateur Cout Recharge VE', ['Comprendre vos couts de recharge est essentiel. La recharge a domicile coute 2-3x moins que les bornes publiques.', 'Ce calculateur compare les couts annuels de recharge a domicile vs publique.', 'Aux tarifs moyens, la recharge domicile coute environ 0,04€/km vs 0,10€/km en charge rapide.', 'Consultez le <a href="/${lang}/tools/ev-vs-gas-calculator">calculateur VE vs essence</a>.'], [{q:'Combien coute la recharge a domicile?',a:'A tarifs moyens (0,13€/kWh), une charge complete de 60 kWh coute environ 7,80€.'},{q:'La recharge domicile est moins chere?',a:'Oui, typiquement 50-70% moins chere.'},{q:'Dois-je installer un chargeur Level 2?',a:'Oui, il charge 5-10x plus vite.'},{q:'Les bornes publiques coutent plus aux heures de pointe?',a:'Beaucoup de reseaux facturent plus de 16h a 21h.'}]),
  de: mkSeo('E-Auto Ladekosten-Rechner', ['Ihre Ladekosten zu verstehen ist essentiell. Heimladen kostet 2-3x weniger als oeffentliche Ladestationen.', 'Dieser Rechner vergleicht jaehrliche Kosten von Heim- vs oeffentlichem Laden.', 'Bei durchschnittlichen Tarifen kostet Heimladen etwa 0,04€/km vs 0,10€/km am Schnelllader.', 'Nutzen Sie den <a href="/${lang}/tools/ev-vs-gas-calculator">E-Auto vs Benziner Rechner</a>.'], [{q:'Was kostet Heimladen?',a:'Bei Durchschnittstarif (0,13€/kWh) kostet eine Vollladung von 60 kWh etwa 7,80€.'},{q:'Ist Heimladen guenstiger?',a:'Ja, typisch 50-70% guenstiger.'},{q:'Soll ich eine Wallbox installieren?',a:'Ja, sie laedt 5-10x schneller als die Steckdose.'},{q:'Kosten oeffentliche Lader mehr zu Spitzenzeiten?',a:'Viele Netze berechnen mehr von 16-21 Uhr.'}]),
  pt: mkSeo('Calculadora Custo Recarga EV', ['Entender seus custos de recarga e essencial. A recarga em casa custa 2-3x menos que estacoes publicas.', 'Esta calculadora compara custos anuais de recarga em casa vs publica.', 'Com tarifas medias, a recarga em casa custa R$0,04/km vs R$0,10/km na recarga rapida.', 'Consulte a <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'Quanto custa carregar em casa?',a:'Com tarifa media (R$0,13/kWh), uma carga completa de 60 kWh custa cerca de R$7,80.'},{q:'A recarga em casa e mais barata?',a:'Sim, tipicamente 50-70% mais barata.'},{q:'Devo instalar um carregador Level 2?',a:'Sim, carrega 5-10x mais rapido.'},{q:'Estacoes publicas custam mais no horario de pico?',a:'Muitas redes cobram mais das 16 as 21h.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="ev-charging-cost-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
