'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'familySize', labels: { en: 'Family Size', it: 'Dimensione famiglia', es: 'Tamano familia', fr: 'Taille famille', de: 'Familiengroesse', pt: 'Tamanho familia' }, defaultValue: '2', min: 1, max: 8 },
  { key: 'annualDentalCost', labels: { en: 'Expected Annual Dental ($)', it: 'Spese dentali annuali (€)', es: 'Gastos dentales anuales ($)', fr: 'Frais dentaires annuels (€)', de: 'Jaehrliche Zahnarztkosten (€)', pt: 'Custos dentarios anuais (R$)' }, defaultValue: '800' },
  { key: 'needsMajorWork', labels: { en: 'Major Work Needed (0=no,1=yes)', it: 'Lavori importanti (0=no,1=si)', es: 'Trabajo mayor (0=no,1=si)', fr: 'Travaux majeurs (0=non,1=oui)', de: 'Groessere Arbeiten (0=nein,1=ja)', pt: 'Trabalho maior (0=nao,1=sim)' }, defaultValue: '0', min: 0, max: 1 },
  { key: 'planTier', labels: { en: 'Plan Tier (1=basic,3=premium)', it: 'Livello piano (1=base,3=premium)', es: 'Nivel plan (1=basico,3=premium)', fr: 'Niveau plan (1=base,3=premium)', de: 'Planstufe (1=basis,3=premium)', pt: 'Nivel plano (1=basico,3=premium)' }, defaultValue: '2', min: 1, max: 3 },
];
const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'estimatedSavings', labels: { en: 'Est. Annual Savings', it: 'Risparmio annuale est.', es: 'Ahorro anual est.', fr: 'Economies annuelles est.', de: 'Geschaetzte Ersparnis', pt: 'Economia anual est.' }, color: 'green' as const, format: 'currency' as const },
  { key: 'annualMax', labels: { en: 'Annual Maximum', it: 'Massimale annuale', es: 'Maximo anual', fr: 'Maximum annuel', de: 'Jaehrliches Maximum', pt: 'Maximo anual' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const fam = v.familySize || 2; const dental = v.annualDentalCost || 800; const major = v.needsMajorWork || 0; const tier = v.planTier || 2;
  const baseMonthly = [20, 35, 55][Math.min(2, Math.max(0, tier - 1))]; const monthly = baseMonthly * fam;
  const annual = monthly * 12; const coverage = tier === 1 ? 0.5 : tier === 2 ? 0.7 : 0.8;
  const majorCost = major ? 3000 : 0; const totalDental = dental + majorCost;
  const covered = totalDental * coverage; const savings = covered - annual;
  const maxBenefit = [1000, 1500, 2500][Math.min(2, Math.max(0, tier - 1))];
  return { monthlyPremium: Math.round(monthly), annualPremium: Math.round(annual), estimatedSavings: Math.round(Math.max(0, savings)), annualMax: maxBenefit };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Dental Insurance Calculator: Estimate Your Coverage', ['Dental insurance helps manage the cost of routine cleanings, fillings, and major dental work. Most plans cover preventive care at 100%, basic procedures at 70-80%, and major work at 50%.', 'This calculator estimates monthly premiums and potential savings based on family size, expected dental costs, and plan tier. Individual plans average $20-$50/month while family plans cost $50-$150/month.', 'Without insurance, a routine cleaning costs $200-$400, a filling $150-$300, and a crown $1,000-$3,000. Dental insurance makes these costs much more manageable.', 'For related tools, see our <a href="/${lang}/tools/health-insurance-calculator">health insurance calculator</a> and <a href="/${lang}/tools/vision-insurance-calculator">vision insurance calculator</a>.'], [{q:'Is dental insurance worth it?',a:'For most people yes, especially if you need more than just cleanings. A single crown without insurance can cost more than a year of premiums.'},{q:'What does dental insurance cover?',a:'Preventive (cleanings, x-rays) at 100%, basic (fillings, extractions) at 70-80%, and major (crowns, root canals) at 50%.'},{q:'What is the annual maximum?',a:'Most plans cap benefits at $1,000-$2,500/year. Premium plans may offer higher limits.'},{q:'Is there a waiting period?',a:'Many plans have a 6-12 month waiting period for major procedures. Preventive care is usually covered immediately.'}]),
  it: mkSeo('Calcolatore Assicurazione Dentale', ['L\'assicurazione dentale aiuta a gestire i costi di pulizia, otturazioni e lavori importanti.', 'Questo calcolatore stima i premi e i risparmi in base a dimensione famiglia e costi previsti.', 'Senza assicurazione, una pulizia costa 200-400€ e una corona 1.000-3.000€.', 'Consulta il <a href="/${lang}/tools/health-insurance-calculator">calcolatore assicurazione sanitaria</a>.'], [{q:'Vale la pena?',a:'Per la maggior parte si, specialmente se servono lavori oltre la pulizia.'},{q:'Cosa copre?',a:'Prevenzione al 100%, lavori base al 70-80%, lavori importanti al 50%.'},{q:'Cos\'e il massimale annuale?',a:'La maggior parte dei piani copre fino a 1.000-2.500€/anno.'},{q:'C\'e un periodo di attesa?',a:'Molti piani hanno 6-12 mesi di attesa per lavori importanti.'}]),
  es: mkSeo('Calculadora de Seguro Dental', ['El seguro dental ayuda a gestionar costos de limpiezas, empastes y trabajos mayores.', 'Esta calculadora estima primas y ahorros segun tamano de familia y costos esperados.', 'Sin seguro, una limpieza cuesta $200-$400 y una corona $1,000-$3,000.', 'Consulta la <a href="/${lang}/tools/health-insurance-calculator">calculadora de seguro de salud</a>.'], [{q:'Vale la pena?',a:'Para la mayoria si, especialmente si necesitas mas que limpiezas.'},{q:'Que cubre?',a:'Preventivo al 100%, basico al 70-80%, mayor al 50%.'},{q:'Cual es el maximo anual?',a:'La mayoria cubre hasta $1,000-$2,500/ano.'},{q:'Hay periodo de espera?',a:'Muchos planes tienen 6-12 meses de espera para trabajos mayores.'}]),
  fr: mkSeo('Calculateur Assurance Dentaire', ['L\'assurance dentaire aide a gerer les couts de nettoyages, plombages et travaux majeurs.', 'Ce calculateur estime primes et economies selon la taille de la famille et les couts prevus.', 'Sans assurance, un nettoyage coute 200-400€ et une couronne 1 000-3 000€.', 'Consultez le <a href="/${lang}/tools/health-insurance-calculator">calculateur assurance sante</a>.'], [{q:'Ca vaut le coup?',a:'Pour la plupart oui, surtout si vous avez besoin de plus que des nettoyages.'},{q:'Que couvre-t-elle?',a:'Preventif a 100%, basique a 70-80%, majeur a 50%.'},{q:'Quel est le maximum annuel?',a:'La plupart couvrent jusqu\'a 1 000-2 500€/an.'},{q:'Y a-t-il un delai d\'attente?',a:'Beaucoup ont 6-12 mois pour les travaux majeurs.'}]),
  de: mkSeo('Zahnversicherungsrechner', ['Die Zahnversicherung hilft bei den Kosten fuer Reinigungen, Fuellungen und groessere Arbeiten.', 'Dieser Rechner schaetzt Praemien und Ersparnisse basierend auf Familiengroesse und erwarteten Kosten.', 'Ohne Versicherung kostet eine Reinigung 200-400€ und eine Krone 1.000-3.000€.', 'Nutzen Sie den <a href="/${lang}/tools/health-insurance-calculator">Krankenversicherungsrechner</a>.'], [{q:'Lohnt sie sich?',a:'Fuer die meisten ja, besonders wenn mehr als Reinigungen noetig sind.'},{q:'Was deckt sie ab?',a:'Vorsorge zu 100%, Basis zu 70-80%, Grosses zu 50%.'},{q:'Was ist das Jahresmaximum?',a:'Die meisten decken bis 1.000-2.500€/Jahr.'},{q:'Gibt es eine Wartezeit?',a:'Viele haben 6-12 Monate fuer groessere Arbeiten.'}]),
  pt: mkSeo('Calculadora de Seguro Dental', ['O seguro dental ajuda a gerenciar custos de limpezas, obturacoes e trabalhos maiores.', 'Esta calculadora estima premios e economias com base no tamanho da familia e custos esperados.', 'Sem seguro, uma limpeza custa R$200-400 e uma coroa R$1.000-3.000.', 'Consulte a <a href="/${lang}/tools/health-insurance-calculator">calculadora de seguro saude</a>.'], [{q:'Vale a pena?',a:'Para a maioria sim, especialmente se precisa mais que limpezas.'},{q:'O que cobre?',a:'Preventivo a 100%, basico a 70-80%, maior a 50%.'},{q:'Qual o maximo anual?',a:'A maioria cobre ate R$1.000-2.500/ano.'},{q:'Ha periodo de espera?',a:'Muitos tem 6-12 meses para trabalhos maiores.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="dental-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
