'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'weddingBudget', labels: { en: 'Wedding Budget ($)', it: 'Budget matrimonio (€)', es: 'Presupuesto boda ($)', fr: 'Budget mariage (€)', de: 'Hochzeitsbudget (€)', pt: 'Orcamento casamento (R$)' }, defaultValue: '30000' },
  { key: 'guestCount', labels: { en: 'Number of Guests', it: 'Numero invitati', es: 'Numero de invitados', fr: 'Nombre d\'invites', de: 'Gaestezahl', pt: 'Numero de convidados' }, defaultValue: '150', min: 10, max: 500 },
  { key: 'liabilityCoverage', labels: { en: 'Liability Coverage ($)', it: 'Copertura RC ($)', es: 'Cobertura responsabilidad ($)', fr: 'Couverture RC (€)', de: 'Haftpflichtdeckung (€)', pt: 'Cobertura RC (R$)' }, defaultValue: '1000000' },
  { key: 'cancellationCoverage', labels: { en: 'Cancellation Coverage ($)', it: 'Copertura cancellazione (€)', es: 'Cobertura cancelacion ($)', fr: 'Couverture annulation (€)', de: 'Stornierungsdeckung (€)', pt: 'Cobertura cancelamento (R$)' }, defaultValue: '25000' },
];
const results = [
  { key: 'premium', labels: { en: 'Total Premium', it: 'Premio totale', es: 'Prima total', fr: 'Prime totale', de: 'Gesamtpraemie', pt: 'Premio total' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'cancellationPremium', labels: { en: 'Cancellation Premium', it: 'Premio cancellazione', es: 'Prima cancelacion', fr: 'Prime annulation', de: 'Stornierungspraemie', pt: 'Premio cancelamento' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'liabilityPremium', labels: { en: 'Liability Premium', it: 'Premio RC', es: 'Prima responsabilidad', fr: 'Prime RC', de: 'Haftpflichtpraemie', pt: 'Premio RC' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'costPerGuest', labels: { en: 'Cost Per Guest', it: 'Costo per invitato', es: 'Costo por invitado', fr: 'Cout par invite', de: 'Kosten pro Gast', pt: 'Custo por convidado' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const budget = v.weddingBudget || 30000; const guests = v.guestCount || 150; const liability = v.liabilityCoverage || 1000000; const cancel = v.cancellationCoverage || 25000;
  const cancelPrem = cancel * 0.015; const liabPrem = (liability / 1000000) * 185 + guests * 0.5;
  const total = cancelPrem + liabPrem;
  return { premium: Math.round(total), cancellationPremium: Math.round(cancelPrem), liabilityPremium: Math.round(liabPrem), costPerGuest: Math.round((total / guests) * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Wedding Insurance Calculator: Protect Your Big Day', ['Wedding insurance protects your financial investment against cancellations, vendor no-shows, severe weather, and liability claims at your venue. With average weddings costing $30,000+, insurance is a smart investment.', 'This calculator estimates premiums for both cancellation/postponement coverage and liability protection based on your budget, guest count, and coverage levels.', 'Wedding insurance typically costs $150-$600 for a comprehensive policy. Cancellation coverage protects your deposits, while liability coverage is often required by venues.', 'For related tools, see our <a href="/${lang}/tools/umbrella-insurance-calculator">umbrella insurance calculator</a> and <a href="/${lang}/tools/jewelry-insurance-calculator">jewelry insurance calculator</a>.'], [{q:'What does wedding insurance cover?',a:'Cancellation due to illness/weather/vendor issues, liability for guest injuries, damage to venue, lost deposits, and sometimes damaged attire.'},{q:'How much does it cost?',a:'Typically $150-$600 for comprehensive coverage on a $30,000 wedding.'},{q:'When should I buy it?',a:'As soon as you book your venue and start making deposits. Coverage applies from the purchase date.'},{q:'Does it cover cold feet?',a:'No, voluntary cancellation (change of heart) is never covered. Only unforeseen circumstances qualify.'}]),
  it: mkSeo('Calcolatore Assicurazione Matrimonio', ['L\'assicurazione matrimonio protegge il tuo investimento da cancellazioni e imprevisti.', 'Questo calcolatore stima i premi per copertura cancellazione e responsabilita civile.', 'L\'assicurazione matrimonio costa tipicamente 150-600€ per una polizza completa.', 'Consulta il <a href="/${lang}/tools/jewelry-insurance-calculator">calcolatore assicurazione gioielli</a>.'], [{q:'Cosa copre?',a:'Cancellazione per malattia/meteo, responsabilita per infortuni degli invitati e depositi persi.'},{q:'Quanto costa?',a:'Tipicamente 150-600€ per una copertura completa.'},{q:'Quando comprarla?',a:'Appena si prenota la location.'},{q:'Copre il ripensamento?',a:'No, solo circostanze impreviste.'}]),
  es: mkSeo('Calculadora de Seguro de Boda', ['El seguro de boda protege tu inversion contra cancelaciones e imprevistos.', 'Esta calculadora estima primas para cobertura de cancelacion y responsabilidad civil.', 'El seguro de boda cuesta tipicamente $150-$600 para una poliza completa.', 'Consulta la <a href="/${lang}/tools/jewelry-insurance-calculator">calculadora de seguro de joyas</a>.'], [{q:'Que cubre?',a:'Cancelacion por enfermedad/clima, responsabilidad y depositos perdidos.'},{q:'Cuanto cuesta?',a:'Tipicamente $150-$600.'},{q:'Cuando comprarlo?',a:'Al reservar el lugar.'},{q:'Cubre arrepentimiento?',a:'No, solo circunstancias imprevistas.'}]),
  fr: mkSeo('Calculateur Assurance Mariage', ['L\'assurance mariage protege votre investissement contre les annulations et imprevu.', 'Ce calculateur estime les primes pour couverture annulation et responsabilite civile.', 'L\'assurance mariage coute typiquement 150-600€ pour une police complete.', 'Consultez le <a href="/${lang}/tools/jewelry-insurance-calculator">calculateur assurance bijoux</a>.'], [{q:'Que couvre-t-elle?',a:'Annulation pour maladie/meteo, responsabilite et acomptes perdus.'},{q:'Combien ca coute?',a:'Typiquement 150-600€.'},{q:'Quand l\'acheter?',a:'Des la reservation du lieu.'},{q:'Couvre-t-elle le changement d\'avis?',a:'Non, seulement les circonstances imprevues.'}]),
  de: mkSeo('Hochzeitsversicherungsrechner', ['Die Hochzeitsversicherung schuetzt Ihre Investition gegen Stornierungen und Unvorhergesehenes.', 'Dieser Rechner schaetzt Praemien fuer Stornierungs- und Haftpflichtdeckung.', 'Die Hochzeitsversicherung kostet typisch 150-600€.', 'Nutzen Sie den <a href="/${lang}/tools/jewelry-insurance-calculator">Schmuckversicherungsrechner</a>.'], [{q:'Was deckt sie ab?',a:'Stornierung wegen Krankheit/Wetter, Haftpflicht und verlorene Anzahlungen.'},{q:'Was kostet sie?',a:'Typisch 150-600€.'},{q:'Wann abschliessen?',a:'Bei Buchung der Location.'},{q:'Deckt sie kalte Fuesse ab?',a:'Nein, nur unvorhergesehene Umstaende.'}]),
  pt: mkSeo('Calculadora de Seguro de Casamento', ['O seguro de casamento protege seu investimento contra cancelamentos e imprevistos.', 'Esta calculadora estima premios para cobertura de cancelamento e responsabilidade civil.', 'O seguro de casamento custa tipicamente R$150-600 para uma apolice completa.', 'Consulte a <a href="/${lang}/tools/jewelry-insurance-calculator">calculadora de seguro de joias</a>.'], [{q:'O que cobre?',a:'Cancelamento por doenca/clima, responsabilidade e depositos perdidos.'},{q:'Quanto custa?',a:'Tipicamente R$150-600.'},{q:'Quando contratar?',a:'Ao reservar o local.'},{q:'Cobre desistencia?',a:'Nao, apenas circunstancias imprevistas.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="wedding-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
