'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'tripCost', labels: { en: 'Trip Cost ($)', it: 'Costo viaggio (€)', es: 'Costo del viaje ($)', fr: 'Cout du voyage (€)', de: 'Reisekosten (€)', pt: 'Custo da viagem (R$)' }, defaultValue: '3000' },
  { key: 'tripDuration', labels: { en: 'Trip Duration (days)', it: 'Durata viaggio (giorni)', es: 'Duracion viaje (dias)', fr: 'Duree voyage (jours)', de: 'Reisedauer (Tage)', pt: 'Duracao viagem (dias)' }, defaultValue: '14', min: 1, max: 365 },
  { key: 'travelerAge', labels: { en: 'Traveler Age', it: 'Eta viaggiatore', es: 'Edad viajero', fr: 'Age voyageur', de: 'Alter Reisender', pt: 'Idade viajante' }, defaultValue: '35', min: 18, max: 85 },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '100' },
];
const results = [
  { key: 'premium', labels: { en: 'Estimated Premium', it: 'Premio stimato', es: 'Prima estimada', fr: 'Prime estimee', de: 'Geschaetzte Praemie', pt: 'Premio estimado' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'medicalCoverage', labels: { en: 'Medical Coverage', it: 'Copertura medica', es: 'Cobertura medica', fr: 'Couverture medicale', de: 'Medizinische Deckung', pt: 'Cobertura medica' }, color: 'green' as const, format: 'currency' as const },
  { key: 'cancellationCoverage', labels: { en: 'Cancellation Coverage', it: 'Copertura cancellazione', es: 'Cobertura cancelacion', fr: 'Couverture annulation', de: 'Stornierungsdeckung', pt: 'Cobertura cancelamento' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'costPerDay', labels: { en: 'Cost Per Day', it: 'Costo al giorno', es: 'Costo por dia', fr: 'Cout par jour', de: 'Kosten pro Tag', pt: 'Custo por dia' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const cost = v.tripCost || 3000; const days = v.tripDuration || 14; const age = v.travelerAge || 35; const ded = v.deductible || 100;
  const basePct = 0.05; const ageFactor = age > 65 ? 1.5 : age > 50 ? 1.2 : 1.0; const durationFactor = 1 + (days - 7) * 0.005;
  const dedDiscount = (ded - 50) * 0.002; const premium = Math.max(20, cost * basePct * ageFactor * durationFactor - dedDiscount);
  return { premium: Math.round(premium), medicalCoverage: Math.round(cost * 5), cancellationCoverage: Math.round(cost), costPerDay: Math.round(premium / days * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Travel Insurance Calculator: Estimate Your Coverage Cost', ['Travel insurance protects your financial investment when unexpected events disrupt your trip. From medical emergencies abroad to trip cancellations, having the right coverage ensures peace of mind while exploring the world.', 'This calculator estimates your travel insurance premium based on trip cost, duration, traveler age, and deductible. Typical travel insurance costs 5-8% of your total trip cost, with higher rates for older travelers and longer trips.', 'Medical coverage abroad is often the most valuable component, as healthcare costs in foreign countries can be astronomical without insurance. Most policies also include trip cancellation, baggage loss, and emergency evacuation.', 'For related tools, see our <a href="/${lang}/tools/car-insurance-calculator">car insurance calculator</a> and <a href="/${lang}/tools/health-insurance-calculator">health insurance calculator</a>.'], [{q:'Is travel insurance worth it?',a:'Yes, especially for expensive trips, international travel, or travelers with pre-existing conditions. A single medical emergency abroad can cost tens of thousands.'},{q:'What does travel insurance cover?',a:'Most policies cover trip cancellation, medical emergencies, emergency evacuation, baggage loss/delay, and travel delays.'},{q:'When should I buy travel insurance?',a:'Buy it soon after booking your trip to maximize cancellation coverage. Some benefits like pre-existing condition waivers require purchase within 14-21 days of booking.'},{q:'Does travel insurance cover COVID-19?',a:'Many policies now cover COVID-related trip cancellations and medical treatment. Check your specific policy for details.'}]),
  it: mkSeo('Calcolatore Assicurazione Viaggio', ['L\'assicurazione viaggio protegge il tuo investimento quando eventi imprevisti interrompono il viaggio. Dalle emergenze mediche all\'estero alle cancellazioni, la giusta copertura garantisce tranquillita.', 'Questo calcolatore stima il premio in base a costo del viaggio, durata, eta e franchigia. Il costo tipico e il 5-8% del costo totale del viaggio.', 'La copertura medica all\'estero e spesso il componente piu prezioso. La maggior parte delle polizze include anche cancellazione, smarrimento bagagli e evacuazione d\'emergenza.', 'Consulta il nostro <a href="/${lang}/tools/car-insurance-calculator">calcolatore assicurazione auto</a> e il <a href="/${lang}/tools/health-insurance-calculator">calcolatore assicurazione sanitaria</a>.'], [{q:'Vale la pena l\'assicurazione viaggio?',a:'Si, specialmente per viaggi costosi e internazionali. Un\'emergenza medica all\'estero puo costare decine di migliaia di euro.'},{q:'Cosa copre?',a:'Cancellazione viaggio, emergenze mediche, evacuazione, smarrimento bagagli e ritardi.'},{q:'Quando comprarla?',a:'Subito dopo la prenotazione per massimizzare la copertura cancellazione.'},{q:'Copre il COVID-19?',a:'Molte polizze ora coprono cancellazioni e cure mediche legate al COVID.'}]),
  es: mkSeo('Calculadora Seguro de Viaje', ['El seguro de viaje protege tu inversion cuando eventos inesperados interrumpen tu viaje.', 'Esta calculadora estima tu prima segun costo del viaje, duracion, edad y deducible. El costo tipico es 5-8% del costo total.', 'La cobertura medica en el extranjero es el componente mas valioso.', 'Consulta nuestra <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro de auto</a>.'], [{q:'Vale la pena el seguro de viaje?',a:'Si, especialmente para viajes caros e internacionales.'},{q:'Que cubre?',a:'Cancelacion, emergencias medicas, evacuacion, equipaje perdido y retrasos.'},{q:'Cuando comprarlo?',a:'Inmediatamente despues de reservar para maximizar la cobertura.'},{q:'Cubre el COVID-19?',a:'Muchas polizas ahora cubren cancelaciones y tratamiento medico por COVID.'}]),
  fr: mkSeo('Calculateur Assurance Voyage', ['L\'assurance voyage protege votre investissement quand des evenements imprevus perturbent votre voyage.', 'Ce calculateur estime votre prime selon le cout du voyage, la duree, l\'age et la franchise. Le cout typique est 5-8% du cout total.', 'La couverture medicale a l\'etranger est le composant le plus precieux.', 'Consultez notre <a href="/${lang}/tools/car-insurance-calculator">calculateur assurance auto</a>.'], [{q:'L\'assurance voyage en vaut-elle la peine?',a:'Oui, surtout pour les voyages couteux et internationaux.'},{q:'Que couvre-t-elle?',a:'Annulation, urgences medicales, evacuation, bagages perdus et retards.'},{q:'Quand l\'acheter?',a:'Des la reservation pour maximiser la couverture annulation.'},{q:'Couvre-t-elle le COVID-19?',a:'De nombreuses polices couvrent maintenant les annulations et traitements lies au COVID.'}]),
  de: mkSeo('Reiseversicherungsrechner', ['Die Reiseversicherung schuetzt Ihre finanzielle Investition bei unerwarteten Reiseunterbrechungen.', 'Dieser Rechner schaetzt Ihre Praemie basierend auf Reisekosten, Dauer, Alter und Selbstbeteiligung. Typische Kosten: 5-8% der Gesamtreisekosten.', 'Die medizinische Deckung im Ausland ist oft der wertvollste Bestandteil.', 'Nutzen Sie unseren <a href="/${lang}/tools/car-insurance-calculator">Kfz-Versicherungsrechner</a>.'], [{q:'Lohnt sich eine Reiseversicherung?',a:'Ja, besonders fuer teure und internationale Reisen.'},{q:'Was wird abgedeckt?',a:'Stornierung, medizinische Notfaelle, Evakuierung, Gepaeckverlust und Verspaetungen.'},{q:'Wann abschliessen?',a:'Direkt nach der Buchung fuer maximalen Stornierungsschutz.'},{q:'Deckt sie COVID-19 ab?',a:'Viele Policen decken jetzt COVID-bedingte Stornierungen und Behandlungen ab.'}]),
  pt: mkSeo('Calculadora Seguro Viagem', ['O seguro viagem protege seu investimento quando eventos inesperados interrompem sua viagem.', 'Esta calculadora estima seu premio com base no custo da viagem, duracao, idade e franquia. O custo tipico e 5-8% do custo total.', 'A cobertura medica no exterior e o componente mais valioso.', 'Consulte nossa <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro auto</a>.'], [{q:'O seguro viagem vale a pena?',a:'Sim, especialmente para viagens caras e internacionais.'},{q:'O que cobre?',a:'Cancelamento, emergencias medicas, evacuacao, bagagem perdida e atrasos.'},{q:'Quando contratar?',a:'Logo apos a reserva para maximizar a cobertura de cancelamento.'},{q:'Cobre COVID-19?',a:'Muitas apolices agora cobrem cancelamentos e tratamentos relacionados ao COVID.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="travel-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
