'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'annualHVAC', labels: { en: 'Annual HVAC Cost ($)', it: 'Costo HVAC annuale (€)', es: 'Costo HVAC anual ($)', fr: 'Cout HVAC annuel (€)', de: 'Jaehrliche HVAC-Kosten (€)', pt: 'Custo HVAC anual (R$)' }, defaultValue: '1800' },
  { key: 'thermostatCost', labels: { en: 'Smart Thermostat Cost ($)', it: 'Costo termostato smart (€)', es: 'Costo termostato inteligente ($)', fr: 'Cout thermostat intelligent (€)', de: 'Smart-Thermostat-Kosten (€)', pt: 'Custo termostato inteligente (R$)' }, defaultValue: '250' },
  { key: 'hoursAway', labels: { en: 'Hours Away From Home/Day', it: 'Ore fuori casa/giorno', es: 'Horas fuera de casa/dia', fr: 'Heures hors domicile/jour', de: 'Stunden ausser Haus/Tag', pt: 'Horas fora de casa/dia' }, defaultValue: '10', min: 0, max: 20 },
  { key: 'existingProgrammable', labels: { en: 'Have Programmable (0=no,1=yes)', it: 'Hai programmabile (0=no,1=si)', es: 'Tienes programable (0=no,1=si)', fr: 'Avez programmable (0=non,1=oui)', de: 'Haben programmierbaren (0=nein,1=ja)', pt: 'Tem programavel (0=nao,1=sim)' }, defaultValue: '0', min: 0, max: 1 },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackMonths', labels: { en: 'Payback (months)', it: 'Ammortamento (mesi)', es: 'Amortizacion (meses)', fr: 'Amortissement (mois)', de: 'Amortisation (Monate)', pt: 'Amortizacao (meses)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'fiveYearSavings', labels: { en: '5-Year Net Savings', it: 'Risparmio netto 5 anni', es: 'Ahorro neto 5 anos', fr: 'Economies nettes 5 ans', de: '5-Jahres-Nettoeinsparung', pt: 'Economia liquida 5 anos' }, color: 'green' as const, format: 'currency' as const },
  { key: 'savingsPercent', labels: { en: 'HVAC Savings (%)', it: 'Risparmio HVAC (%)', es: 'Ahorro HVAC (%)', fr: 'Economies HVAC (%)', de: 'HVAC-Ersparnis (%)', pt: 'Economia HVAC (%)' }, color: 'gray' as const, format: 'percent' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const hvac = v.annualHVAC || 1800; const cost = v.thermostatCost || 250; const hours = v.hoursAway || 10; const existing = v.existingProgrammable || 0;
  const baseSavingsPct = existing ? 0.08 : 0.15; const awayBonus = (hours / 24) * 0.1;
  const totalPct = Math.min(0.30, baseSavingsPct + awayBonus);
  const savings = hvac * totalPct; const payback = savings > 0 ? (cost / savings) * 12 : 99;
  return { annualSavings: Math.round(savings), paybackMonths: Math.round(payback), fiveYearSavings: Math.round(savings * 5 - cost), savingsPercent: Math.round(totalPct * 100) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Smart Thermostat Savings Calculator', ['A smart thermostat can save 10-25% on heating and cooling costs by learning your schedule and automatically adjusting temperatures when you are away or asleep.', 'This calculator estimates your annual HVAC savings based on current costs, time away from home, and whether you already have a programmable thermostat.', 'The EPA estimates that smart thermostats save an average of $50-$180 per year. The more time you spend away from home, the greater your savings potential.', 'For related tools, see our <a href="/${lang}/tools/heat-pump-calculator">heat pump calculator</a> and <a href="/${lang}/tools/home-energy-audit-calculator">home energy audit calculator</a>.'], [{q:'How much do smart thermostats save?',a:'On average, 10-25% on HVAC costs, or $50-$180 per year. Savings depend on your schedule and current thermostat type.'},{q:'Are smart thermostats worth it?',a:'Yes, most pay for themselves in 6-18 months and last 5-10 years. They also add convenience and comfort.'},{q:'Which smart thermostat is best?',a:'Popular options include Nest, Ecobee, and Honeywell. All offer similar savings. Choose based on your smart home ecosystem.'},{q:'Do they work with my HVAC system?',a:'Most smart thermostats are compatible with 90%+ of HVAC systems. Check compatibility on the manufacturer website before buying.'}]),
  it: mkSeo('Calcolatore Risparmio Termostato Smart', ['Un termostato smart puo far risparmiare il 10-25% sui costi di climatizzazione.', 'Questo calcolatore stima il risparmio HVAC annuale basato sui costi attuali e sul tempo fuori casa.', 'L\'EPA stima che i termostati smart risparmiano in media 50-180€/anno.', 'Consulta il <a href="/${lang}/tools/heat-pump-calculator">calcolatore pompa di calore</a>.'], [{q:'Quanto risparmiano?',a:'In media il 10-25% sui costi HVAC, o 50-180€/anno.'},{q:'Valgono l\'investimento?',a:'Si, si ripagano in 6-18 mesi e durano 5-10 anni.'},{q:'Quale e il migliore?',a:'Nest, Ecobee e Honeywell sono tutti validi. Scegli in base al tuo ecosistema smart home.'},{q:'Funzionano con il mio impianto?',a:'La maggior parte e compatibile con il 90%+ degli impianti HVAC.'}]),
  es: mkSeo('Calculadora Ahorro Termostato Inteligente', ['Un termostato inteligente puede ahorrar 10-25% en costos de climatizacion.', 'Esta calculadora estima tu ahorro HVAC anual segun tus costos y tiempo fuera de casa.', 'La EPA estima que los termostatos inteligentes ahorran $50-$180/ano en promedio.', 'Consulta la <a href="/${lang}/tools/heat-pump-calculator">calculadora bomba de calor</a>.'], [{q:'Cuanto ahorran?',a:'En promedio 10-25% en costos HVAC, o $50-$180/ano.'},{q:'Valen la pena?',a:'Si, se amortizan en 6-18 meses y duran 5-10 anos.'},{q:'Cual es el mejor?',a:'Nest, Ecobee y Honeywell son todos buenos.'},{q:'Funcionan con mi sistema?',a:'La mayoria es compatible con el 90%+ de los sistemas HVAC.'}]),
  fr: mkSeo('Calculateur Economies Thermostat Intelligent', ['Un thermostat intelligent peut economiser 10-25% sur les couts de climatisation.', 'Ce calculateur estime vos economies HVAC annuelles selon vos couts et votre temps hors domicile.', 'L\'EPA estime que les thermostats intelligents economisent 50-180€/an en moyenne.', 'Consultez le <a href="/${lang}/tools/heat-pump-calculator">calculateur pompe a chaleur</a>.'], [{q:'Combien economisent-ils?',a:'En moyenne 10-25% sur les couts HVAC, soit 50-180€/an.'},{q:'En valent-ils la peine?',a:'Oui, ils se rentabilisent en 6-18 mois et durent 5-10 ans.'},{q:'Lequel est le meilleur?',a:'Nest, Ecobee et Honeywell sont tous de bons choix.'},{q:'Fonctionnent-ils avec mon systeme?',a:'La plupart sont compatibles avec 90%+ des systemes HVAC.'}]),
  de: mkSeo('Smart-Thermostat-Ersparnis-Rechner', ['Ein Smart-Thermostat kann 10-25% bei Heiz- und Kuehlkosten sparen.', 'Dieser Rechner schaetzt Ihre jaehrliche HVAC-Ersparnis basierend auf aktuellen Kosten und Abwesenheitszeit.', 'Die EPA schaetzt, dass Smart-Thermostate durchschnittlich 50-180€/Jahr sparen.', 'Nutzen Sie den <a href="/${lang}/tools/heat-pump-calculator">Waermepumpen-Rechner</a>.'], [{q:'Wie viel sparen sie?',a:'Durchschnittlich 10-25% bei HVAC-Kosten, oder 50-180€/Jahr.'},{q:'Lohnen sie sich?',a:'Ja, sie amortisieren sich in 6-18 Monaten und halten 5-10 Jahre.'},{q:'Welcher ist der beste?',a:'Nest, Ecobee und Honeywell sind alle gut.'},{q:'Funktionieren sie mit meinem System?',a:'Die meisten sind mit 90%+ der HVAC-Systeme kompatibel.'}]),
  pt: mkSeo('Calculadora Economia Termostato Inteligente', ['Um termostato inteligente pode economizar 10-25% nos custos de climatizacao.', 'Esta calculadora estima sua economia HVAC anual com base nos custos e tempo fora de casa.', 'A EPA estima que termostatos inteligentes economizam R$50-180/ano em media.', 'Consulte a <a href="/${lang}/tools/heat-pump-calculator">calculadora bomba de calor</a>.'], [{q:'Quanto economizam?',a:'Em media 10-25% nos custos HVAC, ou R$50-180/ano.'},{q:'Valem a pena?',a:'Sim, se pagam em 6-18 meses e duram 5-10 anos.'},{q:'Qual e o melhor?',a:'Nest, Ecobee e Honeywell sao todos bons.'},{q:'Funcionam com meu sistema?',a:'A maioria e compativel com 90%+ dos sistemas HVAC.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="smart-thermostat-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
