'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'numBulbs', labels: { en: 'Number of Bulbs', it: 'Numero di lampadine', es: 'Numero de bombillas', fr: 'Nombre d\'ampoules', de: 'Anzahl Gluehbirnen', pt: 'Numero de lampadas' }, defaultValue: '30', min: 1, max: 100 },
  { key: 'oldWattage', labels: { en: 'Old Bulb Wattage (W)', it: 'Watt lampadina vecchia (W)', es: 'Watts bombilla vieja (W)', fr: 'Watts ancienne ampoule (W)', de: 'Alte Wattzahl (W)', pt: 'Watts lampada antiga (W)' }, defaultValue: '60' },
  { key: 'hoursPerDay', labels: { en: 'Hours On Per Day', it: 'Ore accese al giorno', es: 'Horas encendidas/dia', fr: 'Heures allumees/jour', de: 'Stunden an/Tag', pt: 'Horas ligadas/dia' }, defaultValue: '5', min: 1, max: 24 },
  { key: 'electricityRate', labels: { en: 'Electricity ($/kWh)', it: 'Elettricita (€/kWh)', es: 'Electricidad ($/kWh)', fr: 'Electricite (€/kWh)', de: 'Strom (€/kWh)', pt: 'Eletricidade (R$/kWh)' }, defaultValue: '0.13', step: 0.01 },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'kwhSaved', labels: { en: 'kWh Saved/Year', it: 'kWh risparmiati/anno', es: 'kWh ahorrados/ano', fr: 'kWh economises/an', de: 'kWh gespart/Jahr', pt: 'kWh economizados/ano' }, color: 'blue' as const, format: 'number' as const },
  { key: 'paybackMonths', labels: { en: 'Payback (months)', it: 'Ammortamento (mesi)', es: 'Amortizacion (meses)', fr: 'Amortissement (mois)', de: 'Amortisation (Monate)', pt: 'Amortizacao (meses)' }, color: 'gray' as const, format: 'number' as const },
  { key: 'co2Saved', labels: { en: 'CO2 Saved (lbs/yr)', it: 'CO2 risparmiata (kg/anno)', es: 'CO2 ahorrado (lbs/ano)', fr: 'CO2 economise (kg/an)', de: 'CO2 gespart (kg/Jahr)', pt: 'CO2 economizado (kg/ano)' }, color: 'green' as const, format: 'number' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const bulbs = v.numBulbs || 30; const oldW = v.oldWattage || 60; const hours = v.hoursPerDay || 5; const rate = v.electricityRate || 0.13;
  const ledW = oldW * 0.15; // LEDs use ~85% less energy
  const oldKwh = (bulbs * oldW * hours * 365) / 1000; const ledKwh = (bulbs * ledW * hours * 365) / 1000;
  const saved = oldKwh - ledKwh; const savings = saved * rate;
  const ledCost = bulbs * 3; // ~$3 per LED bulb
  const payback = savings > 0 ? (ledCost / savings) * 12 : 99;
  return { annualSavings: Math.round(savings), kwhSaved: Math.round(saved), paybackMonths: Math.round(payback), co2Saved: Math.round(saved * 0.92) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('LED Savings Calculator: How Much Can You Save?', ['Switching to LED bulbs is one of the easiest and most cost-effective energy upgrades. LEDs use 75-85% less energy than incandescent bulbs and last 15-25 times longer.', 'This calculator estimates your annual energy and cost savings from switching all your bulbs to LED, plus the payback period for the LED investment.', 'A typical household with 30 light bulbs can save $100-$300 per year by switching to LEDs. The bulbs pay for themselves in just 2-6 months.', 'For related tools, see our <a href="/${lang}/tools/home-energy-audit-calculator">home energy audit calculator</a> and <a href="/${lang}/tools/smart-thermostat-calculator">smart thermostat calculator</a>.'], [{q:'How much do LED bulbs save?',a:'LEDs use 75-85% less energy than incandescents. A typical household saves $100-$300/year.'},{q:'How long do LED bulbs last?',a:'LED bulbs last 15,000-50,000 hours, or 15-25 years at typical usage, vs 1,000 hours for incandescents.'},{q:'Are LED bulbs worth the higher price?',a:'Absolutely. Despite costing $2-5 each, LEDs pay for themselves in 2-6 months and save $5-$10/year per bulb.'},{q:'Do LEDs work with dimmers?',a:'Most modern LEDs are dimmable. Check the packaging for "dimmable" labeling. Using a dimmer can save an additional 10-20%.'}]),
  it: mkSeo('Calcolatore Risparmio LED', ['Passare ai LED e uno degli upgrade energetici piu semplici ed efficaci.', 'Questo calcolatore stima il risparmio annuale e il periodo di ammortamento.', 'Una famiglia tipica con 30 lampadine risparmia 100-300€/anno passando ai LED.', 'Consulta il <a href="/${lang}/tools/home-energy-audit-calculator">calcolatore audit energetico</a>.'], [{q:'Quanto risparmiano i LED?',a:'I LED usano il 75-85% in meno di energia. Risparmio tipico: 100-300€/anno.'},{q:'Quanto durano?',a:'15.000-50.000 ore, o 15-25 anni con uso tipico.'},{q:'Valgono il prezzo piu alto?',a:'Assolutamente. Si ripagano in 2-6 mesi.'},{q:'Funzionano con i dimmer?',a:'La maggior parte dei LED moderni e dimmerabile.'}]),
  es: mkSeo('Calculadora Ahorro LED', ['Cambiar a LED es una de las mejoras energeticas mas faciles y rentables.', 'Esta calculadora estima tu ahorro anual y el periodo de amortizacion.', 'Un hogar tipico con 30 bombillas ahorra $100-$300/ano con LED.', 'Consulta la <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Cuanto ahorran los LED?',a:'Los LED usan 75-85% menos energia. Ahorro tipico: $100-$300/ano.'},{q:'Cuanto duran?',a:'15,000-50,000 horas, o 15-25 anos.'},{q:'Valen el precio mas alto?',a:'Absolutamente. Se amortizan en 2-6 meses.'},{q:'Funcionan con reguladores?',a:'La mayoria de LED modernos son regulables.'}]),
  fr: mkSeo('Calculateur Economies LED', ['Passer aux LED est l\'une des ameliorations energetiques les plus simples et rentables.', 'Ce calculateur estime vos economies annuelles et l\'amortissement.', 'Un foyer typique avec 30 ampoules economise 100-300€/an avec des LED.', 'Consultez le <a href="/${lang}/tools/home-energy-audit-calculator">calculateur audit energetique</a>.'], [{q:'Combien economisent les LED?',a:'Les LED utilisent 75-85% moins d\'energie. Economie typique: 100-300€/an.'},{q:'Combien de temps durent-elles?',a:'15 000-50 000 heures, soit 15-25 ans.'},{q:'Valent-elles le prix plus eleve?',a:'Absolument. Elles se rentabilisent en 2-6 mois.'},{q:'Fonctionnent-elles avec des variateurs?',a:'La plupart des LED modernes sont compatibles variateurs.'}]),
  de: mkSeo('LED-Ersparnis-Rechner', ['Der Umstieg auf LED ist eines der einfachsten und kosteneffektivsten Energie-Upgrades.', 'Dieser Rechner schaetzt Ihre jaehrliche Ersparnis und Amortisationszeit.', 'Ein typischer Haushalt mit 30 Gluehbirnen spart 100-300€/Jahr mit LED.', 'Nutzen Sie den <a href="/${lang}/tools/home-energy-audit-calculator">Energieaudit-Rechner</a>.'], [{q:'Wie viel sparen LEDs?',a:'LEDs verbrauchen 75-85% weniger Energie. Typische Ersparnis: 100-300€/Jahr.'},{q:'Wie lange halten sie?',a:'15.000-50.000 Stunden, oder 15-25 Jahre.'},{q:'Lohnt sich der hoehere Preis?',a:'Absolut. Sie amortisieren sich in 2-6 Monaten.'},{q:'Funktionieren sie mit Dimmern?',a:'Die meisten modernen LEDs sind dimmbar.'}]),
  pt: mkSeo('Calculadora Economia LED', ['Mudar para LED e uma das melhorias energeticas mais faceis e rentaveis.', 'Esta calculadora estima sua economia anual e o periodo de amortizacao.', 'Uma familia tipica com 30 lampadas economiza R$100-300/ano com LED.', 'Consulte a <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Quanto os LEDs economizam?',a:'LEDs usam 75-85% menos energia. Economia tipica: R$100-300/ano.'},{q:'Quanto duram?',a:'15.000-50.000 horas, ou 15-25 anos.'},{q:'Valem o preco mais alto?',a:'Absolutamente. Se pagam em 2-6 meses.'},{q:'Funcionam com dimmers?',a:'A maioria dos LEDs modernos e dimerizavel.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="led-savings-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
