'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'annualMiles', labels: { en: 'Annual Miles', it: 'Km annuali', es: 'Millas anuales', fr: 'Km annuels', de: 'Jaehrliche Km', pt: 'Km anuais' }, defaultValue: '12000' },
  { key: 'gasPrice', labels: { en: 'Gas Price ($/gal)', it: 'Prezzo benzina (€/L)', es: 'Precio gasolina ($/gal)', fr: 'Prix essence (€/L)', de: 'Benzinpreis (€/L)', pt: 'Preco gasolina (R$/L)' }, defaultValue: '3.50', step: 0.1 },
  { key: 'electricityRate', labels: { en: 'Electricity ($/kWh)', it: 'Elettricita (€/kWh)', es: 'Electricidad ($/kWh)', fr: 'Electricite (€/kWh)', de: 'Strom (€/kWh)', pt: 'Eletricidade (R$/kWh)' }, defaultValue: '0.13', step: 0.01 },
  { key: 'taxCredit', labels: { en: 'EV Tax Credit ($)', it: 'Credito imposta EV (€)', es: 'Credito fiscal EV ($)', fr: 'Credit impot VE (€)', de: 'EV-Steuergutschrift (€)', pt: 'Credito fiscal EV (R$)' }, defaultValue: '7500' },
];
const results = [
  { key: 'annualFuelSavings', labels: { en: 'Annual Fuel Savings', it: 'Risparmio carburante/anno', es: 'Ahorro combustible/ano', fr: 'Economies carburant/an', de: 'Kraftstoffersparnis/Jahr', pt: 'Economia combustivel/ano' }, color: 'green' as const, format: 'currency' as const },
  { key: 'maintenanceSavings', labels: { en: 'Annual Maintenance Savings', it: 'Risparmio manutenzione/anno', es: 'Ahorro mantenimiento/ano', fr: 'Economies entretien/an', de: 'Wartungsersparnis/Jahr', pt: 'Economia manutencao/ano' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'fiveYearTotal', labels: { en: '5-Year Total Savings', it: 'Risparmio totale 5 anni', es: 'Ahorro total 5 anos', fr: 'Economies totales 5 ans', de: '5-Jahres-Gesamtersparnis', pt: 'Economia total 5 anos' }, color: 'green' as const, format: 'currency' as const },
  { key: 'totalWithCredit', labels: { en: '5-Year + Tax Credit', it: '5 anni + credito imposta', es: '5 anos + credito fiscal', fr: '5 ans + credit impot', de: '5 Jahre + Steuergutschrift', pt: '5 anos + credito fiscal' }, color: 'green' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const miles = v.annualMiles || 12000; const gas = v.gasPrice || 3.5; const elec = v.electricityRate || 0.13; const credit = v.taxCredit || 7500;
  const gasCostPerMile = gas / 30; const evCostPerMile = elec / 3.5;
  const fuelSave = (gasCostPerMile - evCostPerMile) * miles; const maintSave = 600;
  const fiveYear = (fuelSave + maintSave) * 5;
  return { annualFuelSavings: Math.round(fuelSave), maintenanceSavings: maintSave, fiveYearTotal: Math.round(fiveYear), totalWithCredit: Math.round(fiveYear + credit) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('EV Savings Calculator: Total Savings From Going Electric', ['Switching to an electric vehicle can save thousands of dollars over its lifetime through lower fuel costs, reduced maintenance, and available tax incentives.', 'This calculator estimates your total savings including fuel costs, maintenance reduction, and federal/state tax credits. The average EV driver saves $1,500-$2,500 per year.', 'Beyond fuel savings, EVs have significantly lower maintenance costs: no oil changes, fewer brake replacements, and no transmission servicing.', 'For related tools, see our <a href="/${lang}/tools/ev-vs-gas-calculator">EV vs gas calculator</a> and <a href="/${lang}/tools/ev-charging-cost-calculator">EV charging cost calculator</a>.'], [{q:'How much can I save by switching to an EV?',a:'Most drivers save $1,500-$2,500/year in fuel and maintenance, plus up to $7,500 in federal tax credits.'},{q:'What maintenance does an EV need?',a:'Primarily tire rotation, cabin air filter, brake fluid, and battery coolant. No oil changes, spark plugs, or transmission service.'},{q:'How long do EV batteries last?',a:'Most last 200,000-300,000 miles with warranty coverage of 8 years/100,000 miles.'},{q:'Do all EVs qualify for the tax credit?',a:'Not all. The $7,500 federal credit has assembly and battery sourcing requirements. Check IRS guidelines for eligible models.'}]),
  it: mkSeo('Calcolatore Risparmio EV', ['Passare a un veicolo elettrico puo far risparmiare migliaia di euro.', 'Questo calcolatore stima il risparmio totale inclusi carburante, manutenzione e incentivi fiscali.', 'Oltre al carburante, le EV hanno costi di manutenzione significativamente inferiori.', 'Consulta il <a href="/${lang}/tools/ev-vs-gas-calculator">calcolatore EV vs benzina</a>.'], [{q:'Quanto posso risparmiare?',a:'La maggior parte risparmia 1.500-2.500€/anno tra carburante e manutenzione.'},{q:'Che manutenzione serve?',a:'Principalmente rotazione gomme, filtro abitacolo e liquido freni.'},{q:'Quanto dura la batteria?',a:'200.000-300.000 km con garanzia di 8 anni.'},{q:'Tutti gli EV hanno il credito d\'imposta?',a:'Non tutti. Verifica i requisiti specifici nel tuo paese.'}]),
  es: mkSeo('Calculadora de Ahorro EV', ['Cambiar a un vehiculo electrico puede ahorrar miles de dolares.', 'Esta calculadora estima tu ahorro total incluyendo combustible, mantenimiento e incentivos.', 'Ademas del combustible, los EV tienen costos de mantenimiento significativamente menores.', 'Consulta la <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'Cuanto puedo ahorrar?',a:'La mayoria ahorra $1,500-$2,500/ano en combustible y mantenimiento.'},{q:'Que mantenimiento necesita?',a:'Principalmente rotacion de llantas, filtro de cabina y liquido de frenos.'},{q:'Cuanto dura la bateria?',a:'200,000-300,000 millas con garantia de 8 anos.'},{q:'Todos los EV califican para el credito?',a:'No todos. Verifica los requisitos del IRS.'}]),
  fr: mkSeo('Calculateur Economies VE', ['Passer a un vehicule electrique peut faire economiser des milliers d\'euros.', 'Ce calculateur estime vos economies totales incluant carburant, entretien et incitations fiscales.', 'Au-dela du carburant, les VE ont des couts d\'entretien significativement inferieurs.', 'Consultez le <a href="/${lang}/tools/ev-vs-gas-calculator">calculateur VE vs essence</a>.'], [{q:'Combien puis-je economiser?',a:'La plupart economisent 1 500-2 500€/an.'},{q:'Quel entretien faut-il?',a:'Principalement rotation des pneus, filtre habitacle et liquide de freins.'},{q:'Combien de temps dure la batterie?',a:'200 000-300 000 km avec garantie de 8 ans.'},{q:'Tous les VE ont le credit d\'impot?',a:'Non, verifiez les conditions specifiques.'}]),
  de: mkSeo('E-Auto Ersparnis-Rechner', ['Der Umstieg auf ein E-Auto kann Tausende Euro sparen.', 'Dieser Rechner schaetzt Ihre Gesamtersparnis inkl. Kraftstoff, Wartung und Steuervorteile.', 'Neben Kraftstoff haben E-Autos deutlich niedrigere Wartungskosten.', 'Nutzen Sie den <a href="/${lang}/tools/ev-vs-gas-calculator">E-Auto vs Benziner Rechner</a>.'], [{q:'Wie viel kann ich sparen?',a:'Die meisten sparen 1.500-2.500€/Jahr.'},{q:'Welche Wartung braucht es?',a:'Hauptsaechlich Reifenwechsel, Innenraumfilter und Bremsfluessigkeit.'},{q:'Wie lange haelt die Batterie?',a:'200.000-300.000 km mit 8 Jahren Garantie.'},{q:'Haben alle E-Autos Steuervorteile?',a:'Nicht alle. Pruefen Sie die spezifischen Bedingungen.'}]),
  pt: mkSeo('Calculadora de Economia EV', ['Mudar para um veiculo eletrico pode economizar milhares de reais.', 'Esta calculadora estima sua economia total incluindo combustivel, manutencao e incentivos.', 'Alem do combustivel, os EVs tem custos de manutencao significativamente menores.', 'Consulte a <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'Quanto posso economizar?',a:'A maioria economiza R$1.500-2.500/ano.'},{q:'Que manutencao precisa?',a:'Principalmente rodizio de pneus, filtro de ar e fluido de freio.'},{q:'Quanto dura a bateria?',a:'200.000-300.000 km com garantia de 8 anos.'},{q:'Todos os EVs tem credito fiscal?',a:'Nao, verifique as condicoes especificas.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="ev-savings-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
