'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'totalAssets', labels: { en: 'Total Assets ($)', it: 'Patrimonio totale (€)', es: 'Activos totales ($)', fr: 'Actifs totaux (€)', de: 'Gesamtvermoegen (€)', pt: 'Patrimonio total (R$)' }, defaultValue: '500000' },
  { key: 'annualIncome', labels: { en: 'Annual Income ($)', it: 'Reddito annuale (€)', es: 'Ingreso anual ($)', fr: 'Revenu annuel (€)', de: 'Jahreseinkommen (€)', pt: 'Renda anual (R$)' }, defaultValue: '100000' },
  { key: 'numProperties', labels: { en: 'Number of Properties', it: 'Numero di proprieta', es: 'Numero de propiedades', fr: 'Nombre de proprietes', de: 'Anzahl Immobilien', pt: 'Numero de propriedades' }, defaultValue: '1', min: 0, max: 10 },
  { key: 'numVehicles', labels: { en: 'Number of Vehicles', it: 'Numero di veicoli', es: 'Numero de vehiculos', fr: 'Nombre de vehicules', de: 'Anzahl Fahrzeuge', pt: 'Numero de veiculos' }, defaultValue: '2', min: 0, max: 10 },
];
const results = [
  { key: 'recommendedCoverage', labels: { en: 'Recommended Coverage', it: 'Copertura raccomandata', es: 'Cobertura recomendada', fr: 'Couverture recommandee', de: 'Empfohlene Deckung', pt: 'Cobertura recomendada' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Est. Annual Premium', it: 'Premio annuale stimato', es: 'Prima anual estimada', fr: 'Prime annuelle estimee', de: 'Geschaetzte Jahrespraemie', pt: 'Premio anual estimado' }, color: 'green' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Est. Monthly Premium', it: 'Premio mensile stimato', es: 'Prima mensual estimada', fr: 'Prime mensuelle estimee', de: 'Monatliche Praemie', pt: 'Premio mensal estimado' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'costPerMillion', labels: { en: 'Cost Per $1M Coverage', it: 'Costo per 1M€ copertura', es: 'Costo por $1M cobertura', fr: 'Cout par 1M€ couverture', de: 'Kosten pro 1M€ Deckung', pt: 'Custo por R$1M cobertura' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const assets = v.totalAssets || 500000; const income = v.annualIncome || 100000;
  const props = v.numProperties || 1; const vehicles = v.numVehicles || 2;
  const recommended = Math.max(1000000, assets + income * 2);
  const riskFactor = 1 + props * 0.1 + vehicles * 0.05;
  const basePremium = (recommended / 1000000) * 300 * riskFactor;
  return { recommendedCoverage: Math.round(recommended), annualPremium: Math.round(basePremium), monthlyPremium: Math.round(basePremium / 12), costPerMillion: Math.round(basePremium / (recommended / 1000000)) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Umbrella Insurance Calculator: Estimate Your Coverage', ['Umbrella insurance provides an extra layer of liability protection beyond your existing home and auto policies. It kicks in when your other policy limits are exhausted, protecting your assets from major lawsuits and claims.', 'This calculator estimates recommended coverage based on your total assets, income, properties, and vehicles. Most financial advisors recommend coverage equal to your total net worth at minimum.', 'Umbrella policies are surprisingly affordable, typically costing $150-$400 per year for $1 million in additional coverage. Each additional million usually costs $50-$100 more.', 'For related tools, see our <a href="/${lang}/tools/home-insurance-calculator">home insurance calculator</a> and <a href="/${lang}/tools/car-insurance-calculator">car insurance calculator</a>.'], [{q:'What does umbrella insurance cover?',a:'It covers liability claims that exceed your auto or home insurance limits, including bodily injury, property damage, defamation, and certain lawsuits.'},{q:'How much umbrella insurance do I need?',a:'At minimum, coverage should equal your total net worth (assets minus debts). High-income earners should add 2-3 years of income.'},{q:'Is umbrella insurance expensive?',a:'No, it is one of the most affordable insurance types. $1 million in coverage typically costs $150-$400 per year.'},{q:'Do I need umbrella insurance?',a:'If you own a home, have significant assets, or face higher-than-average liability risk (pool, trampoline, teen drivers), umbrella insurance is highly recommended.'}]),
  it: mkSeo('Calcolatore Assicurazione Ombrello', ['L\'assicurazione ombrello fornisce un ulteriore livello di protezione responsabilita civile oltre alle polizze casa e auto esistenti.', 'Questo calcolatore stima la copertura raccomandata in base a patrimonio, reddito, proprieta e veicoli.', 'Le polizze ombrello sono sorprendentemente convenienti, con costi tipici di 150-400€ all\'anno per 1 milione di copertura aggiuntiva.', 'Consulta il nostro <a href="/${lang}/tools/home-insurance-calculator">calcolatore assicurazione casa</a>.'], [{q:'Cosa copre l\'assicurazione ombrello?',a:'Copre richieste di risarcimento che superano i limiti delle polizze auto o casa.'},{q:'Quanta copertura mi serve?',a:'Come minimo, uguale al patrimonio netto totale.'},{q:'E costosa?',a:'No, 1 milione di copertura costa tipicamente 150-400€ all\'anno.'},{q:'Ne ho bisogno?',a:'Se possiedi una casa o hai beni significativi, e altamente raccomandata.'}]),
  es: mkSeo('Calculadora Seguro Paraguas', ['El seguro paraguas proporciona una capa adicional de proteccion de responsabilidad civil.', 'Esta calculadora estima la cobertura recomendada segun tus activos, ingresos y propiedades.', 'Las polizas paraguas son sorprendentemente asequibles, costando tipicamente $150-$400 al ano por $1 millon.', 'Consulta nuestra <a href="/${lang}/tools/home-insurance-calculator">calculadora de seguro de hogar</a>.'], [{q:'Que cubre el seguro paraguas?',a:'Cubre reclamaciones que exceden los limites de tus polizas de auto o hogar.'},{q:'Cuanta cobertura necesito?',a:'Como minimo, igual a tu patrimonio neto total.'},{q:'Es costoso?',a:'No, $1 millon de cobertura cuesta tipicamente $150-$400 al ano.'},{q:'Lo necesito?',a:'Si tienes una casa o activos significativos, es altamente recomendado.'}]),
  fr: mkSeo('Calculateur Assurance Parapluie', ['L\'assurance parapluie fournit une couche supplementaire de protection responsabilite civile.', 'Ce calculateur estime la couverture recommandee selon votre patrimoine, revenus et proprietes.', 'Les polices parapluie sont etonnamment abordables, coutant typiquement 150-400€ par an pour 1 million de couverture.', 'Consultez notre <a href="/${lang}/tools/home-insurance-calculator">calculateur assurance habitation</a>.'], [{q:'Que couvre l\'assurance parapluie?',a:'Elle couvre les reclamations depassant les limites de vos polices auto ou habitation.'},{q:'Combien de couverture ai-je besoin?',a:'Au minimum, egale a votre patrimoine net total.'},{q:'Est-ce cher?',a:'Non, 1 million de couverture coute typiquement 150-400€ par an.'},{q:'En ai-je besoin?',a:'Si vous possedez un logement ou avez des actifs significatifs, c\'est hautement recommande.'}]),
  de: mkSeo('Dachversicherungsrechner', ['Die Dachversicherung bietet eine zusaetzliche Haftpflichtschutzschicht ueber Ihre bestehenden Policen hinaus.', 'Dieser Rechner schaetzt die empfohlene Deckung basierend auf Vermoegen, Einkommen und Immobilien.', 'Dachpolicen sind ueberraschend guenstig, typisch 150-400€ pro Jahr fuer 1 Million Deckung.', 'Nutzen Sie unseren <a href="/${lang}/tools/home-insurance-calculator">Hausversicherungsrechner</a>.'], [{q:'Was deckt die Dachversicherung ab?',a:'Sie deckt Ansprueche ab, die die Limits Ihrer Auto- oder Hausversicherung uebersteigen.'},{q:'Wie viel Deckung brauche ich?',a:'Mindestens gleich Ihrem Gesamtnettovermoegen.'},{q:'Ist sie teuer?',a:'Nein, 1 Million Deckung kostet typisch 150-400€ pro Jahr.'},{q:'Brauche ich sie?',a:'Wenn Sie ein Haus besitzen oder bedeutende Vermoegenswerte haben, ist sie sehr empfehlenswert.'}]),
  pt: mkSeo('Calculadora Seguro Guarda-chuva', ['O seguro guarda-chuva fornece uma camada extra de protecao de responsabilidade civil.', 'Esta calculadora estima a cobertura recomendada com base em patrimonio, renda e propriedades.', 'As apolices guarda-chuva sao surpreendentemente acessiveis, custando tipicamente R$150-400 por ano para R$1 milhao.', 'Consulte nossa <a href="/${lang}/tools/home-insurance-calculator">calculadora de seguro residencial</a>.'], [{q:'O que cobre o seguro guarda-chuva?',a:'Cobre reclamacoes que excedem os limites das apolices de auto ou residencial.'},{q:'Quanta cobertura preciso?',a:'No minimo, igual ao seu patrimonio liquido total.'},{q:'E caro?',a:'Nao, R$1 milhao de cobertura custa tipicamente R$150-400 por ano.'},{q:'Preciso dele?',a:'Se voce possui uma casa ou tem ativos significativos, e altamente recomendado.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="umbrella-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
