'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'annualRevenue', labels: { en: 'Annual Revenue ($)', it: 'Fatturato annuale (€)', es: 'Ingresos anuales ($)', fr: 'Chiffre d\'affaires (€)', de: 'Jahresumsatz (€)', pt: 'Receita anual (R$)' }, defaultValue: '500000' },
  { key: 'employees', labels: { en: 'Number of Employees', it: 'Numero dipendenti', es: 'Numero de empleados', fr: 'Nombre d\'employes', de: 'Anzahl Mitarbeiter', pt: 'Numero de funcionarios' }, defaultValue: '10', min: 1, max: 500 },
  { key: 'industryRisk', labels: { en: 'Industry Risk (1-10)', it: 'Rischio settore (1-10)', es: 'Riesgo industria (1-10)', fr: 'Risque secteur (1-10)', de: 'Branchenrisiko (1-10)', pt: 'Risco setor (1-10)' }, defaultValue: '5', min: 1, max: 10 },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '1000' },
];
const results = [
  { key: 'glPremium', labels: { en: 'General Liability Premium', it: 'Premio RC Generale', es: 'Prima Responsabilidad Civil', fr: 'Prime RC Generale', de: 'Allgemeine Haftpflicht', pt: 'Premio RC Geral' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'propertyPremium', labels: { en: 'Property Insurance', it: 'Assicurazione proprieta', es: 'Seguro de propiedad', fr: 'Assurance propriete', de: 'Sachversicherung', pt: 'Seguro propriedade' }, color: 'green' as const, format: 'currency' as const },
  { key: 'wcPremium', labels: { en: 'Workers Comp Est.', it: 'Infortuni lavoro est.', es: 'Comp. trabajadores est.', fr: 'Accidents travail est.', de: 'Arbeiterunfallvers.', pt: 'Comp. trabalhadores est.' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'totalAnnual', labels: { en: 'Total Annual Cost', it: 'Costo annuale totale', es: 'Costo anual total', fr: 'Cout annuel total', de: 'Jaehrliche Gesamtkosten', pt: 'Custo anual total' }, color: 'red' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const rev = v.annualRevenue || 500000; const emp = v.employees || 10; const risk = v.industryRisk || 5; const ded = v.deductible || 1000;
  const riskMult = 0.5 + risk * 0.1; const dedDiscount = (ded - 500) * 0.1;
  const gl = Math.max(500, rev * 0.002 * riskMult - dedDiscount);
  const prop = Math.max(300, rev * 0.001 * riskMult);
  const wc = Math.max(200, emp * 500 * riskMult);
  return { glPremium: Math.round(gl), propertyPremium: Math.round(prop), wcPremium: Math.round(wc), totalAnnual: Math.round(gl + prop + wc) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Business Insurance Calculator: Estimate Commercial Coverage', ['Business insurance is essential for protecting your company from financial losses due to lawsuits, property damage, and employee injuries. The right coverage can mean the difference between surviving a crisis and closing your doors.', 'This calculator estimates premiums for general liability, property insurance, and workers compensation based on your revenue, employee count, industry risk level, and chosen deductible.', 'General liability typically costs $400-$2,000/year for small businesses. Workers compensation varies significantly by industry, from $0.75 to $2.50+ per $100 of payroll.', 'For related tools, see our <a href="/${lang}/tools/umbrella-insurance-calculator">umbrella insurance calculator</a> and <a href="/${lang}/tools/roi-calculator">ROI calculator</a>.'], [{q:'What types of business insurance do I need?',a:'Most businesses need general liability, property insurance, and workers compensation. Depending on your industry, you may also need professional liability (E&O), cyber liability, or commercial auto insurance.'},{q:'How much does business insurance cost?',a:'Small businesses typically pay $500-$3,000/year for basic coverage. Costs vary widely based on industry, revenue, number of employees, and location.'},{q:'Is business insurance legally required?',a:'Workers compensation is required in most states if you have employees. General liability is not legally required but is often needed for contracts and leases.'},{q:'What is a BOP (Business Owner Policy)?',a:'A BOP bundles general liability and property insurance at a discount, typically saving 15-20% compared to purchasing separately.'}]),
  it: mkSeo('Calcolatore Assicurazione Aziendale', ['L\'assicurazione aziendale e essenziale per proteggere la tua azienda da perdite finanziarie.', 'Questo calcolatore stima i premi per responsabilita civile, assicurazione proprieta e infortuni sul lavoro.', 'La responsabilita civile costa tipicamente 400-2.000€/anno per le piccole imprese.', 'Consulta il nostro <a href="/${lang}/tools/umbrella-insurance-calculator">calcolatore assicurazione ombrello</a>.'], [{q:'Quali assicurazioni servono alla mia azienda?',a:'RC generale, assicurazione proprieta e infortuni sul lavoro sono le piu comuni.'},{q:'Quanto costa?',a:'Le piccole imprese pagano tipicamente 500-3.000€/anno per la copertura base.'},{q:'E obbligatoria?',a:'L\'assicurazione infortuni e obbligatoria se hai dipendenti.'},{q:'Cos\'e una polizza BOP?',a:'Una polizza che combina RC generale e assicurazione proprieta con uno sconto del 15-20%.'}]),
  es: mkSeo('Calculadora Seguro Empresarial', ['El seguro empresarial es esencial para proteger tu empresa de perdidas financieras.', 'Esta calculadora estima primas para responsabilidad civil, seguro de propiedad y compensacion laboral.', 'La responsabilidad civil cuesta tipicamente $400-$2,000/ano para pequenas empresas.', 'Consulta nuestra <a href="/${lang}/tools/umbrella-insurance-calculator">calculadora de seguro paraguas</a>.'], [{q:'Que tipos de seguro empresarial necesito?',a:'RC general, seguro de propiedad y compensacion laboral son los mas comunes.'},{q:'Cuanto cuesta?',a:'Las pequenas empresas pagan tipicamente $500-$3,000/ano por cobertura basica.'},{q:'Es legalmente obligatorio?',a:'La compensacion laboral es obligatoria si tienes empleados.'},{q:'Que es una poliza BOP?',a:'Una poliza que combina RC general y seguro de propiedad con un descuento del 15-20%.'}]),
  fr: mkSeo('Calculateur Assurance Entreprise', ['L\'assurance entreprise est essentielle pour proteger votre societe des pertes financieres.', 'Ce calculateur estime les primes pour RC generale, assurance propriete et accidents du travail.', 'La RC generale coute typiquement 400-2 000€/an pour les petites entreprises.', 'Consultez notre <a href="/${lang}/tools/umbrella-insurance-calculator">calculateur assurance parapluie</a>.'], [{q:'Quels types d\'assurance entreprise me faut-il?',a:'RC generale, assurance propriete et accidents du travail sont les plus courants.'},{q:'Combien ca coute?',a:'Les petites entreprises paient typiquement 500-3 000€/an pour la couverture de base.'},{q:'Est-ce legalement obligatoire?',a:'L\'assurance accidents du travail est obligatoire si vous avez des employes.'},{q:'Qu\'est-ce qu\'une police BOP?',a:'Une police combinant RC generale et assurance propriete avec une remise de 15-20%.'}]),
  de: mkSeo('Gewerbeversicherungsrechner', ['Die Gewerbeversicherung ist essentiell zum Schutz Ihres Unternehmens vor finanziellen Verlusten.', 'Dieser Rechner schaetzt Praemien fuer allgemeine Haftpflicht, Sachversicherung und Arbeitsunfallversicherung.', 'Die allgemeine Haftpflicht kostet typisch 400-2.000€/Jahr fuer kleine Unternehmen.', 'Nutzen Sie unseren <a href="/${lang}/tools/umbrella-insurance-calculator">Dachversicherungsrechner</a>.'], [{q:'Welche Gewerbeversicherungen brauche ich?',a:'Allgemeine Haftpflicht, Sachversicherung und Arbeitsunfallversicherung sind am haeufigsten.'},{q:'Was kostet es?',a:'Kleine Unternehmen zahlen typisch 500-3.000€/Jahr fuer Grunddeckung.'},{q:'Ist sie gesetzlich vorgeschrieben?',a:'Die Arbeitsunfallversicherung ist Pflicht wenn Sie Mitarbeiter haben.'},{q:'Was ist eine BOP-Police?',a:'Eine Buendelpolice aus Haftpflicht und Sachversicherung mit 15-20% Rabatt.'}]),
  pt: mkSeo('Calculadora Seguro Empresarial', ['O seguro empresarial e essencial para proteger sua empresa de perdas financeiras.', 'Esta calculadora estima premios para RC geral, seguro de propriedade e compensacao trabalhista.', 'A RC geral custa tipicamente R$400-2.000/ano para pequenas empresas.', 'Consulte nossa <a href="/${lang}/tools/umbrella-insurance-calculator">calculadora de seguro guarda-chuva</a>.'], [{q:'Quais seguros empresariais preciso?',a:'RC geral, seguro de propriedade e compensacao trabalhista sao os mais comuns.'},{q:'Quanto custa?',a:'Pequenas empresas pagam tipicamente R$500-3.000/ano por cobertura basica.'},{q:'E legalmente obrigatorio?',a:'A compensacao trabalhista e obrigatoria se voce tem funcionarios.'},{q:'O que e uma apolice BOP?',a:'Uma apolice que combina RC geral e seguro de propriedade com desconto de 15-20%.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="business-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
