'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'currentHeatingCost', labels: { en: 'Current Annual Heating ($)', it: 'Riscaldamento annuale attuale (€)', es: 'Calefaccion anual actual ($)', fr: 'Chauffage annuel actuel (€)', de: 'Aktuelle Heizkosten/Jahr (€)', pt: 'Aquecimento anual atual (R$)' }, defaultValue: '2000' },
  { key: 'heatPumpCost', labels: { en: 'Heat Pump Install Cost ($)', it: 'Costo installazione (€)', es: 'Costo instalacion ($)', fr: 'Cout installation (€)', de: 'Installationskosten (€)', pt: 'Custo instalacao (R$)' }, defaultValue: '8000' },
  { key: 'efficiencyGain', labels: { en: 'Efficiency Gain (%)', it: 'Guadagno efficienza (%)', es: 'Ganancia eficiencia (%)', fr: 'Gain efficacite (%)', de: 'Effizienzgewinn (%)', pt: 'Ganho eficiencia (%)' }, defaultValue: '50', min: 20, max: 70 },
  { key: 'incentive', labels: { en: 'Tax Incentive ($)', it: 'Incentivo fiscale (€)', es: 'Incentivo fiscal ($)', fr: 'Incitation fiscale (€)', de: 'Steueranreiz (€)', pt: 'Incentivo fiscal (R$)' }, defaultValue: '2000' },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackYears', labels: { en: 'Payback Period (years)', it: 'Ammortamento (anni)', es: 'Amortizacion (anos)', fr: 'Amortissement (annees)', de: 'Amortisation (Jahre)', pt: 'Amortizacao (anos)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'tenYearSavings', labels: { en: '10-Year Net Savings', it: 'Risparmio netto 10 anni', es: 'Ahorro neto 10 anos', fr: 'Economies nettes 10 ans', de: '10-Jahres-Nettoeinsparung', pt: 'Economia liquida 10 anos' }, color: 'green' as const, format: 'currency' as const },
  { key: 'newAnnualCost', labels: { en: 'New Annual Heating Cost', it: 'Nuovo costo riscaldamento', es: 'Nuevo costo calefaccion', fr: 'Nouveau cout chauffage', de: 'Neue jaehrliche Heizkosten', pt: 'Novo custo aquecimento' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const current = v.currentHeatingCost || 2000; const install = v.heatPumpCost || 8000;
  const eff = (v.efficiencyGain || 50) / 100; const incentive = v.incentive || 2000;
  const newCost = current * (1 - eff); const savings = current - newCost; const netCost = install - incentive;
  const payback = savings > 0 ? netCost / savings : 99;
  return { annualSavings: Math.round(savings), paybackYears: Math.round(payback * 10) / 10, tenYearSavings: Math.round(savings * 10 - netCost), newAnnualCost: Math.round(newCost) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Heat Pump Savings Calculator: Estimate Your Energy Savings', ['Heat pumps are one of the most efficient ways to heat and cool your home, typically using 50% less energy than traditional systems. This calculator helps you estimate annual savings and payback period.', 'Modern heat pumps achieve 300-400% efficiency (COP 3-4), meaning they produce 3-4 units of heat for every unit of electricity consumed. This makes them far more efficient than gas furnaces (80-98% efficiency).', 'The Inflation Reduction Act offers up to $8,000 in heat pump tax credits, making the switch more affordable than ever. Many states offer additional incentives and rebates.', 'For related tools, see our <a href="/${lang}/tools/home-energy-audit-calculator">home energy audit calculator</a> and <a href="/${lang}/tools/insulation-roi-calculator">insulation ROI calculator</a>.'], [{q:'How much can a heat pump save?',a:'Most homeowners save 30-50% on heating costs, or $500-$1,500 per year depending on current fuel type and climate.'},{q:'Do heat pumps work in cold climates?',a:'Modern cold-climate heat pumps work efficiently down to -15°F (-26°C). They are now viable in most US and European climates.'},{q:'How long does a heat pump last?',a:'A properly maintained heat pump lasts 15-20 years, similar to a traditional HVAC system.'},{q:'What incentives are available?',a:'The US federal ITC offers up to $8,000. Many states, utilities, and EU countries offer additional rebates of $500-$5,000.'}]),
  it: mkSeo('Calcolatore Risparmio Pompa di Calore', ['Le pompe di calore sono tra i modi piu efficienti per riscaldare e raffreddare la casa.', 'Le pompe moderne raggiungono un\'efficienza del 300-400%, producendo 3-4 unita di calore per ogni unita di elettricita.', 'Molti governi offrono incentivi fino a 8.000€ per l\'installazione.', 'Consulta il <a href="/${lang}/tools/home-energy-audit-calculator">calcolatore audit energetico</a>.'], [{q:'Quanto posso risparmiare?',a:'La maggior parte risparmia il 30-50% sui costi di riscaldamento.'},{q:'Funzionano con il freddo?',a:'Le pompe moderne funzionano fino a -26°C.'},{q:'Quanto durano?',a:'15-20 anni con manutenzione adeguata.'},{q:'Quali incentivi ci sono?',a:'Molti paesi offrono crediti d\'imposta e detrazioni fino a 8.000€.'}]),
  es: mkSeo('Calculadora Ahorro Bomba de Calor', ['Las bombas de calor son una de las formas mas eficientes de climatizar tu hogar.', 'Las bombas modernas alcanzan 300-400% de eficiencia.', 'Muchos gobiernos ofrecen incentivos de hasta $8,000.', 'Consulta la <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Cuanto puedo ahorrar?',a:'La mayoria ahorra 30-50% en costos de calefaccion.'},{q:'Funcionan con frio?',a:'Las bombas modernas funcionan hasta -26°C.'},{q:'Cuanto duran?',a:'15-20 anos con mantenimiento adecuado.'},{q:'Que incentivos hay?',a:'Muchos paises ofrecen creditos fiscales hasta $8,000.'}]),
  fr: mkSeo('Calculateur Economies Pompe a Chaleur', ['Les pompes a chaleur sont parmi les moyens les plus efficaces de chauffer et refroidir votre maison.', 'Les pompes modernes atteignent 300-400% d\'efficacite.', 'De nombreux gouvernements offrent des incitations jusqu\'a 8 000€.', 'Consultez le <a href="/${lang}/tools/home-energy-audit-calculator">calculateur audit energetique</a>.'], [{q:'Combien puis-je economiser?',a:'La plupart economisent 30-50% sur les couts de chauffage.'},{q:'Fonctionnent-elles par grand froid?',a:'Les pompes modernes fonctionnent jusqu\'a -26°C.'},{q:'Combien de temps durent-elles?',a:'15-20 ans avec un entretien adequat.'},{q:'Quelles incitations existent?',a:'De nombreux pays offrent des credits d\'impot jusqu\'a 8 000€.'}]),
  de: mkSeo('Waermepumpen-Ersparnis-Rechner', ['Waermepumpen gehoeren zu den effizientesten Methoden zum Heizen und Kuehlen.', 'Moderne Waermepumpen erreichen 300-400% Effizienz.', 'Viele Regierungen bieten Anreize bis zu 8.000€.', 'Nutzen Sie den <a href="/${lang}/tools/home-energy-audit-calculator">Energieaudit-Rechner</a>.'], [{q:'Wie viel kann ich sparen?',a:'Die meisten sparen 30-50% bei den Heizkosten.'},{q:'Funktionieren sie bei Kaelte?',a:'Moderne Waermepumpen funktionieren bis -26°C.'},{q:'Wie lange halten sie?',a:'15-20 Jahre bei angemessener Wartung.'},{q:'Welche Anreize gibt es?',a:'Viele Laender bieten Steuergutschriften bis 8.000€.'}]),
  pt: mkSeo('Calculadora Economia Bomba de Calor', ['As bombas de calor sao uma das formas mais eficientes de climatizar sua casa.', 'As bombas modernas alcancam 300-400% de eficiencia.', 'Muitos governos oferecem incentivos ate R$8.000.', 'Consulte a <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Quanto posso economizar?',a:'A maioria economiza 30-50% nos custos de aquecimento.'},{q:'Funcionam no frio?',a:'As bombas modernas funcionam ate -26°C.'},{q:'Quanto duram?',a:'15-20 anos com manutencao adequada.'},{q:'Que incentivos existem?',a:'Muitos paises oferecem creditos fiscais ate R$8.000.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="heat-pump-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
