'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'annualIncome', labels: { en: 'Annual Income ($)', it: 'Reddito annuale (€)', es: 'Ingreso anual ($)', fr: 'Revenu annuel (€)', de: 'Jahreseinkommen (€)', pt: 'Renda anual (R$)' }, defaultValue: '60000' },
  { key: 'age', labels: { en: 'Your Age', it: 'Eta', es: 'Edad', fr: 'Age', de: 'Alter', pt: 'Idade' }, defaultValue: '35', min: 18, max: 65 },
  { key: 'existingCoverage', labels: { en: 'Existing Coverage ($/mo)', it: 'Copertura esistente (€/mese)', es: 'Cobertura existente ($/mes)', fr: 'Couverture existante (€/mois)', de: 'Bestehende Deckung (€/Mo)', pt: 'Cobertura existente (R$/mes)' }, defaultValue: '0' },
];
const results = [
  { key: 'monthlyBenefit', labels: { en: 'Recommended Monthly Benefit', it: 'Beneficio mensile raccomandato', es: 'Beneficio mensual recomendado', fr: 'Prestation mensuelle recommandee', de: 'Empfohlene Monatsleistung', pt: 'Beneficio mensal recomendado' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Est. Monthly Premium', it: 'Premio mensile stimato', es: 'Prima mensual est.', fr: 'Prime mensuelle est.', de: 'Geschaetzte Monatspraemie', pt: 'Premio mensal est.' }, color: 'green' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'totalPayout', labels: { en: 'Total Benefit (5yr)', it: 'Beneficio totale (5 anni)', es: 'Beneficio total (5 anos)', fr: 'Prestation totale (5 ans)', de: 'Gesamtleistung (5 J.)', pt: 'Beneficio total (5 anos)' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const monthlyBenefit = Math.round((v.annualIncome || 60000) * 0.6 / 12);
  const ageFactor = 1 + ((v.age || 35) - 30) * 0.025;
  const premium = Math.max(20, monthlyBenefit * 0.025 * ageFactor);
  const netBenefit = Math.max(0, monthlyBenefit - (v.existingCoverage || 0));
  return { monthlyBenefit: netBenefit, monthlyPremium: Math.round(premium), annualPremium: Math.round(premium * 12), totalPayout: Math.round(monthlyBenefit * 60) };
}
const s = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: s('Disability Insurance Calculator: Protect Your Income', ['Disability insurance replaces a portion of your income if you become unable to work due to illness or injury. Most financial advisors recommend coverage that replaces 60-70% of your pre-tax income, as disability benefits are typically tax-free when you pay the premiums yourself.', 'This calculator estimates your recommended monthly benefit (60% of gross income) and approximate premium based on your age. Younger applicants pay less because they are statistically less likely to file a claim. Premiums also vary by occupation — office workers pay less than construction workers.', 'Long-term disability insurance is one of the most overlooked protections. Statistics show that 1 in 4 workers will experience a disability lasting 90+ days before retirement. Without coverage, a serious illness or injury could devastate your finances, even if you have health insurance.', 'For comprehensive financial protection, also check our <a href="/${lang}/tools/life-insurance-calculator">life insurance calculator</a> and <a href="/${lang}/tools/emergency-fund-calculator">emergency fund calculator</a>.'], [{ q: 'How much disability insurance do I need?', a: 'Most policies cover 60-70% of your pre-tax income. Since benefits are usually tax-free (if you pay premiums yourself), this typically replaces about 80-90% of your take-home pay.' }, { q: 'What is the difference between short-term and long-term disability?', a: 'Short-term disability covers 3-6 months after a waiting period of 1-14 days. Long-term disability kicks in after 90-180 days and can last until retirement age. Both are important for complete coverage.' }, { q: 'Does employer disability insurance provide enough coverage?', a: 'Employer-provided coverage typically replaces only 40-60% of base salary and may not cover bonuses or commissions. Benefits are also taxable if the employer pays the premiums. Consider supplemental individual coverage.' }, { q: 'What conditions qualify for disability benefits?', a: 'Common qualifying conditions include back injuries, cancer, heart disease, mental health disorders, and musculoskeletal problems. The definition of disability varies by policy — own occupation vs. any occupation policies differ significantly.' }]),
  it: s('Calcolatore Assicurazione Invalidita: Proteggi il Tuo Reddito', ['L\'assicurazione invalidita sostituisce una parte del reddito se non puoi lavorare per malattia o infortunio. La maggior parte dei consulenti raccomanda una copertura del 60-70% del reddito lordo.', 'Questo calcolatore stima il beneficio mensile raccomandato e il premio approssimativo in base all\'eta.', 'L\'assicurazione invalidita a lungo termine e una delle protezioni piu trascurate. Le statistiche mostrano che 1 lavoratore su 4 subira un\'invalidita di oltre 90 giorni prima della pensione.', 'Per una protezione completa, consulta anche il nostro <a href="/${lang}/tools/life-insurance-calculator">calcolatore assicurazione vita</a>.'], [{ q: 'Quanta assicurazione invalidita mi serve?', a: 'La maggior parte delle polizze copre il 60-70% del reddito lordo.' }, { q: 'Qual e la differenza tra invalidita a breve e lungo termine?', a: 'A breve termine copre 3-6 mesi, a lungo termine inizia dopo 90-180 giorni e puo durare fino alla pensione.' }, { q: 'La copertura del datore di lavoro e sufficiente?', a: 'Tipicamente copre solo il 40-60% dello stipendio base. Considera una copertura individuale supplementare.' }, { q: 'Quali condizioni danno diritto ai benefici?', a: 'Infortuni alla schiena, cancro, malattie cardiache, disturbi mentali e problemi muscoloscheletrici sono comuni.' }]),
  es: s('Calculadora Seguro de Incapacidad: Protege Tus Ingresos', ['El seguro de incapacidad reemplaza una porcion de tus ingresos si no puedes trabajar. Se recomienda cobertura del 60-70% del ingreso bruto.', 'Esta calculadora estima tu beneficio mensual recomendado y prima aproximada segun tu edad.', 'El seguro de incapacidad a largo plazo es una de las protecciones mas olvidadas.', 'Consulta tambien nuestra <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{ q: 'Cuanto seguro de incapacidad necesito?', a: 'La mayoria de polizas cubren el 60-70% del ingreso bruto.' }, { q: 'Cual es la diferencia entre incapacidad a corto y largo plazo?', a: 'A corto plazo cubre 3-6 meses, a largo plazo comienza despues de 90-180 dias.' }, { q: 'La cobertura del empleador es suficiente?', a: 'Tipicamente cubre solo el 40-60% del salario base.' }, { q: 'Que condiciones califican?', a: 'Lesiones de espalda, cancer, enfermedades cardiacas y trastornos mentales son comunes.' }]),
  fr: s('Calculateur Assurance Invalidite: Protegez Vos Revenus', ['L\'assurance invalidite remplace une partie de vos revenus si vous ne pouvez plus travailler. La couverture recommandee est de 60-70% du revenu brut.', 'Ce calculateur estime votre prestation mensuelle recommandee et la prime approximative selon votre age.', 'L\'assurance invalidite a long terme est l\'une des protections les plus negligees.', 'Consultez aussi notre <a href="/${lang}/tools/life-insurance-calculator">calculateur assurance vie</a>.'], [{ q: 'Combien d\'assurance invalidite ai-je besoin?', a: 'La plupart des polices couvrent 60-70% du revenu brut.' }, { q: 'Quelle est la difference entre invalidite a court et long terme?', a: 'A court terme couvre 3-6 mois, a long terme commence apres 90-180 jours.' }, { q: 'La couverture de l\'employeur suffit-elle?', a: 'Elle couvre typiquement seulement 40-60% du salaire de base.' }, { q: 'Quelles conditions sont couvertes?', a: 'Blessures dorsales, cancer, maladies cardiaques et troubles mentaux sont courants.' }]),
  de: s('BU-Versicherungsrechner: Schuetzen Sie Ihr Einkommen', ['Die Berufsunfaehigkeitsversicherung ersetzt einen Teil Ihres Einkommens bei Arbeitsunfaehigkeit. Empfohlen wird eine Deckung von 60-70% des Bruttoeinkommens.', 'Dieser Rechner schaetzt Ihre empfohlene monatliche Leistung und die ungefaehre Praemie basierend auf dem Alter.', 'Die BU-Versicherung ist eine der am meisten vernachlaessigten Absicherungen.', 'Nutzen Sie auch unseren <a href="/${lang}/tools/life-insurance-calculator">Lebensversicherungsrechner</a>.'], [{ q: 'Wie viel BU-Versicherung brauche ich?', a: 'Die meisten Policen decken 60-70% des Bruttoeinkommens ab.' }, { q: 'Was ist der Unterschied zwischen kurz- und langfristiger BU?', a: 'Kurzfristige BU deckt 3-6 Monate, langfristige beginnt nach 90-180 Tagen.' }, { q: 'Reicht die Absicherung des Arbeitgebers?', a: 'Sie deckt typisch nur 40-60% des Grundgehalts.' }, { q: 'Welche Erkrankungen sind abgedeckt?', a: 'Rueckenverletzungen, Krebs, Herzerkrankungen und psychische Stoerungen sind haeufig.' }]),
  pt: s('Calculadora Seguro Invalidez: Proteja Sua Renda', ['O seguro invalidez substitui parte da sua renda se voce nao puder trabalhar. Recomenda-se cobertura de 60-70% da renda bruta.', 'Esta calculadora estima seu beneficio mensal recomendado e premio aproximado com base na idade.', 'O seguro de invalidez de longo prazo e uma das protecoes mais negligenciadas.', 'Consulte tambem nossa <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{ q: 'Quanto seguro invalidez eu preciso?', a: 'A maioria das apolices cobre 60-70% da renda bruta.' }, { q: 'Qual a diferenca entre invalidez de curto e longo prazo?', a: 'Curto prazo cobre 3-6 meses, longo prazo comeca apos 90-180 dias.' }, { q: 'A cobertura do empregador e suficiente?', a: 'Tipicamente cobre apenas 40-60% do salario base.' }, { q: 'Quais condicoes sao cobertas?', a: 'Lesoes nas costas, cancer, doencas cardiacas e transtornos mentais sao comuns.' }]),
};
export default function DisabilityInsuranceCalculator() {
  return <InsuranceCalculatorPage toolSlug="disability-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />;
}
