'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'currentAge', labels: { en: 'Current Age', it: 'Eta attuale', es: 'Edad actual', fr: 'Age actuel', de: 'Aktuelles Alter', pt: 'Idade atual' }, defaultValue: '55', min: 30, max: 80 },
  { key: 'dailyBenefit', labels: { en: 'Daily Benefit ($)', it: 'Beneficio giornaliero (€)', es: 'Beneficio diario ($)', fr: 'Prestation quotidienne (€)', de: 'Tagesleistung (€)', pt: 'Beneficio diario (R$)' }, defaultValue: '200', min: 50, max: 500 },
  { key: 'benefitPeriod', labels: { en: 'Benefit Period (years)', it: 'Periodo beneficio (anni)', es: 'Periodo beneficio (anos)', fr: 'Periode prestation (annees)', de: 'Leistungszeitraum (Jahre)', pt: 'Periodo beneficio (anos)' }, defaultValue: '3', min: 1, max: 10 },
  { key: 'inflationProtection', labels: { en: 'Inflation Protection (0=no,1=yes)', it: 'Protezione inflazione (0=no,1=si)', es: 'Proteccion inflacion (0=no,1=si)', fr: 'Protection inflation (0=non,1=oui)', de: 'Inflationsschutz (0=nein,1=ja)', pt: 'Protecao inflacao (0=nao,1=sim)' }, defaultValue: '1', min: 0, max: 1 },
];
const results = [
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'green' as const, format: 'currency' as const },
  { key: 'totalBenefitPool', labels: { en: 'Total Benefit Pool', it: 'Pool benefici totale', es: 'Pool beneficios total', fr: 'Pool prestations total', de: 'Gesamtleistungspool', pt: 'Pool beneficios total' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'monthlyBenefit', labels: { en: 'Monthly Benefit', it: 'Beneficio mensile', es: 'Beneficio mensual', fr: 'Prestation mensuelle', de: 'Monatsleistung', pt: 'Beneficio mensal' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const age = v.currentAge || 55; const daily = v.dailyBenefit || 200; const years = v.benefitPeriod || 3; const inflation = v.inflationProtection || 1;
  const ageFactor = age < 50 ? 0.6 : age < 60 ? 1.0 : age < 70 ? 1.8 : 3.0;
  const inflationMult = inflation ? 1.4 : 1.0; const pool = daily * 365 * years;
  const annual = daily * 12 * ageFactor * inflationMult;
  return { annualPremium: Math.round(annual), monthlyPremium: Math.round(annual / 12), totalBenefitPool: Math.round(pool), monthlyBenefit: Math.round(daily * 30) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Long-Term Care Insurance Calculator: Estimate Your Premium', ['Long-term care insurance covers the costs of nursing homes, assisted living, and in-home care when you can no longer perform daily activities independently. The average nursing home costs over $90,000 per year.', 'This calculator estimates premiums based on your age, desired daily benefit, benefit period, and inflation protection. Buying at a younger age significantly reduces premiums.', 'About 70% of people over 65 will need some form of long-term care. Medicare covers very limited long-term care, making private insurance essential for asset protection.', 'For related tools, see our <a href="/${lang}/tools/life-insurance-calculator">life insurance calculator</a> and <a href="/${lang}/tools/retirement-calculator">retirement calculator</a>.'], [{q:'When should I buy long-term care insurance?',a:'The ideal age is 50-60. Premiums increase 6-8% per year of age. After 70, it may be prohibitively expensive or unavailable.'},{q:'How much does a nursing home cost?',a:'The national average is $7,500-$9,000/month for a semi-private room, or $90,000-$108,000 per year.'},{q:'Does Medicare cover long-term care?',a:'Medicare covers only up to 100 days of skilled nursing care following a hospital stay. It does not cover custodial (non-medical) care.'},{q:'What is inflation protection?',a:'It increases your daily benefit 3-5% per year to keep pace with rising care costs. It adds 30-40% to premiums but is highly recommended.'}]),
  it: mkSeo('Calcolatore Assicurazione Lungodegenza', ['L\'assicurazione lungodegenza copre i costi di case di cura e assistenza domiciliare.', 'Questo calcolatore stima i premi in base a eta, beneficio giornaliero e periodo di copertura.', 'Circa il 70% delle persone over 65 avra bisogno di qualche forma di assistenza a lungo termine.', 'Consulta il <a href="/${lang}/tools/life-insurance-calculator">calcolatore assicurazione vita</a>.'], [{q:'Quando comprarla?',a:'L\'eta ideale e 50-60 anni. I premi aumentano del 6-8% per anno di eta.'},{q:'Quanto costa una casa di cura?',a:'La media e 7.500-9.000€/mese.'},{q:'Il sistema sanitario copre la lungodegenza?',a:'Solo cure limitate post-ospedaliere.'},{q:'Cos\'e la protezione dall\'inflazione?',a:'Aumenta il beneficio del 3-5% annuo per stare al passo con i costi crescenti.'}]),
  es: mkSeo('Calculadora Seguro de Cuidados a Largo Plazo', ['El seguro de cuidados a largo plazo cubre costos de hogares de ancianos y asistencia.', 'Esta calculadora estima primas segun edad, beneficio diario y periodo de cobertura.', 'Aproximadamente el 70% de las personas mayores de 65 necesitaran cuidados a largo plazo.', 'Consulta la <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{q:'Cuando comprarlo?',a:'La edad ideal es 50-60 anos.'},{q:'Cuanto cuesta un hogar de ancianos?',a:'Promedio de $7,500-$9,000/mes.'},{q:'Medicare lo cubre?',a:'Solo hasta 100 dias de cuidado especializado.'},{q:'Que es la proteccion contra inflacion?',a:'Aumenta el beneficio 3-5% anual.'}]),
  fr: mkSeo('Calculateur Assurance Dependance', ['L\'assurance dependance couvre les couts des maisons de retraite et de l\'aide a domicile.', 'Ce calculateur estime les primes selon l\'age, la prestation quotidienne et la periode.', 'Environ 70% des personnes de plus de 65 ans auront besoin de soins de longue duree.', 'Consultez le <a href="/${lang}/tools/life-insurance-calculator">calculateur assurance vie</a>.'], [{q:'Quand l\'acheter?',a:'L\'age ideal est 50-60 ans.'},{q:'Combien coute une maison de retraite?',a:'En moyenne 7 500-9 000€/mois.'},{q:'La Secu couvre-t-elle la dependance?',a:'Partiellement seulement.'},{q:'Qu\'est-ce que la protection inflation?',a:'Elle augmente la prestation de 3-5% par an.'}]),
  de: mkSeo('Pflegeversicherungsrechner', ['Die Pflegeversicherung deckt Kosten fuer Pflegeheime und haeusliche Pflege.', 'Dieser Rechner schaetzt Praemien basierend auf Alter, Tagesleistung und Leistungszeitraum.', 'Etwa 70% der ueber 65-Jaehrigen werden eine Form der Langzeitpflege benoetigen.', 'Nutzen Sie den <a href="/${lang}/tools/life-insurance-calculator">Lebensversicherungsrechner</a>.'], [{q:'Wann abschliessen?',a:'Das ideale Alter ist 50-60 Jahre.'},{q:'Was kostet ein Pflegeheim?',a:'Durchschnittlich 7.500-9.000€/Monat.'},{q:'Deckt die Krankenversicherung Pflege ab?',a:'Nur begrenzte Leistungen.'},{q:'Was ist Inflationsschutz?',a:'Erhoehung der Leistung um 3-5% jaehrlich.'}]),
  pt: mkSeo('Calculadora Seguro de Cuidados de Longo Prazo', ['O seguro de cuidados de longo prazo cobre custos de casas de repouso e assistencia.', 'Esta calculadora estima premios com base na idade, beneficio diario e periodo.', 'Cerca de 70% das pessoas acima de 65 anos precisarao de cuidados de longo prazo.', 'Consulte a <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{q:'Quando contratar?',a:'A idade ideal e 50-60 anos.'},{q:'Quanto custa uma casa de repouso?',a:'Em media R$7.500-9.000/mes.'},{q:'O SUS cobre cuidados de longo prazo?',a:'Apenas parcialmente.'},{q:'O que e protecao contra inflacao?',a:'Aumenta o beneficio em 3-5% ao ano.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="long-term-care-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
