'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'commuteDistance', labels: { en: 'Daily Commute (miles)', it: 'Tragitto giornaliero (km)', es: 'Trayecto diario (millas)', fr: 'Trajet quotidien (km)', de: 'Taeglicher Arbeitsweg (km)', pt: 'Trajeto diario (km)' }, defaultValue: '10' },
  { key: 'workDays', labels: { en: 'Work Days/Year', it: 'Giorni lavoro/anno', es: 'Dias trabajo/ano', fr: 'Jours travail/an', de: 'Arbeitstage/Jahr', pt: 'Dias trabalho/ano' }, defaultValue: '250' },
  { key: 'gasPrice', labels: { en: 'Gas Price ($/gal)', it: 'Prezzo benzina (€/L)', es: 'Precio gasolina ($/gal)', fr: 'Prix essence (€/L)', de: 'Benzinpreis (€/L)', pt: 'Preco gasolina (R$/L)' }, defaultValue: '3.50', step: 0.1 },
  { key: 'ebikeCost', labels: { en: 'E-Bike Cost ($)', it: 'Costo e-bike (€)', es: 'Costo e-bike ($)', fr: 'Cout velo electrique (€)', de: 'E-Bike Kosten (€)', pt: 'Custo e-bike (R$)' }, defaultValue: '1500' },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackMonths', labels: { en: 'Payback (months)', it: 'Ammortamento (mesi)', es: 'Amortizacion (meses)', fr: 'Amortissement (mois)', de: 'Amortisation (Monate)', pt: 'Amortizacao (meses)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'co2Saved', labels: { en: 'CO2 Saved (lbs/yr)', it: 'CO2 risparmiata (kg/anno)', es: 'CO2 ahorrado (lbs/ano)', fr: 'CO2 economise (kg/an)', de: 'CO2 gespart (kg/Jahr)', pt: 'CO2 economizado (kg/ano)' }, color: 'green' as const, format: 'number' as const },
  { key: 'chargingCost', labels: { en: 'Annual Charging Cost', it: 'Costo ricarica annuale', es: 'Costo carga anual', fr: 'Cout recharge annuel', de: 'Jaehrliche Ladekosten', pt: 'Custo recarga anual' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const dist = v.commuteDistance || 10; const days = v.workDays || 250; const gas = v.gasPrice || 3.5; const bikeCost = v.ebikeCost || 1500;
  const annualMiles = dist * 2 * days; const carCost = (annualMiles / 30) * gas + 500; // fuel + parking
  const chargeCost = annualMiles * 0.01; // ~$0.01/mile for e-bike
  const savings = carCost - chargeCost; const payback = savings > 0 ? (bikeCost / savings) * 12 : 999;
  const co2 = annualMiles * 0.89; // lbs CO2 per mile for avg car
  return { annualSavings: Math.round(savings), paybackMonths: Math.round(payback), co2Saved: Math.round(co2), chargingCost: Math.round(chargeCost) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Electric Bike Savings Calculator: Commute Cost Comparison', ['An electric bike can dramatically cut your commuting costs while improving your health and reducing your carbon footprint. E-bikes cost just $0.01 per mile to operate versus $0.12+ for a car.', 'This calculator estimates annual savings from commuting by e-bike instead of car, including fuel costs, parking, and maintenance savings. Most e-bike commuters save $1,000-$3,000 per year.', 'E-bikes have a typical payback period of 3-12 months depending on commute distance and gas prices. They also provide excellent exercise with pedal assist making hills and headwinds manageable.', 'For related tools, see our <a href="/${lang}/tools/ev-vs-gas-calculator">EV vs gas calculator</a> and <a href="/${lang}/tools/carbon-footprint-calculator">carbon footprint calculator</a>.'], [{q:'How much can I save commuting by e-bike?',a:'Most e-bike commuters save $1,000-$3,000/year in fuel, parking, and maintenance costs.'},{q:'How far can an e-bike go?',a:'Most e-bikes have 25-70 miles of range per charge, more than enough for typical commutes.'},{q:'How long does it take to charge?',a:'3-6 hours for a full charge from empty. Most commuters charge overnight.'},{q:'Are e-bikes safe for commuting?',a:'With proper gear (helmet, lights, reflective clothing) and dedicated bike lanes, e-bikes are a safe commuting option.'}]),
  it: mkSeo('Calcolatore Risparmio Bici Elettrica', ['Una bici elettrica puo tagliare drasticamente i costi di pendolarismo.', 'Questo calcolatore stima il risparmio annuale andando in e-bike invece che in auto.', 'Le e-bike hanno un ammortamento tipico di 3-12 mesi.', 'Consulta il <a href="/${lang}/tools/carbon-footprint-calculator">calcolatore impronta carbonica</a>.'], [{q:'Quanto posso risparmiare?',a:'La maggior parte risparmia 1.000-3.000€/anno.'},{q:'Quanta autonomia ha?',a:'25-70 km per ricarica, sufficiente per il pendolarismo tipico.'},{q:'Quanto tempo per ricaricare?',a:'3-6 ore per una ricarica completa.'},{q:'Sono sicure per il pendolarismo?',a:'Con equipaggiamento adeguato e piste ciclabili, si.'}]),
  es: mkSeo('Calculadora Ahorro Bicicleta Electrica', ['Una bicicleta electrica puede reducir drasticamente los costos de transporte.', 'Esta calculadora estima el ahorro anual al ir en e-bike en lugar de auto.', 'Las e-bikes tienen un periodo de amortizacion de 3-12 meses.', 'Consulta la <a href="/${lang}/tools/carbon-footprint-calculator">calculadora de huella de carbono</a>.'], [{q:'Cuanto puedo ahorrar?',a:'La mayoria ahorra $1,000-$3,000/ano.'},{q:'Cuanta autonomia tiene?',a:'25-70 millas por carga.'},{q:'Cuanto tarda en cargar?',a:'3-6 horas para carga completa.'},{q:'Son seguras para el transporte?',a:'Con equipo adecuado y ciclovias, si.'}]),
  fr: mkSeo('Calculateur Economies Velo Electrique', ['Un velo electrique peut reduire considerablement les couts de trajet.', 'Ce calculateur estime les economies annuelles en velo electrique au lieu de la voiture.', 'Les velos electriques ont un amortissement de 3-12 mois.', 'Consultez le <a href="/${lang}/tools/carbon-footprint-calculator">calculateur empreinte carbone</a>.'], [{q:'Combien puis-je economiser?',a:'La plupart economisent 1 000-3 000€/an.'},{q:'Quelle autonomie?',a:'25-70 km par charge.'},{q:'Combien de temps pour charger?',a:'3-6 heures pour une charge complete.'},{q:'Sont-ils surs pour les trajets?',a:'Avec l\'equipement adequat et les pistes cyclables, oui.'}]),
  de: mkSeo('E-Bike Ersparnis-Rechner', ['Ein E-Bike kann Ihre Pendelkosten drastisch senken.', 'Dieser Rechner schaetzt die jaehrliche Ersparnis beim Pendeln mit E-Bike statt Auto.', 'E-Bikes haben eine Amortisationszeit von 3-12 Monaten.', 'Nutzen Sie den <a href="/${lang}/tools/carbon-footprint-calculator">CO2-Fussabdruck-Rechner</a>.'], [{q:'Wie viel kann ich sparen?',a:'Die meisten sparen 1.000-3.000€/Jahr.'},{q:'Welche Reichweite?',a:'25-70 km pro Ladung.'},{q:'Wie lange dauert das Laden?',a:'3-6 Stunden fuer eine Vollladung.'},{q:'Sind sie sicher zum Pendeln?',a:'Mit der richtigen Ausruestung und Radwegen ja.'}]),
  pt: mkSeo('Calculadora Economia Bicicleta Eletrica', ['Uma bicicleta eletrica pode reduzir drasticamente os custos de transporte.', 'Esta calculadora estima a economia anual ao ir de e-bike em vez de carro.', 'As e-bikes tem um periodo de amortizacao de 3-12 meses.', 'Consulte a <a href="/${lang}/tools/carbon-footprint-calculator">calculadora de pegada de carbono</a>.'], [{q:'Quanto posso economizar?',a:'A maioria economiza R$1.000-3.000/ano.'},{q:'Qual a autonomia?',a:'25-70 km por carga.'},{q:'Quanto tempo para carregar?',a:'3-6 horas para carga completa.'},{q:'Sao seguras para o transporte?',a:'Com equipamento adequado e ciclovias, sim.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="electric-bike-savings-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
