'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'coverageAmount', labels: { en: 'Coverage Amount ($)', it: 'Importo copertura (€)', es: 'Monto cobertura ($)', fr: 'Montant couverture (€)', de: 'Deckungsbetrag (€)', pt: 'Valor cobertura (R$)' }, defaultValue: '50000' },
  { key: 'applicantAge', labels: { en: 'Applicant Age', it: 'Eta richiedente', es: 'Edad solicitante', fr: 'Age demandeur', de: 'Alter Antragsteller', pt: 'Idade solicitante' }, defaultValue: '45', min: 18, max: 70 },
  { key: 'smoker', labels: { en: 'Smoker (0=no,1=yes)', it: 'Fumatore (0=no,1=si)', es: 'Fumador (0=no,1=si)', fr: 'Fumeur (0=non,1=oui)', de: 'Raucher (0=nein,1=ja)', pt: 'Fumante (0=nao,1=sim)' }, defaultValue: '0', min: 0, max: 1 },
  { key: 'termLength', labels: { en: 'Term Length (years)', it: 'Durata termine (anni)', es: 'Duracion plazo (anos)', fr: 'Duree terme (annees)', de: 'Laufzeit (Jahre)', pt: 'Duracao prazo (anos)' }, defaultValue: '20', min: 5, max: 30 },
];
const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'lumpSumPayout', labels: { en: 'Lump Sum Payout', it: 'Pagamento forfettario', es: 'Pago unico', fr: 'Versement forfaitaire', de: 'Einmalzahlung', pt: 'Pagamento unico' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'totalPremiums', labels: { en: 'Total Premiums Paid', it: 'Totale premi pagati', es: 'Total primas pagadas', fr: 'Total primes payees', de: 'Gesamte Praemien', pt: 'Total premios pagos' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const coverage = v.coverageAmount || 50000; const age = v.applicantAge || 45; const smoker = v.smoker || 0; const term = v.termLength || 20;
  const ageFactor = age < 35 ? 0.5 : age < 45 ? 0.8 : age < 55 ? 1.2 : 2.0;
  const smokerMult = smoker ? 2.0 : 1.0; const monthly = (coverage / 1000) * 1.5 * ageFactor * smokerMult;
  return { monthlyPremium: Math.round(monthly), annualPremium: Math.round(monthly * 12), lumpSumPayout: Math.round(coverage), totalPremiums: Math.round(monthly * 12 * term) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Critical Illness Insurance Calculator: Estimate Your Premium', ['Critical illness insurance pays a lump sum if you are diagnosed with a covered condition such as cancer, heart attack, or stroke. This money can be used for any purpose including medical bills, living expenses, or debt.', 'This calculator estimates your premium based on coverage amount, age, smoking status, and term length. Younger, healthier applicants pay significantly less.', 'One in three people will be diagnosed with cancer in their lifetime. Heart disease is the leading cause of death globally. Critical illness insurance provides a financial safety net during recovery.', 'For related tools, see our <a href="/${lang}/tools/life-insurance-calculator">life insurance calculator</a> and <a href="/${lang}/tools/health-insurance-calculator">health insurance calculator</a>.'], [{q:'What conditions are covered?',a:'Most policies cover cancer, heart attack, stroke, organ transplant, coronary bypass, and kidney failure. Some also cover MS, blindness, and paralysis.'},{q:'How is it different from health insurance?',a:'Critical illness pays a lump sum directly to you regardless of actual medical costs. Health insurance pays providers for specific medical services.'},{q:'When should I buy it?',a:'The earlier the better. Premiums increase significantly with age, and pre-existing conditions may disqualify you.'},{q:'How much coverage do I need?',a:'Financial advisors recommend 3-5x your annual income or enough to cover 1-2 years of expenses while recovering.'}]),
  it: mkSeo('Calcolatore Assicurazione Malattie Gravi', ['L\'assicurazione malattie gravi paga una somma forfettaria se ti viene diagnosticata una condizione coperta.', 'Questo calcolatore stima il premio in base a copertura, eta, status fumatore e durata.', 'Una persona su tre sara diagnosticata con cancro. L\'assicurazione malattie gravi fornisce una rete di sicurezza.', 'Consulta il <a href="/${lang}/tools/life-insurance-calculator">calcolatore assicurazione vita</a>.'], [{q:'Quali condizioni sono coperte?',a:'Cancro, infarto, ictus, trapianto, bypass coronarico e insufficienza renale.'},{q:'Come e diversa dall\'assicurazione sanitaria?',a:'Paga una somma forfettaria a te direttamente, indipendentemente dai costi medici.'},{q:'Quando comprarla?',a:'Prima possibile. I premi aumentano significativamente con l\'eta.'},{q:'Quanta copertura mi serve?',a:'3-5 volte il tuo reddito annuale o 1-2 anni di spese.'}]),
  es: mkSeo('Calculadora Seguro Enfermedades Criticas', ['El seguro de enfermedades criticas paga una suma global si te diagnostican una condicion cubierta.', 'Esta calculadora estima tu prima segun cobertura, edad, estado de fumador y plazo.', 'Una de cada tres personas sera diagnosticada con cancer.', 'Consulta la <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{q:'Que condiciones cubre?',a:'Cancer, infarto, derrame, trasplante y bypass coronario.'},{q:'Como es diferente del seguro de salud?',a:'Paga una suma global directamente a ti.'},{q:'Cuando comprarlo?',a:'Lo antes posible.'},{q:'Cuanta cobertura necesito?',a:'3-5 veces tu ingreso anual.'}]),
  fr: mkSeo('Calculateur Assurance Maladies Graves', ['L\'assurance maladies graves verse un montant forfaitaire en cas de diagnostic d\'une condition couverte.', 'Ce calculateur estime votre prime selon la couverture, l\'age, le statut fumeur et la duree.', 'Une personne sur trois sera diagnostiquee avec un cancer.', 'Consultez le <a href="/${lang}/tools/life-insurance-calculator">calculateur assurance vie</a>.'], [{q:'Quelles conditions sont couvertes?',a:'Cancer, infarctus, AVC, transplantation et pontage coronarien.'},{q:'Comment est-ce different de l\'assurance sante?',a:'Elle verse un montant forfaitaire directement a vous.'},{q:'Quand l\'acheter?',a:'Le plus tot possible.'},{q:'Combien de couverture?',a:'3-5 fois votre revenu annuel.'}]),
  de: mkSeo('Schwere-Krankheiten-Versicherungsrechner', ['Die Schwere-Krankheiten-Versicherung zahlt eine Einmalsumme bei Diagnose einer gedeckten Erkrankung.', 'Dieser Rechner schaetzt Ihre Praemie basierend auf Deckung, Alter, Raucherstatus und Laufzeit.', 'Jeder Dritte wird mit Krebs diagnostiziert.', 'Nutzen Sie den <a href="/${lang}/tools/life-insurance-calculator">Lebensversicherungsrechner</a>.'], [{q:'Welche Erkrankungen sind gedeckt?',a:'Krebs, Herzinfarkt, Schlaganfall, Transplantation und Bypass.'},{q:'Wie unterscheidet sie sich von der Krankenversicherung?',a:'Sie zahlt eine Einmalsumme direkt an Sie.'},{q:'Wann abschliessen?',a:'So frueh wie moeglich.'},{q:'Wie viel Deckung?',a:'3-5 Mal Ihr Jahreseinkommen.'}]),
  pt: mkSeo('Calculadora Seguro Doencas Graves', ['O seguro de doencas graves paga um valor unico se voce for diagnosticado com uma condicao coberta.', 'Esta calculadora estima seu premio com base na cobertura, idade, status de fumante e prazo.', 'Uma em cada tres pessoas sera diagnosticada com cancer.', 'Consulte a <a href="/${lang}/tools/life-insurance-calculator">calculadora de seguro de vida</a>.'], [{q:'Que condicoes sao cobertas?',a:'Cancer, infarto, AVC, transplante e bypass coronario.'},{q:'Como e diferente do seguro saude?',a:'Paga um valor unico diretamente a voce.'},{q:'Quando contratar?',a:'O mais cedo possivel.'},{q:'Quanta cobertura preciso?',a:'3-5 vezes sua renda anual.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="critical-illness-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
