'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'familySize', labels: { en: 'Family Size', it: 'Dimensione famiglia', es: 'Tamano familia', fr: 'Taille famille', de: 'Familiengroesse', pt: 'Tamanho familia' }, defaultValue: '2', min: 1, max: 8 },
  { key: 'needsGlasses', labels: { en: 'Needs Glasses (0=no,1=yes)', it: 'Serve occhiali (0=no,1=si)', es: 'Necesita lentes (0=no,1=si)', fr: 'Besoin lunettes (0=non,1=oui)', de: 'Braucht Brille (0=nein,1=ja)', pt: 'Precisa oculos (0=nao,1=sim)' }, defaultValue: '1', min: 0, max: 1 },
  { key: 'needsContacts', labels: { en: 'Needs Contacts (0=no,1=yes)', it: 'Serve lenti (0=no,1=si)', es: 'Necesita contactos (0=no,1=si)', fr: 'Besoin lentilles (0=non,1=oui)', de: 'Braucht Kontaktlinsen (0=nein,1=ja)', pt: 'Precisa lentes (0=nao,1=sim)' }, defaultValue: '0', min: 0, max: 1 },
  { key: 'planTier', labels: { en: 'Plan Tier (1=basic,3=premium)', it: 'Livello piano (1=base,3=premium)', es: 'Nivel plan (1=basico,3=premium)', fr: 'Niveau plan (1=base,3=premium)', de: 'Planstufe (1=basis,3=premium)', pt: 'Nivel plano (1=basico,3=premium)' }, defaultValue: '2', min: 1, max: 3 },
];
const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'estimatedSavings', labels: { en: 'Est. Annual Savings', it: 'Risparmio annuale est.', es: 'Ahorro anual est.', fr: 'Economies annuelles est.', de: 'Geschaetzte Ersparnis', pt: 'Economia anual est.' }, color: 'green' as const, format: 'currency' as const },
  { key: 'frameAllowance', labels: { en: 'Frame Allowance', it: 'Budget montatura', es: 'Presupuesto armazon', fr: 'Budget monture', de: 'Gestellbudget', pt: 'Orcamento armacao' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const fam = v.familySize || 2; const glasses = v.needsGlasses || 1; const contacts = v.needsContacts || 0; const tier = v.planTier || 2;
  const baseMonthly = [8, 15, 25][Math.min(2, Math.max(0, tier - 1))]; const monthly = baseMonthly * fam;
  const annual = monthly * 12; const examCost = 200 * fam; const glassesCost = glasses ? 300 * fam : 0; const contactsCost = contacts ? 250 * fam : 0;
  const totalCost = examCost + glassesCost + contactsCost; const coverage = tier === 1 ? 0.5 : tier === 2 ? 0.65 : 0.8;
  const savings = totalCost * coverage - annual; const frame = [130, 200, 300][Math.min(2, Math.max(0, tier - 1))];
  return { monthlyPremium: Math.round(monthly), annualPremium: Math.round(annual), estimatedSavings: Math.round(Math.max(0, savings)), frameAllowance: frame };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Vision Insurance Calculator: Estimate Your Coverage', ['Vision insurance covers routine eye exams, prescription glasses, and contact lenses at reduced costs. Most plans include an annual eye exam and allowances for frames or contacts.', 'This calculator estimates monthly premiums and savings based on your family size, vision needs, and plan tier. Individual plans average $8-$25/month.', 'Without insurance, an eye exam costs $100-$250, glasses $200-$600, and annual contacts $200-$400. Vision insurance makes regular eye care more affordable.', 'For related tools, see our <a href="/${lang}/tools/health-insurance-calculator">health insurance calculator</a> and <a href="/${lang}/tools/dental-insurance-calculator">dental insurance calculator</a>.'], [{q:'Is vision insurance worth it?',a:'If you wear glasses or contacts, yes. The annual frame/contact allowance plus covered exams typically exceeds the annual premium.'},{q:'What does vision insurance cover?',a:'Annual eye exams, frames/lenses, contact lenses, and sometimes LASIK discounts.'},{q:'How often can I get new glasses?',a:'Most plans provide a frame allowance every 12-24 months and an annual exam.'},{q:'Does it cover LASIK?',a:'Many plans offer 10-15% discounts on LASIK but do not cover the full cost.'}]),
  it: mkSeo('Calcolatore Assicurazione Vista', ['L\'assicurazione vista copre esami oculistici, occhiali e lenti a contatto a costi ridotti.', 'Questo calcolatore stima i premi e i risparmi in base alla famiglia e alle esigenze visive.', 'Senza assicurazione, un esame costa 100-250€ e gli occhiali 200-600€.', 'Consulta il <a href="/${lang}/tools/dental-insurance-calculator">calcolatore assicurazione dentale</a>.'], [{q:'Vale la pena?',a:'Se porti occhiali o lenti, si.'},{q:'Cosa copre?',a:'Esami annuali, montature/lenti e lenti a contatto.'},{q:'Ogni quanto nuovi occhiali?',a:'La maggior parte dei piani offre un budget ogni 12-24 mesi.'},{q:'Copre il LASIK?',a:'Molti piani offrono sconti del 10-15% sul LASIK.'}]),
  es: mkSeo('Calculadora de Seguro de Vision', ['El seguro de vision cubre examenes oculares, lentes y contactos a costos reducidos.', 'Esta calculadora estima primas y ahorros segun tu familia y necesidades visuales.', 'Sin seguro, un examen cuesta $100-$250 y los lentes $200-$600.', 'Consulta la <a href="/${lang}/tools/dental-insurance-calculator">calculadora de seguro dental</a>.'], [{q:'Vale la pena?',a:'Si usas lentes o contactos, si.'},{q:'Que cubre?',a:'Examenes anuales, armazones/lentes y contactos.'},{q:'Cada cuanto nuevos lentes?',a:'La mayoria ofrece presupuesto cada 12-24 meses.'},{q:'Cubre LASIK?',a:'Muchos ofrecen descuentos del 10-15%.'}]),
  fr: mkSeo('Calculateur Assurance Vision', ['L\'assurance vision couvre examens de la vue, lunettes et lentilles a couts reduits.', 'Ce calculateur estime primes et economies selon votre famille et vos besoins visuels.', 'Sans assurance, un examen coute 100-250€ et les lunettes 200-600€.', 'Consultez le <a href="/${lang}/tools/dental-insurance-calculator">calculateur assurance dentaire</a>.'], [{q:'Ca vaut le coup?',a:'Si vous portez des lunettes ou lentilles, oui.'},{q:'Que couvre-t-elle?',a:'Examens annuels, montures/verres et lentilles.'},{q:'A quelle frequence de nouvelles lunettes?',a:'La plupart offrent un budget tous les 12-24 mois.'},{q:'Couvre-t-elle le LASIK?',a:'Beaucoup offrent 10-15% de remise.'}]),
  de: mkSeo('Sehversicherungsrechner', ['Die Sehversicherung deckt Augenuntersuchungen, Brillen und Kontaktlinsen zu reduzierten Kosten.', 'Dieser Rechner schaetzt Praemien und Ersparnisse basierend auf Familie und Sehbeduerfnissen.', 'Ohne Versicherung kostet eine Untersuchung 100-250€ und eine Brille 200-600€.', 'Nutzen Sie den <a href="/${lang}/tools/dental-insurance-calculator">Zahnversicherungsrechner</a>.'], [{q:'Lohnt sie sich?',a:'Wenn Sie Brille oder Kontaktlinsen tragen, ja.'},{q:'Was deckt sie ab?',a:'Jaehrliche Untersuchungen, Gestelle/Glaeser und Kontaktlinsen.'},{q:'Wie oft neue Brille?',a:'Die meisten bieten alle 12-24 Monate ein Budget.'},{q:'Deckt sie LASIK ab?',a:'Viele bieten 10-15% Rabatt auf LASIK.'}]),
  pt: mkSeo('Calculadora de Seguro de Visao', ['O seguro de visao cobre exames oculares, oculos e lentes de contato a custos reduzidos.', 'Esta calculadora estima premios e economias com base na familia e necessidades visuais.', 'Sem seguro, um exame custa R$100-250 e oculos R$200-600.', 'Consulte a <a href="/${lang}/tools/dental-insurance-calculator">calculadora de seguro dental</a>.'], [{q:'Vale a pena?',a:'Se voce usa oculos ou lentes, sim.'},{q:'O que cobre?',a:'Exames anuais, armacoes/lentes e lentes de contato.'},{q:'Com que frequencia novos oculos?',a:'A maioria oferece orcamento a cada 12-24 meses.'},{q:'Cobre LASIK?',a:'Muitos oferecem desconto de 10-15%.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="vision-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
