'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'systemCost', labels: { en: 'System Cost ($)', it: 'Costo impianto (€)', es: 'Costo del sistema ($)', fr: 'Cout du systeme (€)', de: 'Systemkosten (€)', pt: 'Custo do sistema (R$)' }, defaultValue: '20000' },
  { key: 'annualProduction', labels: { en: 'Annual Production (kWh)', it: 'Produzione annuale (kWh)', es: 'Produccion anual (kWh)', fr: 'Production annuelle (kWh)', de: 'Jahresproduktion (kWh)', pt: 'Producao anual (kWh)' }, defaultValue: '8000' },
  { key: 'electricityRate', labels: { en: 'Electricity Rate ($/kWh)', it: 'Tariffa elettrica (€/kWh)', es: 'Tarifa electrica ($/kWh)', fr: 'Tarif electricite (€/kWh)', de: 'Strompreis (€/kWh)', pt: 'Tarifa eletrica (R$/kWh)' }, defaultValue: '0.15', step: 0.01 },
  { key: 'incentivePercent', labels: { en: 'Tax Incentive (%)', it: 'Incentivo fiscale (%)', es: 'Incentivo fiscal (%)', fr: 'Incitation fiscale (%)', de: 'Steueranreiz (%)', pt: 'Incentivo fiscal (%)' }, defaultValue: '30', min: 0, max: 50 },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackYears', labels: { en: 'Payback Period (years)', it: 'Ammortamento (anni)', es: 'Amortizacion (anos)', fr: 'Amortissement (annees)', de: 'Amortisation (Jahre)', pt: 'Amortizacao (anos)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'twentyFiveYearSavings', labels: { en: '25-Year Net Savings', it: 'Risparmio netto 25 anni', es: 'Ahorro neto 25 anos', fr: 'Economies nettes 25 ans', de: '25-Jahres-Nettoeinsparung', pt: 'Economia liquida 25 anos' }, color: 'green' as const, format: 'currency' as const },
  { key: 'roi', labels: { en: 'ROI (%)', it: 'ROI (%)', es: 'ROI (%)', fr: 'ROI (%)', de: 'ROI (%)', pt: 'ROI (%)' }, color: 'gray' as const, format: 'percent' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const cost = v.systemCost || 20000; const prod = v.annualProduction || 8000; const rate = v.electricityRate || 0.15; const incentive = (v.incentivePercent || 30) / 100;
  const netCost = cost * (1 - incentive); const annual = prod * rate;
  const payback = annual > 0 ? netCost / annual : 99;
  const savings25 = annual * 25 - netCost; const roi = netCost > 0 ? (savings25 / netCost) * 100 : 0;
  return { annualSavings: Math.round(annual), paybackYears: Math.round(payback * 10) / 10, twentyFiveYearSavings: Math.round(savings25), roi: Math.round(roi) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Solar Panel ROI Calculator: Calculate Your Investment Return', ['Solar panels are one of the best long-term investments for homeowners. With federal tax credits, declining installation costs, and rising electricity rates, the return on investment has never been better.', 'This calculator helps you estimate annual savings, payback period, and 25-year net return based on your system cost, energy production, local electricity rates, and available tax incentives.', 'The average residential solar system pays for itself in 6-10 years and generates 3-5x its cost in savings over 25 years. The federal Investment Tax Credit (ITC) currently offers a 30% credit on installation costs.', 'For related tools, see our <a href="/${lang}/tools/solar-savings-calculator">solar savings calculator</a> and <a href="/${lang}/tools/solar-battery-calculator">solar battery calculator</a>.'], [{q:'What is a good ROI for solar panels?',a:'A typical solar ROI is 10-20% annually after the payback period, which is comparable to or better than stock market returns.'},{q:'How long do solar panels last?',a:'Most solar panels have a 25-year warranty and can produce electricity for 30-40 years with gradual efficiency decline of about 0.5% per year.'},{q:'Does the federal tax credit apply to batteries?',a:'Yes, the 30% ITC applies to solar battery storage systems installed with or after solar panels.'},{q:'What affects solar panel ROI the most?',a:'Local electricity rates, sun hours, system cost, available incentives, and net metering policies have the biggest impact on ROI.'}]),
  it: mkSeo('Calcolatore ROI Pannelli Solari', ['I pannelli solari sono uno dei migliori investimenti a lungo termine per i proprietari di casa.', 'Questo calcolatore stima risparmio annuale, periodo di ammortamento e ritorno netto in 25 anni.', 'L\'impianto solare medio si ripaga in 6-10 anni e genera 3-5 volte il suo costo in risparmi su 25 anni.', 'Consulta il <a href="/${lang}/tools/solar-savings-calculator">calcolatore risparmio solare</a>.'], [{q:'Qual e un buon ROI per i pannelli solari?',a:'Un ROI tipico e del 10-20% annuo dopo l\'ammortamento.'},{q:'Quanto durano?',a:'Hanno garanzia 25 anni e producono energia per 30-40 anni.'},{q:'Il credito d\'imposta si applica alle batterie?',a:'Si, il credito si applica anche ai sistemi di accumulo.'},{q:'Cosa influenza di piu il ROI?',a:'Tariffe elettriche locali, ore di sole, costo del sistema e incentivi disponibili.'}]),
  es: mkSeo('Calculadora ROI Paneles Solares', ['Los paneles solares son una de las mejores inversiones a largo plazo.', 'Esta calculadora estima ahorro anual, periodo de amortizacion y retorno neto en 25 anos.', 'El sistema solar promedio se amortiza en 6-10 anos y genera 3-5x su costo en ahorros.', 'Consulta la <a href="/${lang}/tools/solar-savings-calculator">calculadora de ahorro solar</a>.'], [{q:'Cual es un buen ROI para paneles solares?',a:'Un ROI tipico es del 10-20% anual despues de la amortizacion.'},{q:'Cuanto duran?',a:'Tienen garantia de 25 anos y producen energia por 30-40 anos.'},{q:'El credito fiscal se aplica a baterias?',a:'Si, se aplica tambien a sistemas de almacenamiento.'},{q:'Que afecta mas el ROI?',a:'Tarifas electricas, horas de sol, costo del sistema e incentivos.'}]),
  fr: mkSeo('Calculateur ROI Panneaux Solaires', ['Les panneaux solaires sont un des meilleurs investissements a long terme.', 'Ce calculateur estime economies annuelles, amortissement et retour net sur 25 ans.', 'Le systeme solaire moyen se rentabilise en 6-10 ans et genere 3-5x son cout en economies.', 'Consultez le <a href="/${lang}/tools/solar-savings-calculator">calculateur economies solaires</a>.'], [{q:'Quel est un bon ROI pour les panneaux solaires?',a:'Un ROI typique est de 10-20% annuel apres l\'amortissement.'},{q:'Combien de temps durent-ils?',a:'Garantie 25 ans, production d\'energie pendant 30-40 ans.'},{q:'Le credit d\'impot s\'applique aux batteries?',a:'Oui, il s\'applique aussi aux systemes de stockage.'},{q:'Qu\'est-ce qui affecte le plus le ROI?',a:'Tarifs d\'electricite, heures d\'ensoleillement, cout du systeme et incitations.'}]),
  de: mkSeo('Solaranlage ROI Rechner', ['Solaranlagen sind eine der besten langfristigen Investitionen fuer Hausbesitzer.', 'Dieser Rechner schaetzt jaehrliche Ersparnis, Amortisationszeit und 25-Jahres-Nettorendite.', 'Die durchschnittliche Solaranlage amortisiert sich in 6-10 Jahren.', 'Nutzen Sie den <a href="/${lang}/tools/solar-savings-calculator">Solar-Ersparnis-Rechner</a>.'], [{q:'Was ist ein guter ROI fuer Solaranlagen?',a:'Ein typischer ROI liegt bei 10-20% jaehrlich nach der Amortisation.'},{q:'Wie lange halten Solarmodule?',a:'25 Jahre Garantie, Stromproduktion fuer 30-40 Jahre.'},{q:'Gilt die Steuergutschrift fuer Batterien?',a:'Ja, sie gilt auch fuer Speichersysteme.'},{q:'Was beeinflusst den ROI am meisten?',a:'Strompreise, Sonnenstunden, Systemkosten und Foerderungen.'}]),
  pt: mkSeo('Calculadora ROI Paineis Solares', ['Os paineis solares sao um dos melhores investimentos de longo prazo.', 'Esta calculadora estima economia anual, periodo de amortizacao e retorno liquido em 25 anos.', 'O sistema solar medio se paga em 6-10 anos e gera 3-5x seu custo em economias.', 'Consulte a <a href="/${lang}/tools/solar-savings-calculator">calculadora de economia solar</a>.'], [{q:'Qual e um bom ROI para paineis solares?',a:'Um ROI tipico e de 10-20% anual apos a amortizacao.'},{q:'Quanto duram?',a:'Garantia de 25 anos, producao de energia por 30-40 anos.'},{q:'O credito fiscal se aplica a baterias?',a:'Sim, se aplica tambem a sistemas de armazenamento.'},{q:'O que mais afeta o ROI?',a:'Tarifas de energia, horas de sol, custo do sistema e incentivos.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="solar-panel-roi-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
