'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'turbineCapacity', labels: { en: 'Turbine Capacity (kW)', it: 'Capacita turbina (kW)', es: 'Capacidad turbina (kW)', fr: 'Capacite turbine (kW)', de: 'Turbinenkapazitaet (kW)', pt: 'Capacidade turbina (kW)' }, defaultValue: '5', min: 1, max: 100 },
  { key: 'avgWindSpeed', labels: { en: 'Avg Wind Speed (mph)', it: 'Velocita media vento (km/h)', es: 'Velocidad media viento (mph)', fr: 'Vitesse moyenne vent (km/h)', de: 'Durchschn. Windgeschw. (km/h)', pt: 'Velocidade media vento (km/h)' }, defaultValue: '12', min: 3, max: 30 },
  { key: 'installCost', labels: { en: 'Installation Cost ($)', it: 'Costo installazione (€)', es: 'Costo instalacion ($)', fr: 'Cout installation (€)', de: 'Installationskosten (€)', pt: 'Custo instalacao (R$)' }, defaultValue: '30000' },
  { key: 'electricityRate', labels: { en: 'Electricity Rate ($/kWh)', it: 'Tariffa elettrica (€/kWh)', es: 'Tarifa electrica ($/kWh)', fr: 'Tarif electricite (€/kWh)', de: 'Strompreis (€/kWh)', pt: 'Tarifa eletrica (R$/kWh)' }, defaultValue: '0.15', step: 0.01 },
];
const results = [
  { key: 'annualProduction', labels: { en: 'Annual Production (kWh)', it: 'Produzione annuale (kWh)', es: 'Produccion anual (kWh)', fr: 'Production annuelle (kWh)', de: 'Jahresproduktion (kWh)', pt: 'Producao anual (kWh)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackYears', labels: { en: 'Payback Period (years)', it: 'Ammortamento (anni)', es: 'Amortizacion (anos)', fr: 'Amortissement (annees)', de: 'Amortisation (Jahre)', pt: 'Amortizacao (anos)' }, color: 'gray' as const, format: 'number' as const },
  { key: 'co2Saved', labels: { en: 'CO2 Saved (tons/yr)', it: 'CO2 risparmiata (t/anno)', es: 'CO2 ahorrado (t/ano)', fr: 'CO2 economise (t/an)', de: 'CO2 gespart (t/Jahr)', pt: 'CO2 economizado (t/ano)' }, color: 'green' as const, format: 'number' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const kw = v.turbineCapacity || 5; const wind = v.avgWindSpeed || 12; const cost = v.installCost || 30000; const rate = v.electricityRate || 0.15;
  const capacityFactor = Math.min(0.45, wind * 0.025); const annual = kw * 8760 * capacityFactor;
  const savings = annual * rate; const payback = savings > 0 ? cost / savings : 99; const co2 = annual * 0.000417;
  return { annualProduction: Math.round(annual), annualSavings: Math.round(savings), paybackYears: Math.round(payback * 10) / 10, co2Saved: Math.round(co2 * 10) / 10 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Wind Turbine Calculator: Estimate Energy Production', ['Residential wind turbines can generate clean energy for homes in windy areas. This calculator estimates annual energy production, savings, and payback period based on turbine size and local wind conditions.', 'Wind energy production depends heavily on average wind speed. A site needs consistent winds of 10+ mph to make a turbine economically viable. Production increases with the cube of wind speed.', 'Small residential turbines (1-10 kW) typically cost $3,000-$8,000 per kW installed. The federal ITC provides a 30% tax credit for residential wind installations.', 'For related tools, see our <a href="/${lang}/tools/solar-panel-roi-calculator">solar panel ROI calculator</a> and <a href="/${lang}/tools/carbon-footprint-calculator">carbon footprint calculator</a>.'], [{q:'How much energy does a residential wind turbine produce?',a:'A 5 kW turbine in a good wind area can produce 8,000-12,000 kWh/year, covering 50-100% of an average home\'s needs.'},{q:'Do I need a lot of wind?',a:'Average wind speeds of 10+ mph are needed for economic viability. Check your local wind resource maps before investing.'},{q:'How tall are residential turbines?',a:'Typically 60-120 feet. Higher towers capture stronger, more consistent winds.'},{q:'Are wind turbines noisy?',a:'Modern small turbines produce 35-55 dB at ground level, comparable to a quiet conversation or refrigerator.'}]),
  it: mkSeo('Calcolatore Turbina Eolica', ['Le turbine eoliche residenziali possono generare energia pulita in aree ventose.', 'La produzione dipende fortemente dalla velocita media del vento.', 'Le turbine piccole (1-10 kW) costano 3.000-8.000€/kW installato.', 'Consulta il <a href="/${lang}/tools/solar-panel-roi-calculator">calcolatore ROI pannelli solari</a>.'], [{q:'Quanta energia produce?',a:'Una turbina da 5 kW in area ventosa produce 8.000-12.000 kWh/anno.'},{q:'Serve molto vento?',a:'Velocita medie di 16+ km/h sono necessarie per la viabilita economica.'},{q:'Quanto sono alte?',a:'Tipicamente 18-36 metri.'},{q:'Sono rumorose?',a:'Le turbine moderne producono 35-55 dB, come un frigorifero.'}]),
  es: mkSeo('Calculadora de Turbina Eolica', ['Las turbinas eolicas residenciales pueden generar energia limpia en areas ventosas.', 'La produccion depende de la velocidad media del viento.', 'Las turbinas pequenas (1-10 kW) cuestan $3,000-$8,000/kW instalado.', 'Consulta la <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paneles solares</a>.'], [{q:'Cuanta energia produce?',a:'Una turbina de 5 kW en area ventosa produce 8,000-12,000 kWh/ano.'},{q:'Se necesita mucho viento?',a:'Velocidades medias de 16+ km/h son necesarias.'},{q:'Que tan altas son?',a:'Tipicamente 18-36 metros.'},{q:'Son ruidosas?',a:'Las turbinas modernas producen 35-55 dB.'}]),
  fr: mkSeo('Calculateur Eolienne', ['Les eoliennes residentielles peuvent generer de l\'energie propre dans les zones ventees.', 'La production depend de la vitesse moyenne du vent.', 'Les petites eoliennes (1-10 kW) coutent 3 000-8 000€/kW installe.', 'Consultez le <a href="/${lang}/tools/solar-panel-roi-calculator">calculateur ROI panneaux solaires</a>.'], [{q:'Combien d\'energie produit-elle?',a:'Une eolienne de 5 kW en zone ventee produit 8 000-12 000 kWh/an.'},{q:'Faut-il beaucoup de vent?',a:'Des vitesses moyennes de 16+ km/h sont necessaires.'},{q:'Quelle hauteur?',a:'Typiquement 18-36 metres.'},{q:'Sont-elles bruyantes?',a:'Les eoliennes modernes produisent 35-55 dB.'}]),
  de: mkSeo('Windturbinen-Rechner', ['Wohn-Windturbinen koennen in windigen Gebieten saubere Energie erzeugen.', 'Die Produktion haengt stark von der durchschnittlichen Windgeschwindigkeit ab.', 'Kleine Turbinen (1-10 kW) kosten 3.000-8.000€/kW installiert.', 'Nutzen Sie den <a href="/${lang}/tools/solar-panel-roi-calculator">Solaranlage ROI Rechner</a>.'], [{q:'Wie viel Energie wird produziert?',a:'Eine 5 kW Turbine in windiger Lage produziert 8.000-12.000 kWh/Jahr.'},{q:'Braucht man viel Wind?',a:'Durchschnittliche Windgeschwindigkeiten von 16+ km/h sind notwendig.'},{q:'Wie hoch sind sie?',a:'Typisch 18-36 Meter.'},{q:'Sind sie laut?',a:'Moderne Turbinen erzeugen 35-55 dB.'}]),
  pt: mkSeo('Calculadora de Turbina Eolica', ['As turbinas eolicas residenciais podem gerar energia limpa em areas ventosas.', 'A producao depende da velocidade media do vento.', 'Turbinas pequenas (1-10 kW) custam R$3.000-8.000/kW instalado.', 'Consulte a <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paineis solares</a>.'], [{q:'Quanta energia produz?',a:'Uma turbina de 5 kW em area ventosa produz 8.000-12.000 kWh/ano.'},{q:'Precisa de muito vento?',a:'Velocidades medias de 16+ km/h sao necessarias.'},{q:'Qual a altura?',a:'Tipicamente 18-36 metros.'},{q:'Sao barulhentas?',a:'Turbinas modernas produzem 35-55 dB.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="wind-turbine-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
