'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'batterySize', labels: { en: 'Battery Size (kWh)', it: 'Capacita batteria (kWh)', es: 'Tamano bateria (kWh)', fr: 'Taille batterie (kWh)', de: 'Batteriegroesse (kWh)', pt: 'Tamanho bateria (kWh)' }, defaultValue: '60' },
  { key: 'efficiency', labels: { en: 'Rated Efficiency (mi/kWh)', it: 'Efficienza nominale (km/kWh)', es: 'Eficiencia nominal (mi/kWh)', fr: 'Efficacite nominale (km/kWh)', de: 'Nenneffizienz (km/kWh)', pt: 'Eficiencia nominal (km/kWh)' }, defaultValue: '4', step: 0.1 },
  { key: 'temperature', labels: { en: 'Temperature (°F)', it: 'Temperatura (°C)', es: 'Temperatura (°F)', fr: 'Temperature (°C)', de: 'Temperatur (°C)', pt: 'Temperatura (°C)' }, defaultValue: '70' },
  { key: 'speed', labels: { en: 'Avg Speed (mph)', it: 'Velocita media (km/h)', es: 'Velocidad media (mph)', fr: 'Vitesse moyenne (km/h)', de: 'Durchschnittsgeschw. (km/h)', pt: 'Velocidade media (km/h)' }, defaultValue: '60' },
];
const results = [
  { key: 'realRange', labels: { en: 'Real-World Range (mi)', it: 'Autonomia reale (km)', es: 'Autonomia real (mi)', fr: 'Autonomie reelle (km)', de: 'Reale Reichweite (km)', pt: 'Autonomia real (km)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'ratedRange', labels: { en: 'Rated Range (mi)', it: 'Autonomia nominale (km)', es: 'Autonomia nominal (mi)', fr: 'Autonomie nominale (km)', de: 'Nennreichweite (km)', pt: 'Autonomia nominal (km)' }, color: 'gray' as const, format: 'number' as const },
  { key: 'rangeLoss', labels: { en: 'Range Loss (%)', it: 'Perdita autonomia (%)', es: 'Perdida autonomia (%)', fr: 'Perte autonomie (%)', de: 'Reichweitenverlust (%)', pt: 'Perda autonomia (%)' }, color: 'red' as const, format: 'percent' as const },
  { key: 'costPerMile', labels: { en: 'Cost Per Mile', it: 'Costo al km', es: 'Costo por milla', fr: 'Cout par km', de: 'Kosten pro km', pt: 'Custo por km' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const bat = v.batterySize || 60; const eff = v.efficiency || 4; const temp = v.temperature || 70; const speed = v.speed || 60;
  const rated = bat * eff; let tempFactor = 1; if (temp < 32) tempFactor = 0.6; else if (temp < 50) tempFactor = 0.8; else if (temp > 95) tempFactor = 0.9;
  const speedFactor = speed > 70 ? 0.85 : speed > 60 ? 0.92 : 1;
  const real = rated * tempFactor * speedFactor; const loss = ((rated - real) / rated) * 100;
  return { realRange: Math.round(real), ratedRange: Math.round(rated), rangeLoss: Math.round(loss), costPerMile: Math.round((0.13 / (eff * tempFactor * speedFactor)) * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('EV Range Calculator: Estimate Real-World Range', ['EPA-rated range rarely matches real-world driving. Temperature, speed, and driving conditions significantly affect how far your EV can go on a single charge.', 'This calculator adjusts your rated range based on temperature and average speed to give a more realistic estimate of your actual driving range.', 'Cold weather is the biggest range killer, reducing range by 20-40% when temperatures drop below freezing. Highway speeds above 70 mph can reduce range by 15% or more.', 'For related tools, see our <a href="/${lang}/tools/ev-charging-cost-calculator">EV charging cost calculator</a> and <a href="/${lang}/tools/ev-vs-gas-calculator">EV vs gas calculator</a>.'], [{q:'How much range do EVs lose in cold weather?',a:'EVs can lose 20-40% of rated range in freezing temperatures due to battery chemistry and cabin heating demands.'},{q:'Does highway speed affect EV range?',a:'Yes, significantly. At 75 mph, range decreases about 15-20% compared to 60 mph due to increased aerodynamic drag.'},{q:'How accurate are EPA range ratings?',a:'EPA ratings are often 10-20% optimistic for real-world driving. Expect 80-90% of rated range in typical conditions.'},{q:'How can I maximize my EV range?',a:'Precondition the cabin while plugged in, drive at moderate speeds, use regenerative braking, and maintain proper tire pressure.'}]),
  it: mkSeo('Calcolatore Autonomia EV', ['L\'autonomia EPA raramente corrisponde alla guida reale. Temperatura e velocita influenzano significativamente l\'autonomia.', 'Questo calcolatore adegua l\'autonomia nominale in base a temperatura e velocita.', 'Il freddo e il maggior nemico dell\'autonomia, riducendola del 20-40% sotto zero.', 'Consulta il <a href="/${lang}/tools/ev-charging-cost-calculator">calcolatore costo ricarica EV</a>.'], [{q:'Quanta autonomia si perde al freddo?',a:'Le EV possono perdere il 20-40% sotto zero.'},{q:'La velocita in autostrada influisce?',a:'Si, a 120 km/h l\'autonomia cala del 15-20%.'},{q:'Quanto sono accurate le stime?',a:'Le stime ufficiali sono spesso 10-20% ottimistiche.'},{q:'Come massimizzare l\'autonomia?',a:'Preriscaldare l\'abitacolo da collegati, velocita moderata, frenata rigenerativa.'}]),
  es: mkSeo('Calculadora de Autonomia EV', ['La autonomia EPA rara vez coincide con la conduccion real.', 'Esta calculadora ajusta tu autonomia nominal segun temperatura y velocidad.', 'El frio reduce la autonomia un 20-40% bajo cero.', 'Consulta la <a href="/${lang}/tools/ev-charging-cost-calculator">calculadora costo carga EV</a>.'], [{q:'Cuanta autonomia se pierde con frio?',a:'Los EV pueden perder 20-40% bajo cero.'},{q:'La velocidad en autopista afecta?',a:'Si, a 120 km/h la autonomia baja 15-20%.'},{q:'Que tan precisas son las estimaciones?',a:'Las estimaciones oficiales son 10-20% optimistas.'},{q:'Como maximizar la autonomia?',a:'Precalentar el habitaculo conectado, velocidad moderada, frenado regenerativo.'}]),
  fr: mkSeo('Calculateur Autonomie VE', ['L\'autonomie EPA correspond rarement a la conduite reelle.', 'Ce calculateur ajuste votre autonomie nominale selon la temperature et la vitesse.', 'Le froid reduit l\'autonomie de 20-40% sous zero.', 'Consultez le <a href="/${lang}/tools/ev-charging-cost-calculator">calculateur cout recharge VE</a>.'], [{q:'Combien d\'autonomie perd-on par temps froid?',a:'Les VE peuvent perdre 20-40% sous zero.'},{q:'La vitesse sur autoroute affecte-t-elle?',a:'Oui, a 120 km/h l\'autonomie baisse de 15-20%.'},{q:'Les estimations sont-elles precises?',a:'Les estimations officielles sont 10-20% optimistes.'},{q:'Comment maximiser l\'autonomie?',a:'Prechauffer l\'habitacle branche, vitesse moderee, freinage regeneratif.'}]),
  de: mkSeo('E-Auto Reichweiten-Rechner', ['Die EPA-Reichweite stimmt selten mit der realen Fahrt ueberein.', 'Dieser Rechner passt Ihre Nennreichweite an Temperatur und Geschwindigkeit an.', 'Kaelte reduziert die Reichweite um 20-40% unter dem Gefrierpunkt.', 'Nutzen Sie den <a href="/${lang}/tools/ev-charging-cost-calculator">E-Auto Ladekosten-Rechner</a>.'], [{q:'Wie viel Reichweite verliert man bei Kaelte?',a:'E-Autos koennen 20-40% unter dem Gefrierpunkt verlieren.'},{q:'Beeinflusst Autobahngeschwindigkeit die Reichweite?',a:'Ja, bei 120 km/h sinkt die Reichweite um 15-20%.'},{q:'Wie genau sind die Angaben?',a:'Offizielle Angaben sind oft 10-20% optimistisch.'},{q:'Wie maximiere ich die Reichweite?',a:'Vorklimatisieren am Strom, moderate Geschwindigkeit, Rekuperation.'}]),
  pt: mkSeo('Calculadora de Autonomia EV', ['A autonomia EPA raramente corresponde a conducao real.', 'Esta calculadora ajusta sua autonomia nominal com base na temperatura e velocidade.', 'O frio reduz a autonomia em 20-40% abaixo de zero.', 'Consulte a <a href="/${lang}/tools/ev-charging-cost-calculator">calculadora custo recarga EV</a>.'], [{q:'Quanta autonomia se perde no frio?',a:'Os EVs podem perder 20-40% abaixo de zero.'},{q:'A velocidade na rodovia afeta?',a:'Sim, a 120 km/h a autonomia cai 15-20%.'},{q:'As estimativas sao precisas?',a:'As estimativas oficiais sao 10-20% otimistas.'},{q:'Como maximizar a autonomia?',a:'Pre-aquecer o habitaculo conectado, velocidade moderada, frenagem regenerativa.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="ev-range-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
