'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'bikeValue', labels: { en: 'Motorcycle Value ($)', it: 'Valore moto (€)', es: 'Valor moto ($)', fr: 'Valeur moto (€)', de: 'Motorradwert (€)', pt: 'Valor moto (R$)' }, defaultValue: '10000' },
  { key: 'engineCC', labels: { en: 'Engine Size (cc)', it: 'Cilindrata (cc)', es: 'Cilindrada (cc)', fr: 'Cylindree (cc)', de: 'Hubraum (cc)', pt: 'Cilindrada (cc)' }, defaultValue: '600', min: 50, max: 2000 },
  { key: 'riderAge', labels: { en: 'Rider Age', it: 'Eta pilota', es: 'Edad conductor', fr: 'Age conducteur', de: 'Alter Fahrer', pt: 'Idade piloto' }, defaultValue: '30', min: 16, max: 80 },
  { key: 'yearsExperience', labels: { en: 'Years of Experience', it: 'Anni di esperienza', es: 'Anos de experiencia', fr: 'Annees d\'experience', de: 'Jahre Erfahrung', pt: 'Anos de experiencia' }, defaultValue: '5', min: 0, max: 40 },
];
const results = [
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'green' as const, format: 'currency' as const },
  { key: 'liabilityCoverage', labels: { en: 'Liability Coverage', it: 'Copertura RC', es: 'Cobertura responsabilidad', fr: 'Couverture RC', de: 'Haftpflichtdeckung', pt: 'Cobertura RC' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'collisionCoverage', labels: { en: 'Collision Coverage', it: 'Copertura collisione', es: 'Cobertura colision', fr: 'Couverture collision', de: 'Kollisionsdeckung', pt: 'Cobertura colisao' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const value = v.bikeValue || 10000; const cc = v.engineCC || 600; const age = v.riderAge || 30; const exp = v.yearsExperience || 5;
  const basePct = 0.06; const ccFactor = cc > 1000 ? 1.5 : cc > 600 ? 1.2 : 1.0;
  const ageFactor = age < 25 ? 1.8 : age > 65 ? 1.3 : 1.0; const expDiscount = Math.min(0.3, exp * 0.03);
  const annual = Math.max(200, value * basePct * ccFactor * ageFactor * (1 - expDiscount));
  return { annualPremium: Math.round(annual), monthlyPremium: Math.round(annual / 12), liabilityCoverage: 100000, collisionCoverage: Math.round(value) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Motorcycle Insurance Calculator: Estimate Your Premium', ['Motorcycle insurance is essential for protecting yourself and your bike on the road. Premiums vary widely based on bike type, engine size, rider age, and experience level.', 'This calculator estimates your annual and monthly premiums based on motorcycle value, engine displacement, rider age, and years of riding experience. Sport bikes with large engines cost significantly more to insure.', 'The average motorcycle insurance premium is $500-$1,500/year for liability coverage. Full coverage with collision and comprehensive can cost $1,000-$3,000+ for sport bikes.', 'For related tools, see our <a href="/${lang}/tools/car-insurance-calculator">car insurance calculator</a> and <a href="/${lang}/tools/gap-insurance-calculator">GAP insurance calculator</a>.'], [{q:'How much is motorcycle insurance?',a:'Average premiums range from $500-$1,500/year. Sport bikes and riders under 25 pay significantly more.'},{q:'What factors affect motorcycle insurance rates?',a:'Engine size, bike type, rider age, experience, driving record, and location are the main factors.'},{q:'Do I need full coverage on a motorcycle?',a:'Full coverage is recommended for newer or financed bikes. Older bikes may only need liability coverage.'},{q:'Does a safety course lower premiums?',a:'Yes, completing a motorcycle safety course can reduce premiums by 5-15% with most insurers.'}]),
  it: mkSeo('Calcolatore Assicurazione Moto', ['L\'assicurazione moto e essenziale per proteggerti e proteggere la tua moto.', 'Questo calcolatore stima il premio in base a valore, cilindrata, eta e esperienza.', 'Il premio medio per la moto e 500-1.500€/anno per la RC.', 'Consulta il <a href="/${lang}/tools/car-insurance-calculator">calcolatore assicurazione auto</a>.'], [{q:'Quanto costa?',a:'I premi medi vanno da 500 a 1.500€/anno.'},{q:'Quali fattori influenzano il prezzo?',a:'Cilindrata, tipo di moto, eta, esperienza e storico di guida.'},{q:'Serve la copertura completa?',a:'Raccomandata per moto nuove o finanziate.'},{q:'Un corso di guida sicura riduce il premio?',a:'Si, del 5-15% con la maggior parte degli assicuratori.'}]),
  es: mkSeo('Calculadora de Seguro de Moto', ['El seguro de moto es esencial para protegerte en la carretera.', 'Esta calculadora estima tu prima segun valor, cilindrada, edad y experiencia.', 'La prima promedio es $500-$1,500/ano para RC.', 'Consulta la <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro de auto</a>.'], [{q:'Cuanto cuesta?',a:'Primas promedio de $500-$1,500/ano.'},{q:'Que factores afectan el precio?',a:'Cilindrada, tipo de moto, edad y experiencia.'},{q:'Necesito cobertura completa?',a:'Recomendada para motos nuevas o financiadas.'},{q:'Un curso de seguridad reduce la prima?',a:'Si, del 5-15%.'}]),
  fr: mkSeo('Calculateur Assurance Moto', ['L\'assurance moto est essentielle pour vous proteger sur la route.', 'Ce calculateur estime votre prime selon la valeur, la cylindree, l\'age et l\'experience.', 'La prime moyenne est de 500-1 500€/an pour la RC.', 'Consultez le <a href="/${lang}/tools/car-insurance-calculator">calculateur assurance auto</a>.'], [{q:'Combien ca coute?',a:'Primes moyennes de 500-1 500€/an.'},{q:'Quels facteurs affectent le prix?',a:'Cylindree, type de moto, age et experience.'},{q:'Ai-je besoin d\'une couverture complete?',a:'Recommandee pour les motos neuves ou financees.'},{q:'Un stage de conduite reduit la prime?',a:'Oui, de 5-15%.'}]),
  de: mkSeo('Motorradversicherungsrechner', ['Die Motorradversicherung ist essentiell fuer den Schutz auf der Strasse.', 'Dieser Rechner schaetzt Ihre Praemie basierend auf Wert, Hubraum, Alter und Erfahrung.', 'Die durchschnittliche Praemie betraegt 500-1.500€/Jahr fuer die Haftpflicht.', 'Nutzen Sie den <a href="/${lang}/tools/car-insurance-calculator">Kfz-Versicherungsrechner</a>.'], [{q:'Was kostet sie?',a:'Durchschnittlich 500-1.500€/Jahr.'},{q:'Welche Faktoren beeinflussen den Preis?',a:'Hubraum, Motorradtyp, Alter und Erfahrung.'},{q:'Brauche ich Vollkasko?',a:'Empfohlen fuer neue oder finanzierte Motorraeder.'},{q:'Senkt ein Sicherheitskurs die Praemie?',a:'Ja, um 5-15%.'}]),
  pt: mkSeo('Calculadora de Seguro de Moto', ['O seguro de moto e essencial para proteger voce na estrada.', 'Esta calculadora estima seu premio com base no valor, cilindrada, idade e experiencia.', 'O premio medio e R$500-1.500/ano para RC.', 'Consulte a <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro auto</a>.'], [{q:'Quanto custa?',a:'Premios medios de R$500-1.500/ano.'},{q:'Que fatores afetam o preco?',a:'Cilindrada, tipo de moto, idade e experiencia.'},{q:'Preciso de cobertura completa?',a:'Recomendada para motos novas ou financiadas.'},{q:'Um curso de seguranca reduz o premio?',a:'Sim, de 5-15%.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="motorcycle-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
