'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'electricityKwh', labels: { en: 'Monthly Electricity (kWh)', it: 'Elettricita mensile (kWh)', es: 'Electricidad mensual (kWh)', fr: 'Electricite mensuelle (kWh)', de: 'Monatlicher Strom (kWh)', pt: 'Eletricidade mensal (kWh)' }, defaultValue: '900' },
  { key: 'naturalGas', labels: { en: 'Monthly Gas (therms)', it: 'Gas mensile (m³)', es: 'Gas mensual (therms)', fr: 'Gaz mensuel (m³)', de: 'Monatliches Gas (m³)', pt: 'Gas mensal (m³)' }, defaultValue: '50' },
  { key: 'carMiles', labels: { en: 'Monthly Driving (miles)', it: 'Km mensili auto', es: 'Millas mensuales auto', fr: 'Km mensuels voiture', de: 'Monatliche Auto-Km', pt: 'Km mensais carro' }, defaultValue: '1000' },
  { key: 'flights', labels: { en: 'Flights Per Year', it: 'Voli all\'anno', es: 'Vuelos al ano', fr: 'Vols par an', de: 'Fluege pro Jahr', pt: 'Voos por ano' }, defaultValue: '4', min: 0, max: 50 },
];
const results = [
  { key: 'totalTons', labels: { en: 'Annual CO2 (tons)', it: 'CO2 annuale (tonnellate)', es: 'CO2 anual (toneladas)', fr: 'CO2 annuel (tonnes)', de: 'Jaehrliches CO2 (Tonnen)', pt: 'CO2 anual (toneladas)' }, color: 'red' as const, format: 'number' as const },
  { key: 'energyCO2', labels: { en: 'Home Energy CO2', it: 'CO2 energia casa', es: 'CO2 energia hogar', fr: 'CO2 energie maison', de: 'Hausenergie-CO2', pt: 'CO2 energia casa' }, color: 'gray' as const, format: 'number' as const },
  { key: 'transportCO2', labels: { en: 'Transport CO2', it: 'CO2 trasporti', es: 'CO2 transporte', fr: 'CO2 transport', de: 'Transport-CO2', pt: 'CO2 transporte' }, color: 'gray' as const, format: 'number' as const },
  { key: 'treesNeeded', labels: { en: 'Trees to Offset', it: 'Alberi per compensare', es: 'Arboles para compensar', fr: 'Arbres pour compenser', de: 'Baeume zum Ausgleich', pt: 'Arvores para compensar' }, color: 'green' as const, format: 'number' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const elec = (v.electricityKwh || 900) * 12 * 0.000417; // tons CO2 per kWh
  const gas = (v.naturalGas || 50) * 12 * 0.005; // tons CO2 per therm
  const car = (v.carMiles || 1000) * 12 * 0.000404; // tons CO2 per mile
  const fly = (v.flights || 4) * 0.9; // tons per round-trip flight avg
  const total = elec + gas + car + fly;
  return { totalTons: Math.round(total * 10) / 10, energyCO2: Math.round((elec + gas) * 10) / 10, transportCO2: Math.round((car + fly) * 10) / 10, treesNeeded: Math.round(total / 0.022) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Carbon Footprint Calculator: Calculate Your CO2 Emissions', ['Understanding your carbon footprint is the first step toward reducing your environmental impact. This calculator estimates your annual CO2 emissions from home energy use, driving, and air travel.', 'The average American produces about 16 tons of CO2 per year, compared to a global average of 4 tons. Reducing your footprint starts with understanding where your emissions come from.', 'Home energy and transportation typically account for 60-70% of personal emissions. Simple changes like switching to LED bulbs, improving insulation, or driving an EV can significantly reduce your footprint.', 'For related tools, see our <a href="/${lang}/tools/ev-vs-gas-calculator">EV vs gas calculator</a> and <a href="/${lang}/tools/heat-pump-calculator">heat pump calculator</a>.'], [{q:'What is a carbon footprint?',a:'The total amount of greenhouse gases (mainly CO2) produced by your activities, measured in metric tons per year.'},{q:'What is the average carbon footprint?',a:'The US average is about 16 tons/year per person. The global average is about 4 tons.'},{q:'How can I reduce my carbon footprint?',a:'Drive less or switch to an EV, improve home insulation, use renewable energy, fly less, and eat less meat.'},{q:'How many trees offset 1 ton of CO2?',a:'One mature tree absorbs about 22 kg (48 lbs) of CO2 per year, so roughly 45 trees per ton.'}]),
  it: mkSeo('Calcolatore Impronta Carbonica', ['Capire la tua impronta carbonica e il primo passo per ridurre il tuo impatto ambientale.', 'L\'americano medio produce circa 16 tonnellate di CO2 all\'anno, contro una media globale di 4 tonnellate.', 'Energia domestica e trasporti rappresentano il 60-70% delle emissioni personali.', 'Consulta il <a href="/${lang}/tools/ev-vs-gas-calculator">calcolatore EV vs benzina</a>.'], [{q:'Cos\'e l\'impronta carbonica?',a:'Il totale dei gas serra prodotti dalle tue attivita, misurato in tonnellate/anno.'},{q:'Qual e la media?',a:'La media USA e circa 16 tonnellate/anno. La media globale e circa 4.'},{q:'Come ridurla?',a:'Guida meno, migliora l\'isolamento, usa energie rinnovabili, vola meno.'},{q:'Quanti alberi servono?',a:'Un albero maturo assorbe circa 22 kg di CO2/anno.'}]),
  es: mkSeo('Calculadora de Huella de Carbono', ['Entender tu huella de carbono es el primer paso para reducir tu impacto ambiental.', 'El estadounidense promedio produce unas 16 toneladas de CO2 al ano.', 'Energia del hogar y transporte representan el 60-70% de las emisiones personales.', 'Consulta la <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'Que es la huella de carbono?',a:'El total de gases de efecto invernadero producidos por tus actividades.'},{q:'Cual es el promedio?',a:'El promedio de EE.UU. es unas 16 toneladas/ano.'},{q:'Como reducirla?',a:'Conduce menos, mejora el aislamiento, usa energia renovable.'},{q:'Cuantos arboles se necesitan?',a:'Un arbol maduro absorbe unos 22 kg de CO2/ano.'}]),
  fr: mkSeo('Calculateur Empreinte Carbone', ['Comprendre votre empreinte carbone est la premiere etape pour reduire votre impact environnemental.', 'L\'Americain moyen produit environ 16 tonnes de CO2 par an.', 'L\'energie domestique et les transports representent 60-70% des emissions personnelles.', 'Consultez le <a href="/${lang}/tools/ev-vs-gas-calculator">calculateur VE vs essence</a>.'], [{q:'Qu\'est-ce que l\'empreinte carbone?',a:'Le total des gaz a effet de serre produits par vos activites.'},{q:'Quelle est la moyenne?',a:'La moyenne americaine est environ 16 tonnes/an.'},{q:'Comment la reduire?',a:'Conduisez moins, ameliorez l\'isolation, utilisez l\'energie renouvelable.'},{q:'Combien d\'arbres faut-il?',a:'Un arbre mature absorbe environ 22 kg de CO2/an.'}]),
  de: mkSeo('CO2-Fussabdruck-Rechner', ['Ihren CO2-Fussabdruck zu verstehen ist der erste Schritt zur Reduzierung Ihres Umwelteinflusses.', 'Der durchschnittliche Amerikaner produziert etwa 16 Tonnen CO2 pro Jahr.', 'Hausenergie und Transport machen 60-70% der persoenlichen Emissionen aus.', 'Nutzen Sie den <a href="/${lang}/tools/ev-vs-gas-calculator">E-Auto vs Benziner Rechner</a>.'], [{q:'Was ist der CO2-Fussabdruck?',a:'Die Gesamtmenge an Treibhausgasen aus Ihren Aktivitaeten.'},{q:'Was ist der Durchschnitt?',a:'Der US-Durchschnitt liegt bei etwa 16 Tonnen/Jahr.'},{q:'Wie reduziere ich ihn?',a:'Weniger fahren, Daemmung verbessern, erneuerbare Energie nutzen.'},{q:'Wie viele Baeume braucht man?',a:'Ein ausgewachsener Baum absorbiert etwa 22 kg CO2/Jahr.'}]),
  pt: mkSeo('Calculadora de Pegada de Carbono', ['Entender sua pegada de carbono e o primeiro passo para reduzir seu impacto ambiental.', 'O americano medio produz cerca de 16 toneladas de CO2 por ano.', 'Energia domestica e transporte representam 60-70% das emissoes pessoais.', 'Consulte a <a href="/${lang}/tools/ev-vs-gas-calculator">calculadora EV vs gasolina</a>.'], [{q:'O que e a pegada de carbono?',a:'O total de gases de efeito estufa produzidos por suas atividades.'},{q:'Qual e a media?',a:'A media dos EUA e cerca de 16 toneladas/ano.'},{q:'Como reduzi-la?',a:'Dirija menos, melhore o isolamento, use energia renovavel.'},{q:'Quantas arvores sao necessarias?',a:'Uma arvore madura absorve cerca de 22 kg de CO2/ano.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="carbon-footprint-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
