'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'annualMiles', labels: { en: 'Annual Miles', it: 'Km annuali', es: 'Millas anuales', fr: 'Km annuels', de: 'Jaehrliche Km', pt: 'Km anuais' }, defaultValue: '12000' },
  { key: 'gasPrice', labels: { en: 'Gas Price ($/gal)', it: 'Prezzo benzina (€/L)', es: 'Precio gasolina ($/gal)', fr: 'Prix essence (€/L)', de: 'Benzinpreis (€/L)', pt: 'Preco gasolina (R$/L)' }, defaultValue: '3.50', step: 0.1 },
  { key: 'gasMPG', labels: { en: 'Gas Car MPG', it: 'Km/L auto benzina', es: 'MPG auto gasolina', fr: 'Km/L auto essence', de: 'Km/L Benzinauto', pt: 'Km/L carro gasolina' }, defaultValue: '30' },
  { key: 'electricityRate', labels: { en: 'Electricity ($/kWh)', it: 'Elettricita (€/kWh)', es: 'Electricidad ($/kWh)', fr: 'Electricite (€/kWh)', de: 'Strom (€/kWh)', pt: 'Eletricidade (R$/kWh)' }, defaultValue: '0.13', step: 0.01 },
  { key: 'evEfficiency', labels: { en: 'EV Efficiency (mi/kWh)', it: 'Efficienza EV (km/kWh)', es: 'Eficiencia EV (mi/kWh)', fr: 'Efficacite VE (km/kWh)', de: 'EV-Effizienz (km/kWh)', pt: 'Eficiencia EV (km/kWh)' }, defaultValue: '3.5', step: 0.1 },
];
const results = [
  { key: 'gasFuelCost', labels: { en: 'Gas Annual Fuel Cost', it: 'Costo carburante annuo', es: 'Costo combustible anual', fr: 'Cout carburant annuel', de: 'Jaehrliche Kraftstoffkosten', pt: 'Custo combustivel anual' }, color: 'red' as const, format: 'currency' as const },
  { key: 'evFuelCost', labels: { en: 'EV Annual Charging Cost', it: 'Costo ricarica annuo EV', es: 'Costo carga anual EV', fr: 'Cout recharge annuel VE', de: 'Jaehrliche EV-Ladekosten', pt: 'Custo recarga anual EV' }, color: 'green' as const, format: 'currency' as const },
  { key: 'annualSavings', labels: { en: 'Annual Fuel Savings', it: 'Risparmio carburante annuo', es: 'Ahorro combustible anual', fr: 'Economies carburant annuelles', de: 'Jaehrliche Kraftstoffersparnis', pt: 'Economia combustivel anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'fiveYearSavings', labels: { en: '5-Year Total Savings', it: 'Risparmio totale 5 anni', es: 'Ahorro total 5 anos', fr: 'Economies totales 5 ans', de: '5-Jahres-Gesamtersparnis', pt: 'Economia total 5 anos' }, color: 'green' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const miles = v.annualMiles || 12000; const gas = v.gasPrice || 3.5; const mpg = v.gasMPG || 30;
  const elec = v.electricityRate || 0.13; const eff = v.evEfficiency || 3.5;
  const gasCost = (miles / mpg) * gas; const evCost = (miles / eff) * elec;
  const saving = gasCost - evCost; const maintenanceSaving = 500;
  return { gasFuelCost: Math.round(gasCost), evFuelCost: Math.round(evCost), annualSavings: Math.round(saving + maintenanceSaving), fiveYearSavings: Math.round((saving + maintenanceSaving) * 5) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('EV vs Gas Cost Calculator: Compare Ownership Costs', ['Deciding between an electric vehicle and a gas car? This calculator compares annual fuel costs, maintenance savings, and total cost of ownership over 5 years to help you make an informed decision.', 'Electric vehicles typically cost 50-70% less to fuel than gas cars. At average electricity rates, charging an EV costs about $0.04 per mile compared to $0.12-$0.15 per mile for gas.', 'Beyond fuel savings, EVs save $500-$1,000 annually on maintenance due to fewer moving parts, no oil changes, and regenerative braking that extends brake pad life.', 'For related tools, see our <a href="/${lang}/tools/ev-charging-cost-calculator">EV charging cost calculator</a> and <a href="/${lang}/tools/ev-savings-calculator">EV savings calculator</a>.'], [{q:'Are electric cars cheaper to own?',a:'Yes, typically $1,000-$2,500/year cheaper in fuel and maintenance combined, though upfront costs are often higher.'},{q:'How much does it cost to charge an EV?',a:'At average US electricity rates, charging costs about $0.04/mile or $30-$60/month for typical driving.'},{q:'Do EVs require less maintenance?',a:'Yes, significantly less. No oil changes, fewer brake replacements, and fewer moving parts mean lower maintenance costs.'},{q:'What about EV battery replacement?',a:'Modern EV batteries last 200,000-300,000 miles. Most automakers offer 8-year/100,000-mile battery warranties.'}]),
  it: mkSeo('Calcolatore EV vs Benzina', ['Indeciso tra veicolo elettrico e auto a benzina? Questo calcolatore confronta i costi annuali.', 'I veicoli elettrici costano tipicamente il 50-70% in meno per il carburante rispetto alle auto a benzina.', 'Oltre al risparmio carburante, le EV risparmiano 500-1.000€/anno in manutenzione.', 'Consulta il <a href="/${lang}/tools/ev-charging-cost-calculator">calcolatore costo ricarica EV</a>.'], [{q:'Le auto elettriche sono piu economiche?',a:'Si, tipicamente 1.000-2.500€/anno in meno tra carburante e manutenzione.'},{q:'Quanto costa ricaricare un EV?',a:'Circa 0,04€/km con tariffe medie.'},{q:'Le EV richiedono meno manutenzione?',a:'Si, significativamente meno. Niente cambio olio, meno parti mobili.'},{q:'E la sostituzione della batteria?',a:'Le batterie moderne durano 200.000-300.000 km con garanzia di 8 anni.'}]),
  es: mkSeo('Calculadora EV vs Gasolina', ['Indeciso entre un vehiculo electrico y uno de gasolina? Esta calculadora compara los costos anuales.', 'Los vehiculos electricos cuestan tipicamente 50-70% menos en combustible.', 'Ademas del ahorro en combustible, los EV ahorran $500-$1,000/ano en mantenimiento.', 'Consulta la <a href="/${lang}/tools/ev-charging-cost-calculator">calculadora costo carga EV</a>.'], [{q:'Los autos electricos son mas baratos?',a:'Si, tipicamente $1,000-$2,500/ano menos en combustible y mantenimiento.'},{q:'Cuanto cuesta cargar un EV?',a:'Aproximadamente $0.04/milla con tarifas promedio.'},{q:'Los EV requieren menos mantenimiento?',a:'Si, significativamente menos.'},{q:'Y el reemplazo de bateria?',a:'Las baterias modernas duran 200,000-300,000 millas.'}]),
  fr: mkSeo('Calculateur VE vs Essence', ['Indecis entre vehicule electrique et voiture essence? Ce calculateur compare les couts annuels.', 'Les VE coutent typiquement 50-70% moins cher en carburant.', 'Au-dela du carburant, les VE economisent 500-1 000€/an en entretien.', 'Consultez le <a href="/${lang}/tools/ev-charging-cost-calculator">calculateur cout recharge VE</a>.'], [{q:'Les voitures electriques sont moins cheres?',a:'Oui, typiquement 1 000-2 500€/an en moins.'},{q:'Combien coute la recharge?',a:'Environ 0,04€/km aux tarifs moyens.'},{q:'Moins d\'entretien?',a:'Oui, significativement moins.'},{q:'Et le remplacement de batterie?',a:'Les batteries modernes durent 200 000-300 000 km.'}]),
  de: mkSeo('E-Auto vs Benziner Rechner', ['Unentschlossen zwischen E-Auto und Benziner? Dieser Rechner vergleicht die Jahreskosten.', 'E-Autos kosten typisch 50-70% weniger an Kraftstoff.', 'Neben Kraftstoff sparen E-Autos 500-1.000€/Jahr an Wartung.', 'Nutzen Sie den <a href="/${lang}/tools/ev-charging-cost-calculator">E-Auto Ladekosten-Rechner</a>.'], [{q:'Sind E-Autos guenstiger?',a:'Ja, typisch 1.000-2.500€/Jahr weniger.'},{q:'Was kostet das Laden?',a:'Etwa 0,04€/km bei durchschnittlichen Tarifen.'},{q:'Weniger Wartung?',a:'Ja, deutlich weniger.'},{q:'Und der Batteriewechsel?',a:'Moderne Batterien halten 200.000-300.000 km.'}]),
  pt: mkSeo('Calculadora EV vs Gasolina', ['Indeciso entre veiculo eletrico e carro a gasolina? Esta calculadora compara os custos anuais.', 'Os EVs custam tipicamente 50-70% menos em combustivel.', 'Alem do combustivel, os EVs economizam R$500-1.000/ano em manutencao.', 'Consulte a <a href="/${lang}/tools/ev-charging-cost-calculator">calculadora custo recarga EV</a>.'], [{q:'Carros eletricos sao mais baratos?',a:'Sim, tipicamente R$1.000-2.500/ano a menos.'},{q:'Quanto custa carregar?',a:'Aproximadamente R$0,04/km com tarifas medias.'},{q:'Menos manutencao?',a:'Sim, significativamente menos.'},{q:'E a troca de bateria?',a:'Baterias modernas duram 200.000-300.000 km.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="ev-vs-gas-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
