'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'totalValue', labels: { en: 'Total Jewelry Value ($)', it: 'Valore totale gioielli (€)', es: 'Valor total joyas ($)', fr: 'Valeur totale bijoux (€)', de: 'Gesamtschmuckwert (€)', pt: 'Valor total joias (R$)' }, defaultValue: '10000' },
  { key: 'numPieces', labels: { en: 'Number of Pieces', it: 'Numero di pezzi', es: 'Numero de piezas', fr: 'Nombre de pieces', de: 'Anzahl Stuecke', pt: 'Numero de pecas' }, defaultValue: '3', min: 1, max: 50 },
  { key: 'highestSingle', labels: { en: 'Highest Single Piece ($)', it: 'Pezzo piu costoso (€)', es: 'Pieza mas cara ($)', fr: 'Piece la plus chere (€)', de: 'Teuerstes Stueck (€)', pt: 'Peca mais cara (R$)' }, defaultValue: '5000' },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '0' },
];
const results = [
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'green' as const, format: 'currency' as const },
  { key: 'replacementValue', labels: { en: 'Replacement Value', it: 'Valore sostituzione', es: 'Valor reposicion', fr: 'Valeur remplacement', de: 'Wiederbeschaffungswert', pt: 'Valor reposicao' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'costPer1000', labels: { en: 'Cost Per $1,000 Insured', it: 'Costo per 1.000€ assicurati', es: 'Costo por $1,000 asegurados', fr: 'Cout par 1 000€ assures', de: 'Kosten pro 1.000€ versichert', pt: 'Custo por R$1.000 segurados' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const total = v.totalValue || 10000; const pieces = v.numPieces || 3; const highest = v.highestSingle || 5000; const ded = v.deductible || 0;
  const basePct = 0.015; // 1-2% is typical
  const highValueMult = highest > 10000 ? 1.3 : highest > 5000 ? 1.1 : 1.0;
  const dedDiscount = ded > 0 ? 0.85 : 1.0;
  const annual = total * basePct * highValueMult * dedDiscount;
  return { annualPremium: Math.round(annual), monthlyPremium: Math.round(annual / 12), replacementValue: Math.round(total), costPer1000: Math.round((annual / total) * 1000 * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Jewelry Insurance Calculator: Protect Your Valuables', ['Jewelry insurance provides coverage for your engagement rings, watches, and fine jewelry against loss, theft, damage, and mysterious disappearance. Standard homeowners insurance often has low limits for jewelry.', 'This calculator estimates your annual premium based on total jewelry value, number of pieces, and deductible. Typical rates are 1-2% of the appraised value per year.', 'The average engagement ring costs $5,000-$6,000 and is one of the most commonly lost or stolen items. Dedicated jewelry insurance provides full replacement value with no deductible.', 'For related tools, see our <a href="/${lang}/tools/home-insurance-calculator">home insurance calculator</a> and <a href="/${lang}/tools/wedding-insurance-calculator">wedding insurance calculator</a>.'], [{q:'Is jewelry insurance worth it?',a:'Yes, especially for engagement rings and pieces over $1,000. Standard homeowners insurance typically only covers $1,500-$2,500 for jewelry.'},{q:'What does it cover?',a:'Theft, loss, damage, mysterious disappearance, and often worldwide coverage with full replacement value.'},{q:'How much does it cost?',a:'Typically 1-2% of the appraised value per year, or $100-$200/year for a $10,000 ring.'},{q:'Do I need an appraisal?',a:'Yes, most insurers require a professional appraisal for pieces over $1,000. Appraisals should be updated every 2-3 years.'}]),
  it: mkSeo('Calcolatore Assicurazione Gioielli', ['L\'assicurazione gioielli fornisce copertura per anelli, orologi e gioielli contro perdita, furto e danni.', 'Questo calcolatore stima il premio annuale in base al valore totale e alla franchigia. Tariffe tipiche: 1-2% del valore stimato.', 'L\'anello di fidanzamento medio costa 5.000-6.000€ ed e uno degli oggetti piu comunemente persi o rubati.', 'Consulta il <a href="/${lang}/tools/wedding-insurance-calculator">calcolatore assicurazione matrimonio</a>.'], [{q:'Vale la pena?',a:'Si, specialmente per pezzi oltre 1.000€.'},{q:'Cosa copre?',a:'Furto, perdita, danni e scomparsa misteriosa.'},{q:'Quanto costa?',a:'1-2% del valore stimato per anno.'},{q:'Serve una perizia?',a:'Si, per pezzi oltre 1.000€. Aggiornare ogni 2-3 anni.'}]),
  es: mkSeo('Calculadora de Seguro de Joyas', ['El seguro de joyas protege tus anillos, relojes y joyas finas contra perdida, robo y danos.', 'Esta calculadora estima tu prima anual segun el valor total y deducible. Tarifas tipicas: 1-2% del valor.', 'El anillo de compromiso promedio cuesta $5,000-$6,000.', 'Consulta la <a href="/${lang}/tools/wedding-insurance-calculator">calculadora de seguro de boda</a>.'], [{q:'Vale la pena?',a:'Si, especialmente para piezas de mas de $1,000.'},{q:'Que cubre?',a:'Robo, perdida, danos y desaparicion misteriosa.'},{q:'Cuanto cuesta?',a:'1-2% del valor por ano.'},{q:'Necesito tasacion?',a:'Si, para piezas de mas de $1,000.'}]),
  fr: mkSeo('Calculateur Assurance Bijoux', ['L\'assurance bijoux protege vos bagues, montres et bijoux contre perte, vol et dommages.', 'Ce calculateur estime votre prime annuelle selon la valeur totale et la franchise. Taux typiques: 1-2% de la valeur.', 'La bague de fiancailles moyenne coute 5 000-6 000€.', 'Consultez le <a href="/${lang}/tools/wedding-insurance-calculator">calculateur assurance mariage</a>.'], [{q:'Ca vaut le coup?',a:'Oui, surtout pour les pieces de plus de 1 000€.'},{q:'Que couvre-t-elle?',a:'Vol, perte, dommages et disparition mysterieuse.'},{q:'Combien ca coute?',a:'1-2% de la valeur par an.'},{q:'Faut-il une expertise?',a:'Oui, pour les pieces de plus de 1 000€.'}]),
  de: mkSeo('Schmuckversicherungsrechner', ['Die Schmuckversicherung schuetzt Ihre Ringe, Uhren und Schmuckstuecke vor Verlust, Diebstahl und Schaeden.', 'Dieser Rechner schaetzt Ihre Jahrespraemie basierend auf Gesamtwert und Selbstbeteiligung. Typische Saetze: 1-2% des Werts.', 'Der durchschnittliche Verlobungsring kostet 5.000-6.000€.', 'Nutzen Sie den <a href="/${lang}/tools/wedding-insurance-calculator">Hochzeitsversicherungsrechner</a>.'], [{q:'Lohnt sie sich?',a:'Ja, besonders fuer Stuecke ueber 1.000€.'},{q:'Was deckt sie ab?',a:'Diebstahl, Verlust, Schaeden und mysterioeses Verschwinden.'},{q:'Was kostet sie?',a:'1-2% des Werts pro Jahr.'},{q:'Brauche ich ein Gutachten?',a:'Ja, fuer Stuecke ueber 1.000€.'}]),
  pt: mkSeo('Calculadora de Seguro de Joias', ['O seguro de joias protege seus aneis, relogios e joias finas contra perda, roubo e danos.', 'Esta calculadora estima seu premio anual com base no valor total e franquia. Taxas tipicas: 1-2% do valor.', 'O anel de noivado medio custa R$5.000-6.000.', 'Consulte a <a href="/${lang}/tools/wedding-insurance-calculator">calculadora de seguro de casamento</a>.'], [{q:'Vale a pena?',a:'Sim, especialmente para pecas acima de R$1.000.'},{q:'O que cobre?',a:'Roubo, perda, danos e desaparecimento misterioso.'},{q:'Quanto custa?',a:'1-2% do valor por ano.'},{q:'Preciso de avaliacao?',a:'Sim, para pecas acima de R$1.000.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="jewelry-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
