'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'personalPropertyValue', labels: { en: 'Personal Property Value ($)', it: 'Valore beni (€)', es: 'Valor bienes ($)', fr: 'Valeur biens (€)', de: 'Eigentumswert (€)', pt: 'Valor bens (R$)' }, defaultValue: '20000' },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '500' },
  { key: 'liabilityCoverage', labels: { en: 'Liability Coverage ($)', it: 'Responsabilita civile (€)', es: 'Responsabilidad civil ($)', fr: 'Responsabilite civile (€)', de: 'Haftpflicht (€)', pt: 'Responsabilidade civil (R$)' }, defaultValue: '100000' },
];
const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'personalProperty', labels: { en: 'Property Coverage', it: 'Copertura beni', es: 'Cobertura bienes', fr: 'Couverture biens', de: 'Sachversicherung', pt: 'Cobertura bens' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'liability', labels: { en: 'Liability Coverage', it: 'Responsabilita civile', es: 'Responsabilidad civil', fr: 'Responsabilite civile', de: 'Haftpflicht', pt: 'Responsabilidade civil' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const pv = v.personalPropertyValue || 20000; const baseRate = pv * 0.015; const dd = ((v.deductible || 500) - 250) * 0.1; const la = ((v.liabilityCoverage || 100000) - 100000) / 100000 * 30; const annual = Math.max(100, baseRate - dd + la);
  return { monthlyPremium: Math.round(annual / 12), annualPremium: Math.round(annual), personalProperty: Math.round(pv), liability: v.liabilityCoverage || 100000 };
}
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: { title: 'Renters Insurance Calculator: Estimate Your Premium', paragraphs: ['Renters insurance protects your personal belongings and provides liability coverage when you rent. It is one of the most affordable types of insurance, typically costing $15-30 per month.', 'This calculator estimates your premium based on personal property value, deductible, and liability coverage amount. The base rate is approximately 1.5% of your property value annually.', 'Renters insurance covers personal property against theft, fire, and vandalism. It also provides liability protection if someone is injured in your rental unit and covers additional living expenses if your home becomes uninhabitable.', 'For related tools, check our <a href="/${lang}/tools/home-insurance-calculator">home insurance calculator</a> or the <a href="/${lang}/tools/insurance-deductible-calculator">insurance deductible calculator</a>.'], faq: [{q:'How much renters insurance do I need?',a:'Estimate the total value of all your belongings. Most renters own $20,000-$30,000 worth of personal property.'},{q:'What does renters insurance cover?',a:'Personal property loss, liability claims, additional living expenses, and medical payments. It does NOT cover flooding or earthquakes.'},{q:'Is renters insurance worth it?',a:'At $15-30/month, it is extremely affordable relative to the protection it provides.'},{q:'Can my landlord require renters insurance?',a:'Yes, many landlords require it as a lease condition. Even if not required, it is highly recommended.'}] },
  it: { title: 'Calcolatore Assicurazione Inquilino', paragraphs: ['L\'assicurazione inquilino protegge i tuoi beni personali e offre copertura responsabilita civile quando affitti.', 'Questo calcolatore stima il premio in base al valore dei beni, franchigia e copertura responsabilita.', 'Copre beni personali contro furto, incendio e vandalismo, oltre alla responsabilita civile.', 'Consulta il nostro <a href="/${lang}/tools/home-insurance-calculator">calcolatore assicurazione casa</a>.'], faq: [{q:'Quanta assicurazione inquilino mi serve?',a:'Stima il valore totale di tutti i tuoi beni. La maggior parte degli inquilini possiede beni per 20.000-30.000 euro.'},{q:'Cosa copre l\'assicurazione inquilino?',a:'Beni personali, responsabilita civile, spese di alloggio e spese mediche.'},{q:'Vale la pena l\'assicurazione inquilino?',a:'A 15-30 euro al mese, e molto conveniente rispetto alla protezione offerta.'},{q:'Il padrone di casa puo richiederla?',a:'Si, molti proprietari la richiedono come condizione del contratto.'}] },
  es: { title: 'Calculadora Seguro de Inquilinos', paragraphs: ['El seguro de inquilinos protege tus pertenencias y ofrece cobertura de responsabilidad civil.', 'Esta calculadora estima tu prima basada en el valor de tus bienes, deducible y cobertura de responsabilidad.', 'Cubre bienes personales contra robo, incendio y vandalismo.', 'Consulta nuestra <a href="/${lang}/tools/home-insurance-calculator">calculadora seguro de hogar</a>.'], faq: [{q:'Cuanto seguro de inquilinos necesito?',a:'Estima el valor total de todas tus pertenencias.'},{q:'Que cubre el seguro de inquilinos?',a:'Bienes personales, responsabilidad civil, gastos de alojamiento y gastos medicos.'},{q:'Vale la pena el seguro de inquilinos?',a:'A $15-30/mes, es muy asequible para la proteccion que ofrece.'},{q:'Mi casero puede requerirlo?',a:'Si, muchos propietarios lo requieren como condicion del contrato.'}] },
  fr: { title: 'Calculateur Assurance Locataire', paragraphs: ['L\'assurance locataire protege vos biens personnels et offre une couverture responsabilite civile.', 'Ce calculateur estime votre prime basee sur la valeur de vos biens, la franchise et la couverture responsabilite.', 'Elle couvre les biens contre le vol, l\'incendie et le vandalisme.', 'Consultez notre <a href="/${lang}/tools/home-insurance-calculator">calculateur assurance habitation</a>.'], faq: [{q:'Combien d\'assurance locataire ai-je besoin?',a:'Estimez la valeur totale de tous vos biens.'},{q:'Que couvre l\'assurance locataire?',a:'Biens personnels, responsabilite civile, frais de relogement et frais medicaux.'},{q:'L\'assurance locataire en vaut-elle la peine?',a:'A 15-30 euros/mois, c\'est tres abordable pour la protection offerte.'},{q:'Mon proprietaire peut-il l\'exiger?',a:'Oui, de nombreux proprietaires l\'exigent comme condition du bail.'}] },
  de: { title: 'Mieterversicherungsrechner', paragraphs: ['Die Mieterversicherung schuetzt Ihr persoenliches Eigentum und bietet Haftpflichtschutz.', 'Dieser Rechner schaetzt Ihre Praemie basierend auf Eigentumswert, Selbstbeteiligung und Haftpflicht.', 'Sie deckt persoenliches Eigentum gegen Diebstahl, Brand und Vandalismus ab.', 'Nutzen Sie unseren <a href="/${lang}/tools/home-insurance-calculator">Wohngebaeudeversicherungsrechner</a>.'], faq: [{q:'Wie viel Mieterversicherung brauche ich?',a:'Schaetzen Sie den Gesamtwert all Ihrer Besitztumer.'},{q:'Was deckt die Mieterversicherung?',a:'Persoenliches Eigentum, Haftpflicht, Umzugskosten und medizinische Kosten.'},{q:'Lohnt sich die Mieterversicherung?',a:'Fuer 15-30 Euro/Monat ist sie sehr guenstig fuer den gebotenen Schutz.'},{q:'Kann mein Vermieter sie verlangen?',a:'Ja, viele Vermieter verlangen sie als Mietbedingung.'}] },
  pt: { title: 'Calculadora Seguro de Inquilino', paragraphs: ['O seguro de inquilino protege seus pertences pessoais e oferece cobertura de responsabilidade civil.', 'Esta calculadora estima seu premio com base no valor dos bens, franquia e cobertura de responsabilidade.', 'Cobre bens pessoais contra roubo, incendio e vandalismo.', 'Consulte nossa <a href="/${lang}/tools/home-insurance-calculator">calculadora seguro residencial</a>.'], faq: [{q:'Quanto seguro de inquilino eu preciso?',a:'Estime o valor total de todos os seus pertences.'},{q:'O que o seguro de inquilino cobre?',a:'Bens pessoais, responsabilidade civil, despesas de moradia e despesas medicas.'},{q:'O seguro de inquilino vale a pena?',a:'A R$15-30/mes, e muito acessivel para a protecao oferecida.'},{q:'Meu proprietario pode exigi-lo?',a:'Sim, muitos proprietarios o exigem como condicao do contrato.'}] },
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="renters-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
