'use client';
import { useParams } from 'next/navigation';
import { type Locale } from '@/lib/translations';

const content: Record<Locale, { title: string; lastUpdated: string; sections: { heading: string; body: string }[] }> = {
  en: {
    title: 'Disclaimer',
    lastUpdated: 'Last updated: March 2026',
    sections: [
      {
        heading: 'General Information',
        body: 'The information provided by ToolKit Online ("we", "us", or "our") on toolkitonline.vip (the "Site") is for general informational and educational purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.',
      },
      {
        heading: 'Not Professional Advice',
        body: 'The Site provides free online tools for calculation, conversion, text processing, and other utility purposes. The results generated by our tools should not be considered as professional advice. Specifically: financial calculators (such as VAT calculator, loan calculator, mortgage calculator, salary calculator, tax calculators, insurance calculators) are for estimation purposes only and do not constitute financial, tax, or investment advice; health calculators (such as BMI calculator, calorie calculator, body fat calculator) are for informational purposes only and do not constitute medical advice; any results should be verified independently before making important decisions.',
      },
      {
        heading: 'No Liability for Tool Results',
        body: 'While we strive to provide accurate calculations and conversions, we cannot guarantee that the results produced by our tools are error-free. All tools run entirely in your browser and the calculations are performed client-side. We shall not be held liable for any losses, damages, or negative consequences arising from the use of or reliance on any information or results provided by our tools. Users are advised to consult qualified professionals for financial, legal, medical, or other specialized matters.',
      },
      {
        heading: 'External Links',
        body: 'The Site may contain links to external websites or third-party services that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.',
      },
      {
        heading: 'Affiliate Disclosure',
        body: 'Some pages on our Site may contain affiliate links. This means that if you click on a link and make a purchase, we may receive a small commission at no additional cost to you. This helps support the maintenance and development of our free tools. Our editorial content is not influenced by affiliate partnerships, and we only recommend products or services that we believe provide value to our users.',
      },
      {
        heading: 'Advertisements',
        body: 'We display advertisements on our Site through Google AdSense and other advertising networks. These ads are served by third parties and may use cookies to display relevant advertisements. The presence of advertisements does not constitute an endorsement of the advertised products or services. Please refer to our Privacy Policy for more information about how advertising cookies are managed.',
      },
      {
        heading: 'Accuracy of Information',
        body: 'We make every effort to ensure that the information on our Site is accurate and up-to-date. However, we cannot guarantee that all content is free from errors or omissions. Information may change without notice. We reserve the right to modify, update, or remove content at any time without prior notice.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'To the fullest extent permitted by applicable law, ToolKit Online and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Site or any of its tools.',
      },
      {
        heading: 'Changes to This Disclaimer',
        body: 'We reserve the right to update or modify this Disclaimer at any time. Any changes will be posted on this page with an updated revision date. Your continued use of the Site after any changes constitutes acceptance of the updated Disclaimer.',
      },
      {
        heading: 'Contact Us',
        body: 'If you have any questions about this Disclaimer, please contact us at info@toolkitonline.vip.',
      },
    ],
  },
  it: {
    title: 'Disclaimer',
    lastUpdated: 'Ultimo aggiornamento: Marzo 2026',
    sections: [
      {
        heading: 'Informazioni Generali',
        body: 'Le informazioni fornite da ToolKit Online ("noi") su toolkitonline.vip (il "Sito") sono esclusivamente a scopo informativo e didattico. Tutte le informazioni sul Sito sono fornite in buona fede; tuttavia, non forniamo alcuna dichiarazione o garanzia di alcun tipo, espressa o implicita, riguardo all\'accuratezza, adeguatezza, validita, affidabilita, disponibilita o completezza di qualsiasi informazione sul Sito.',
      },
      {
        heading: 'Non Costituisce Consulenza Professionale',
        body: 'Il Sito fornisce strumenti online gratuiti per calcoli, conversioni, elaborazione testi e altri scopi utilitari. I risultati generati dai nostri strumenti non devono essere considerati come consulenza professionale. In particolare: i calcolatori finanziari (come calcolatore IVA, prestiti, mutui, stipendi, tasse, assicurazioni) sono solo a scopo di stima e non costituiscono consulenza finanziaria, fiscale o di investimento; i calcolatori per la salute (come calcolatore BMI, calorie, grasso corporeo) sono solo a scopo informativo e non costituiscono consulenza medica; qualsiasi risultato dovrebbe essere verificato indipendentemente prima di prendere decisioni importanti.',
      },
      {
        heading: 'Nessuna Responsabilita per i Risultati degli Strumenti',
        body: 'Pur cercando di fornire calcoli e conversioni accurati, non possiamo garantire che i risultati prodotti dai nostri strumenti siano privi di errori. Tutti gli strumenti funzionano interamente nel tuo browser e i calcoli vengono eseguiti lato client. Non saremo ritenuti responsabili per eventuali perdite, danni o conseguenze negative derivanti dall\'uso o dall\'affidamento su qualsiasi informazione o risultato fornito dai nostri strumenti.',
      },
      {
        heading: 'Link Esterni',
        body: 'Il Sito puo contenere link a siti web esterni o servizi di terze parti che non sono forniti o gestiti da noi. Non garantiamo l\'accuratezza, la pertinenza, la tempestivita o la completezza delle informazioni su questi siti web esterni.',
      },
      {
        heading: 'Divulgazione Affiliazione',
        body: 'Alcune pagine del nostro Sito possono contenere link di affiliazione. Cio significa che se fai clic su un link e effettui un acquisto, potremmo ricevere una piccola commissione senza alcun costo aggiuntivo per te. Questo aiuta a sostenere la manutenzione e lo sviluppo dei nostri strumenti gratuiti.',
      },
      {
        heading: 'Pubblicita',
        body: 'Visualizziamo pubblicita sul nostro Sito tramite Google AdSense e altre reti pubblicitarie. Questi annunci sono forniti da terze parti e possono utilizzare cookie per visualizzare pubblicita pertinenti. La presenza di pubblicita non costituisce un\'approvazione dei prodotti o servizi pubblicizzati.',
      },
      {
        heading: 'Accuratezza delle Informazioni',
        body: 'Facciamo ogni sforzo per garantire che le informazioni sul nostro Sito siano accurate e aggiornate. Tuttavia, non possiamo garantire che tutti i contenuti siano privi di errori o omissioni.',
      },
      {
        heading: 'Limitazione di Responsabilita',
        body: 'Nella misura massima consentita dalla legge applicabile, ToolKit Online e i suoi operatori non saranno responsabili per danni indiretti, incidentali, speciali, consequenziali o punitivi, o per qualsiasi perdita di profitti o ricavi.',
      },
      {
        heading: 'Modifiche a Questo Disclaimer',
        body: 'Ci riserviamo il diritto di aggiornare o modificare questo Disclaimer in qualsiasi momento. Eventuali modifiche saranno pubblicate su questa pagina con una data di revisione aggiornata.',
      },
      {
        heading: 'Contattaci',
        body: 'Per qualsiasi domanda su questo Disclaimer, contattaci all\'indirizzo info@toolkitonline.vip.',
      },
    ],
  },
  es: {
    title: 'Aviso Legal',
    lastUpdated: 'Ultima actualizacion: Marzo 2026',
    sections: [
      {
        heading: 'Informacion General',
        body: 'La informacion proporcionada por ToolKit Online ("nosotros") en toolkitonline.vip (el "Sitio") es solo con fines informativos y educativos generales. Toda la informacion en el Sitio se proporciona de buena fe; sin embargo, no hacemos ninguna representacion o garantia de ningun tipo, expresa o implicita, con respecto a la precision, adecuacion, validez, fiabilidad, disponibilidad o integridad de cualquier informacion en el Sitio.',
      },
      {
        heading: 'No Constituye Asesoramiento Profesional',
        body: 'El Sitio proporciona herramientas en linea gratuitas para calculos, conversiones, procesamiento de texto y otros propositos utilitarios. Los resultados generados por nuestras herramientas no deben considerarse como asesoramiento profesional. En particular: las calculadoras financieras (como calculadora de IVA, prestamos, hipotecas, salarios, impuestos, seguros) son solo para fines de estimacion y no constituyen asesoramiento financiero, fiscal o de inversion; las calculadoras de salud (como calculadora de IMC, calorias, grasa corporal) son solo para fines informativos y no constituyen asesoramiento medico.',
      },
      {
        heading: 'Sin Responsabilidad por Resultados de Herramientas',
        body: 'Aunque nos esforzamos por proporcionar calculos y conversiones precisos, no podemos garantizar que los resultados producidos por nuestras herramientas esten libres de errores. Todas las herramientas funcionan completamente en su navegador. No seremos responsables de perdidas, danos o consecuencias negativas derivadas del uso de nuestras herramientas.',
      },
      {
        heading: 'Enlaces Externos',
        body: 'El Sitio puede contener enlaces a sitios web externos o servicios de terceros que no son proporcionados ni mantenidos por nosotros. No garantizamos la precision, relevancia u oportunidad de la informacion en estos sitios web externos.',
      },
      {
        heading: 'Divulgacion de Afiliados',
        body: 'Algunas paginas de nuestro Sitio pueden contener enlaces de afiliados. Esto significa que si hace clic en un enlace y realiza una compra, podemos recibir una pequena comision sin costo adicional para usted.',
      },
      {
        heading: 'Publicidad',
        body: 'Mostramos anuncios en nuestro Sitio a traves de Google AdSense y otras redes publicitarias. La presencia de anuncios no constituye una aprobacion de los productos o servicios anunciados.',
      },
      {
        heading: 'Limitacion de Responsabilidad',
        body: 'En la medida maxima permitida por la ley aplicable, ToolKit Online y sus operadores no seran responsables de danos indirectos, incidentales, especiales, consecuentes o punitivos.',
      },
      {
        heading: 'Cambios a Este Aviso Legal',
        body: 'Nos reservamos el derecho de actualizar o modificar este Aviso Legal en cualquier momento. Los cambios se publicaran en esta pagina con una fecha de revision actualizada.',
      },
      {
        heading: 'Contactenos',
        body: 'Si tiene preguntas sobre este Aviso Legal, contactenos en info@toolkitonline.vip.',
      },
    ],
  },
  fr: {
    title: 'Avertissement',
    lastUpdated: 'Derniere mise a jour : Mars 2026',
    sections: [
      {
        heading: 'Informations Generales',
        body: 'Les informations fournies par ToolKit Online ("nous") sur toolkitonline.vip (le "Site") sont uniquement a des fins d\'information generale et educative. Toutes les informations du Site sont fournies de bonne foi ; cependant, nous ne faisons aucune declaration ou garantie d\'aucune sorte concernant l\'exactitude, l\'adequation, la validite, la fiabilite, la disponibilite ou l\'exhaustivite des informations du Site.',
      },
      {
        heading: 'Ne Constitue Pas un Conseil Professionnel',
        body: 'Le Site fournit des outils en ligne gratuits pour les calculs, conversions, traitement de texte et autres fins utilitaires. Les resultats generes par nos outils ne doivent pas etre consideres comme des conseils professionnels. En particulier : les calculatrices financieres sont uniquement a des fins d\'estimation et ne constituent pas des conseils financiers, fiscaux ou d\'investissement ; les calculatrices de sante sont uniquement a des fins informatives et ne constituent pas des conseils medicaux.',
      },
      {
        heading: 'Aucune Responsabilite pour les Resultats des Outils',
        body: 'Bien que nous nous efforcions de fournir des calculs et conversions precis, nous ne pouvons pas garantir que les resultats produits par nos outils soient exempts d\'erreurs. Tous les outils fonctionnent entierement dans votre navigateur.',
      },
      {
        heading: 'Liens Externes',
        body: 'Le Site peut contenir des liens vers des sites web externes ou des services tiers qui ne sont pas fournis ou maintenus par nous.',
      },
      {
        heading: 'Divulgation d\'Affiliation',
        body: 'Certaines pages de notre Site peuvent contenir des liens d\'affiliation. Cela signifie que si vous cliquez sur un lien et effectuez un achat, nous pouvons recevoir une petite commission sans frais supplementaires pour vous.',
      },
      {
        heading: 'Publicite',
        body: 'Nous affichons des publicites sur notre Site via Google AdSense et d\'autres reseaux publicitaires. La presence de publicites ne constitue pas une approbation des produits ou services annonces.',
      },
      {
        heading: 'Limitation de Responsabilite',
        body: 'Dans la mesure maximale permise par la loi applicable, ToolKit Online et ses operateurs ne seront pas responsables des dommages indirects, accessoires, speciaux, consecutifs ou punitifs.',
      },
      {
        heading: 'Modifications de cet Avertissement',
        body: 'Nous nous reservons le droit de mettre a jour ou de modifier cet Avertissement a tout moment. Les modifications seront publiees sur cette page avec une date de revision mise a jour.',
      },
      {
        heading: 'Contactez-nous',
        body: 'Si vous avez des questions sur cet Avertissement, contactez-nous a info@toolkitonline.vip.',
      },
    ],
  },
  de: {
    title: 'Haftungsausschluss',
    lastUpdated: 'Letzte Aktualisierung: Maerz 2026',
    sections: [
      {
        heading: 'Allgemeine Informationen',
        body: 'Die von ToolKit Online ("wir") auf toolkitonline.vip (die "Website") bereitgestellten Informationen dienen ausschliesslich allgemeinen Informations- und Bildungszwecken. Alle Informationen auf der Website werden in gutem Glauben bereitgestellt; wir geben jedoch keinerlei ausdrueckliche oder stillschweigende Zusicherungen oder Gewaehrleistungen hinsichtlich der Genauigkeit, Angemessenheit, Gueltigkeit, Zuverlaessigkeit, Verfuegbarkeit oder Vollstaendigkeit der Informationen.',
      },
      {
        heading: 'Keine Professionelle Beratung',
        body: 'Die Website bietet kostenlose Online-Tools fuer Berechnungen, Umrechnungen, Textverarbeitung und andere Zwecke. Die von unseren Tools generierten Ergebnisse sollten nicht als professionelle Beratung betrachtet werden. Insbesondere: Finanzrechner dienen nur zu Schaetzungszwecken und stellen keine Finanz-, Steuer- oder Anlageberatung dar; Gesundheitsrechner dienen nur zu Informationszwecken und stellen keine medizinische Beratung dar.',
      },
      {
        heading: 'Keine Haftung fuer Tool-Ergebnisse',
        body: 'Obwohl wir bestrebt sind, genaue Berechnungen und Umrechnungen bereitzustellen, koennen wir nicht garantieren, dass die von unseren Tools erzeugten Ergebnisse fehlerfrei sind. Alle Tools laufen vollstaendig in Ihrem Browser.',
      },
      {
        heading: 'Externe Links',
        body: 'Die Website kann Links zu externen Websites oder Diensten Dritter enthalten, die nicht von uns bereitgestellt oder gepflegt werden.',
      },
      {
        heading: 'Affiliate-Offenlegung',
        body: 'Einige Seiten unserer Website koennen Affiliate-Links enthalten. Das bedeutet, dass wir moeglicherweise eine kleine Provision erhalten, wenn Sie auf einen Link klicken und einen Kauf taetigen, ohne zusaetzliche Kosten fuer Sie.',
      },
      {
        heading: 'Werbung',
        body: 'Wir zeigen Werbung auf unserer Website ueber Google AdSense und andere Werbenetzwerke an. Das Vorhandensein von Werbung stellt keine Billigung der beworbenen Produkte oder Dienstleistungen dar.',
      },
      {
        heading: 'Haftungsbeschraenkung',
        body: 'Im maximal gesetzlich zulaessigen Umfang haften ToolKit Online und seine Betreiber nicht fuer indirekte, zufaellige, besondere, Folge- oder Strafschaeden.',
      },
      {
        heading: 'Aenderungen dieses Haftungsausschlusses',
        body: 'Wir behalten uns das Recht vor, diesen Haftungsausschluss jederzeit zu aktualisieren oder zu aendern. Aenderungen werden auf dieser Seite mit einem aktualisierten Revisionsdatum veroeffentlicht.',
      },
      {
        heading: 'Kontakt',
        body: 'Bei Fragen zu diesem Haftungsausschluss kontaktieren Sie uns unter info@toolkitonline.vip.',
      },
    ],
  },
  pt: {
    title: 'Aviso Legal',
    lastUpdated: 'Ultima atualizacao: Marco 2026',
    sections: [
      {
        heading: 'Informacoes Gerais',
        body: 'As informacoes fornecidas pela ToolKit Online ("nos") em toolkitonline.vip (o "Site") sao apenas para fins informativos e educacionais gerais. Todas as informacoes no Site sao fornecidas de boa fe; no entanto, nao fazemos nenhuma representacao ou garantia de qualquer tipo sobre a precisao, adequacao, validade, confiabilidade, disponibilidade ou completude de qualquer informacao no Site.',
      },
      {
        heading: 'Nao Constitui Aconselhamento Profissional',
        body: 'O Site fornece ferramentas online gratuitas para calculos, conversoes, processamento de texto e outros fins utilitarios. Os resultados gerados pelas nossas ferramentas nao devem ser considerados como aconselhamento profissional. Em particular: calculadoras financeiras sao apenas para fins de estimativa e nao constituem aconselhamento financeiro, fiscal ou de investimento; calculadoras de saude sao apenas para fins informativos e nao constituem aconselhamento medico.',
      },
      {
        heading: 'Sem Responsabilidade por Resultados das Ferramentas',
        body: 'Embora nos esforcemos para fornecer calculos e conversoes precisos, nao podemos garantir que os resultados produzidos pelas nossas ferramentas estejam livres de erros. Todas as ferramentas funcionam inteiramente no seu navegador.',
      },
      {
        heading: 'Links Externos',
        body: 'O Site pode conter links para sites externos ou servicos de terceiros que nao sao fornecidos ou mantidos por nos.',
      },
      {
        heading: 'Divulgacao de Afiliados',
        body: 'Algumas paginas do nosso Site podem conter links de afiliados. Isso significa que se voce clicar em um link e fizer uma compra, podemos receber uma pequena comissao sem custo adicional para voce.',
      },
      {
        heading: 'Publicidade',
        body: 'Exibimos anuncios em nosso Site atraves do Google AdSense e outras redes de publicidade. A presenca de anuncios nao constitui uma aprovacao dos produtos ou servicos anunciados.',
      },
      {
        heading: 'Limitacao de Responsabilidade',
        body: 'Na extensao maxima permitida pela lei aplicavel, a ToolKit Online e seus operadores nao serao responsaveis por danos indiretos, incidentais, especiais, consequenciais ou punitivos.',
      },
      {
        heading: 'Alteracoes a Este Aviso Legal',
        body: 'Reservamo-nos o direito de atualizar ou modificar este Aviso Legal a qualquer momento. As alteracoes serao publicadas nesta pagina com uma data de revisao atualizada.',
      },
      {
        heading: 'Contate-nos',
        body: 'Se tiver alguma duvida sobre este Aviso Legal, entre em contato conosco em info@toolkitonline.vip.',
      },
    ],
  },
};

export default function DisclaimerPage() {
  const params = useParams();
  const lang = (params?.lang as Locale) || 'en';
  const c = content[lang];

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <article className="prose prose-lg max-w-none">
        <h1 className="text-3xl font-bold mb-2">{c.title}</h1>
        <p className="text-sm text-gray-500 mb-8">{c.lastUpdated}</p>
        {c.sections.map((section, i) => (
          <div key={i} className="mb-6">
            <h2 className="text-xl font-semibold mb-2">{section.heading}</h2>
            <p className="text-gray-700 leading-relaxed">{section.body}</p>
          </div>
        ))}
      </article>
    </div>
  );
}
