'use client';
import { useParams } from 'next/navigation';
import { type Locale } from '@/lib/translations';

const content: Record<Locale, { title: string; lastUpdated: string; sections: { heading: string; body: string }[] }> = {
  en: {
    title: 'Disclaimer',
    lastUpdated: 'Last updated: March 2026',
    sections: [
      {
        heading: 'General Disclaimer',
        body: 'The information provided by ToolKit Online ("we," "us," or "our") on toolkitonline.vip (the "Website") is for general informational and educational purposes only. All results generated by our tools are estimates and approximations. They should not be considered as professional advice of any kind. While we strive to provide useful and accurate tools, the results produced by our calculators, converters, and other utilities are intended to serve as general guidance only. You should not rely solely on these results to make important personal, financial, medical, or legal decisions. We strongly recommend consulting with qualified professionals before taking any action based on the information or results provided by our tools.',
      },
      {
        heading: 'Financial Tools Disclaimer',
        body: 'Our financial tools — including but not limited to the VAT Calculator, Loan Calculator, Mortgage Calculator, Investment Calculator, Compound Interest Calculator, Salary Calculator, Profit Margin Calculator, ROI Calculator, Retirement Calculator, and Debt Payoff Calculator — are provided for informational and educational purposes only. The results generated by these tools do not constitute financial advice, investment advice, tax advice, or any other form of professional financial guidance. Financial calculations are based on simplified models and may not account for all variables, fees, taxes, market conditions, or regulations that apply to your specific situation. Interest rates, tax rates, and other financial parameters used in calculations may not reflect current market conditions. Always consult a licensed financial advisor, accountant, or tax professional before making financial decisions. We are not responsible for any financial losses or damages resulting from the use of our tools.',
      },
      {
        heading: 'Health Tools Disclaimer',
        body: 'Our health-related tools — including but not limited to the BMI Calculator, Calorie Calculator, Body Fat Calculator, Ideal Weight Calculator, Water Intake Calculator, Sleep Calculator, Pregnancy Calculator, and Pace Calculator — are provided for informational and educational purposes only. The results generated by these tools do not constitute medical advice, diagnosis, or treatment recommendations. Health calculations are based on general formulas and population averages that may not be appropriate for your individual circumstances, medical history, or health conditions. BMI, body fat percentages, calorie needs, and other health metrics have inherent limitations and should be interpreted in the context of a comprehensive health assessment. Always consult a qualified healthcare professional, physician, or registered dietitian before making decisions about your health, diet, exercise routine, or medical treatment. Never disregard professional medical advice or delay seeking it because of something you have read or calculated on this Website.',
      },
      {
        heading: 'Calculator Accuracy',
        body: 'We make every effort to ensure that our calculators and tools produce accurate results. However, we cannot guarantee that all calculations are free from errors or that the results will be completely accurate in every situation. Our tools use standard mathematical formulas and algorithms, but real-world scenarios may involve additional variables, exceptions, or complexities that our tools cannot fully account for. Rounding, floating-point arithmetic, and other computational factors may cause minor discrepancies in results. We regularly review and update our tools, but errors may occasionally occur. If you notice any inaccuracy in our tools, please contact us at info@toolkitonline.vip so we can investigate and correct the issue promptly.',
      },
      {
        heading: 'Third-Party Links',
        body: 'Our Website may contain links to third-party websites, services, or resources that are not owned or controlled by ToolKit Online. We have no control over, and assume no responsibility for, the content, privacy policies, practices, or availability of any third-party websites or services. The inclusion of any link does not imply endorsement, recommendation, or approval by ToolKit Online. You acknowledge and agree that we are not responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods, or services available on or through any third-party websites.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'To the fullest extent permitted by applicable law, ToolKit Online and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from: (a) your access to or use of, or inability to access or use, the Website or any tools; (b) any errors, inaccuracies, or omissions in the content, results, or calculations provided by our tools; (c) any unauthorized access to or use of our servers or any personal information stored therein; (d) any interruption or cessation of transmission to or from the Website; or (e) any decision or action taken in reliance on the information provided by our tools. You use our tools and rely on their results entirely at your own risk.',
      },
      {
        heading: 'No Professional Relationship',
        body: 'Use of this Website and its tools does not create any professional-client relationship between you and ToolKit Online. We do not provide financial advisory, medical, legal, accounting, or any other type of professional services. The tools and information on this Website are not a substitute for professional advice tailored to your individual needs and circumstances.',
      },
      {
        heading: 'Changes to This Disclaimer',
        body: 'We reserve the right to modify or update this Disclaimer at any time without prior notice. Changes will be effective immediately upon posting on this page with an updated revision date. Your continued use of the Website after any changes constitutes your acceptance of the revised Disclaimer. We encourage you to review this page periodically to stay informed about any updates.',
      },
      {
        heading: 'Contact Us',
        body: 'If you have any questions or concerns about this Disclaimer, please contact us at info@toolkitonline.vip.',
      },
    ],
  },
  it: {
    title: 'Disclaimer',
    lastUpdated: 'Ultimo aggiornamento: Marzo 2026',
    sections: [
      {
        heading: 'Disclaimer Generale',
        body: 'Le informazioni fornite da ToolKit Online ("noi" o "nostro") sul sito toolkitonline.vip (il "Sito Web") sono esclusivamente a scopo informativo e didattico. Tutti i risultati generati dai nostri strumenti sono stime e approssimazioni. Non devono essere considerati come consulenza professionale di alcun tipo. Sebbene ci sforziamo di fornire strumenti utili e accurati, i risultati prodotti dai nostri calcolatori, convertitori e altre utilita sono intesi solo come guida generale. Non dovresti affidarti esclusivamente a questi risultati per prendere decisioni importanti a livello personale, finanziario, medico o legale. Raccomandiamo vivamente di consultare professionisti qualificati prima di intraprendere qualsiasi azione basata sulle informazioni o sui risultati forniti dai nostri strumenti.',
      },
      {
        heading: 'Disclaimer Strumenti Finanziari',
        body: 'I nostri strumenti finanziari — inclusi, a titolo esemplificativo, il Calcolatore IVA, il Calcolatore Prestiti, il Calcolatore Mutuo, il Calcolatore Investimenti, il Calcolatore Interesse Composto, il Calcolatore Stipendio, il Calcolatore Margine di Profitto, il Calcolatore ROI, il Calcolatore Pensione e il Calcolatore Estinzione Debiti — sono forniti esclusivamente a scopo informativo e didattico. I risultati generati da questi strumenti non costituiscono consulenza finanziaria, consulenza sugli investimenti, consulenza fiscale o qualsiasi altra forma di orientamento finanziario professionale. I calcoli finanziari si basano su modelli semplificati e potrebbero non tenere conto di tutte le variabili, commissioni, tasse, condizioni di mercato o normative applicabili alla tua situazione specifica. I tassi di interesse, le aliquote fiscali e altri parametri finanziari utilizzati nei calcoli potrebbero non riflettere le condizioni attuali del mercato. Consulta sempre un consulente finanziario abilitato, un commercialista o un professionista fiscale prima di prendere decisioni finanziarie. Non siamo responsabili per eventuali perdite finanziarie o danni derivanti dall\'uso dei nostri strumenti.',
      },
      {
        heading: 'Disclaimer Strumenti per la Salute',
        body: 'I nostri strumenti relativi alla salute — inclusi, a titolo esemplificativo, il Calcolatore BMI, il Calcolatore Calorie, il Calcolatore Grasso Corporeo, il Calcolatore Peso Ideale, il Calcolatore Assunzione Acqua, il Calcolatore Sonno, il Calcolatore Gravidanza e il Calcolatore Ritmo — sono forniti esclusivamente a scopo informativo e didattico. I risultati generati da questi strumenti non costituiscono consulenza medica, diagnosi o raccomandazioni terapeutiche. I calcoli sanitari si basano su formule generali e medie della popolazione che potrebbero non essere appropriate per le tue circostanze individuali, la tua storia clinica o le tue condizioni di salute. BMI, percentuali di grasso corporeo, fabbisogno calorico e altre metriche sanitarie hanno limiti intrinseci e devono essere interpretati nel contesto di una valutazione sanitaria completa. Consulta sempre un professionista sanitario qualificato, un medico o un dietista registrato prima di prendere decisioni sulla tua salute, dieta, routine di esercizio o trattamento medico. Non ignorare mai il consiglio medico professionale o ritardare la sua ricerca a causa di qualcosa che hai letto o calcolato su questo Sito Web.',
      },
      {
        heading: 'Accuratezza dei Calcolatori',
        body: 'Facciamo ogni sforzo per garantire che i nostri calcolatori e strumenti producano risultati accurati. Tuttavia, non possiamo garantire che tutti i calcoli siano privi di errori o che i risultati saranno completamente accurati in ogni situazione. I nostri strumenti utilizzano formule matematiche e algoritmi standard, ma gli scenari reali possono coinvolgere variabili aggiuntive, eccezioni o complessita che i nostri strumenti non possono tenere pienamente in considerazione. Arrotondamenti, aritmetica in virgola mobile e altri fattori computazionali possono causare piccole discrepanze nei risultati. Esaminiamo e aggiorniamo regolarmente i nostri strumenti, ma occasionalmente possono verificarsi errori. Se noti qualche imprecisione nei nostri strumenti, contattaci a info@toolkitonline.vip in modo da poter indagare e correggere il problema tempestivamente.',
      },
      {
        heading: 'Link a Terze Parti',
        body: 'Il nostro Sito Web puo contenere link a siti web, servizi o risorse di terze parti che non sono di proprieta o controllati da ToolKit Online. Non abbiamo alcun controllo e non ci assumiamo alcuna responsabilita per il contenuto, le politiche sulla privacy, le pratiche o la disponibilita di siti web o servizi di terze parti. L\'inclusione di qualsiasi link non implica approvazione, raccomandazione o supporto da parte di ToolKit Online. Riconosci e accetti che non siamo responsabili, direttamente o indirettamente, per qualsiasi danno o perdita causati o presumibilmente causati dall\'uso o dalla dipendenza da contenuti, beni o servizi disponibili su o attraverso siti web di terze parti.',
      },
      {
        heading: 'Limitazione di Responsabilita',
        body: 'Nella misura massima consentita dalla legge applicabile, ToolKit Online e i suoi operatori non saranno responsabili per danni diretti, indiretti, incidentali, speciali, consequenziali o punitivi, inclusi, a titolo esemplificativo, perdita di profitti, dati, uso, avviamento o altre perdite intangibili, derivanti da: (a) il tuo accesso o utilizzo, o l\'impossibilita di accedere o utilizzare, il Sito Web o qualsiasi strumento; (b) errori, imprecisioni o omissioni nei contenuti, risultati o calcoli forniti dai nostri strumenti; (c) qualsiasi accesso non autorizzato ai nostri server o alle informazioni personali ivi memorizzate; (d) qualsiasi interruzione o cessazione della trasmissione da o verso il Sito Web; o (e) qualsiasi decisione o azione intrapresa in base alle informazioni fornite dai nostri strumenti. Utilizzi i nostri strumenti e ti affidi ai loro risultati interamente a tuo rischio e pericolo.',
      },
      {
        heading: 'Nessun Rapporto Professionale',
        body: 'L\'uso di questo Sito Web e dei suoi strumenti non crea alcun rapporto professionale-cliente tra te e ToolKit Online. Non forniamo servizi di consulenza finanziaria, medica, legale, contabile o di qualsiasi altro tipo professionale. Gli strumenti e le informazioni su questo Sito Web non sostituiscono la consulenza professionale personalizzata per le tue esigenze e circostanze individuali.',
      },
      {
        heading: 'Modifiche a Questo Disclaimer',
        body: 'Ci riserviamo il diritto di modificare o aggiornare questo Disclaimer in qualsiasi momento senza preavviso. Le modifiche saranno effettive immediatamente dopo la pubblicazione su questa pagina con una data di revisione aggiornata. Il tuo uso continuato del Sito Web dopo qualsiasi modifica costituisce la tua accettazione del Disclaimer modificato. Ti incoraggiamo a consultare periodicamente questa pagina per rimanere informato su eventuali aggiornamenti.',
      },
      {
        heading: 'Contattaci',
        body: 'Per qualsiasi domanda o dubbio riguardo questo Disclaimer, contattaci a info@toolkitonline.vip.',
      },
    ],
  },
  es: {
    title: 'Aviso Legal',
    lastUpdated: 'Ultima actualizacion: Marzo 2026',
    sections: [
      {
        heading: 'Aviso Legal General',
        body: 'La informacion proporcionada por ToolKit Online ("nosotros" o "nuestro") en toolkitonline.vip (el "Sitio Web") es unicamente con fines informativos y educativos. Todos los resultados generados por nuestras herramientas son estimaciones y aproximaciones. No deben considerarse como asesoramiento profesional de ningun tipo. Aunque nos esforzamos por proporcionar herramientas utiles y precisas, los resultados producidos por nuestras calculadoras, convertidores y otras utilidades estan destinados a servir solo como orientacion general. No debes confiar unicamente en estos resultados para tomar decisiones importantes a nivel personal, financiero, medico o legal. Recomendamos encarecidamente consultar con profesionales cualificados antes de tomar cualquier accion basada en la informacion o los resultados proporcionados por nuestras herramientas.',
      },
      {
        heading: 'Aviso Legal de Herramientas Financieras',
        body: 'Nuestras herramientas financieras — incluyendo, entre otras, la Calculadora de IVA, la Calculadora de Prestamos, la Calculadora de Hipoteca, la Calculadora de Inversiones, la Calculadora de Interes Compuesto, la Calculadora de Salario, la Calculadora de Margen de Beneficio, la Calculadora de ROI, la Calculadora de Jubilacion y la Calculadora de Liquidacion de Deudas — se proporcionan exclusivamente con fines informativos y educativos. Los resultados generados por estas herramientas no constituyen asesoramiento financiero, asesoramiento de inversiones, asesoramiento fiscal ni ninguna otra forma de orientacion financiera profesional. Los calculos financieros se basan en modelos simplificados y pueden no tener en cuenta todas las variables, comisiones, impuestos, condiciones del mercado o regulaciones que se aplican a tu situacion especifica. Los tipos de interes, las tasas impositivas y otros parametros financieros utilizados en los calculos pueden no reflejar las condiciones actuales del mercado. Consulta siempre a un asesor financiero autorizado, un contable o un profesional fiscal antes de tomar decisiones financieras. No somos responsables de ninguna perdida financiera o dano resultante del uso de nuestras herramientas.',
      },
      {
        heading: 'Aviso Legal de Herramientas de Salud',
        body: 'Nuestras herramientas relacionadas con la salud — incluyendo, entre otras, la Calculadora de IMC, la Calculadora de Calorias, la Calculadora de Grasa Corporal, la Calculadora de Peso Ideal, la Calculadora de Ingesta de Agua, la Calculadora de Sueno, la Calculadora de Embarazo y la Calculadora de Ritmo — se proporcionan exclusivamente con fines informativos y educativos. Los resultados generados por estas herramientas no constituyen asesoramiento medico, diagnostico ni recomendaciones de tratamiento. Los calculos de salud se basan en formulas generales y promedios de poblacion que pueden no ser apropiados para tus circunstancias individuales, historial medico o condiciones de salud. El IMC, los porcentajes de grasa corporal, las necesidades caloricas y otras metricas de salud tienen limitaciones inherentes y deben interpretarse en el contexto de una evaluacion de salud integral. Consulta siempre a un profesional de la salud cualificado, un medico o un dietista registrado antes de tomar decisiones sobre tu salud, dieta, rutina de ejercicio o tratamiento medico. Nunca ignores el consejo medico profesional ni retrases su busqueda por algo que hayas leido o calculado en este Sitio Web.',
      },
      {
        heading: 'Precision de las Calculadoras',
        body: 'Hacemos todo lo posible para garantizar que nuestras calculadoras y herramientas produzcan resultados precisos. Sin embargo, no podemos garantizar que todos los calculos esten libres de errores o que los resultados sean completamente exactos en todas las situaciones. Nuestras herramientas utilizan formulas matematicas y algoritmos estandar, pero los escenarios del mundo real pueden involucrar variables adicionales, excepciones o complejidades que nuestras herramientas no pueden considerar completamente. El redondeo, la aritmetica de punto flotante y otros factores computacionales pueden causar pequenas discrepancias en los resultados. Revisamos y actualizamos regularmente nuestras herramientas, pero ocasionalmente pueden ocurrir errores. Si notas alguna imprecision en nuestras herramientas, contactanos en info@toolkitonline.vip para que podamos investigar y corregir el problema rapidamente.',
      },
      {
        heading: 'Enlaces a Terceros',
        body: 'Nuestro Sitio Web puede contener enlaces a sitios web, servicios o recursos de terceros que no son propiedad ni estan controlados por ToolKit Online. No tenemos control y no asumimos responsabilidad por el contenido, las politicas de privacidad, las practicas o la disponibilidad de sitios web o servicios de terceros. La inclusion de cualquier enlace no implica aprobacion, recomendacion o respaldo por parte de ToolKit Online. Reconoces y aceptas que no somos responsables, directa o indirectamente, de ningun dano o perdida causados por el uso o la dependencia de contenidos, bienes o servicios disponibles en sitios web de terceros.',
      },
      {
        heading: 'Limitacion de Responsabilidad',
        body: 'En la maxima medida permitida por la ley aplicable, ToolKit Online y sus operadores no seran responsables de ningun dano directo, indirecto, incidental, especial, consecuente o punitivo, incluyendo, entre otros, perdida de beneficios, datos, uso, fondo de comercio u otras perdidas intangibles, resultantes de: (a) tu acceso o uso, o la imposibilidad de acceder o usar, el Sitio Web o cualquier herramienta; (b) errores, imprecisiones u omisiones en el contenido, resultados o calculos proporcionados por nuestras herramientas; (c) cualquier acceso no autorizado a nuestros servidores o informacion personal almacenada en ellos; (d) cualquier interrupcion o cesacion de la transmision desde o hacia el Sitio Web; o (e) cualquier decision o accion tomada en base a la informacion proporcionada por nuestras herramientas. Utilizas nuestras herramientas y confias en sus resultados enteramente bajo tu propio riesgo.',
      },
      {
        heading: 'Sin Relacion Profesional',
        body: 'El uso de este Sitio Web y sus herramientas no crea ninguna relacion profesional-cliente entre tu y ToolKit Online. No proporcionamos servicios de asesoria financiera, medica, legal, contable o de ningun otro tipo profesional. Las herramientas e informacion en este Sitio Web no sustituyen el asesoramiento profesional adaptado a tus necesidades y circunstancias individuales.',
      },
      {
        heading: 'Cambios en Este Aviso Legal',
        body: 'Nos reservamos el derecho de modificar o actualizar este Aviso Legal en cualquier momento sin previo aviso. Los cambios seran efectivos inmediatamente despues de su publicacion en esta pagina con una fecha de revision actualizada. Tu uso continuado del Sitio Web despues de cualquier cambio constituye tu aceptacion del Aviso Legal revisado. Te animamos a revisar esta pagina periodicamente para estar informado sobre cualquier actualizacion.',
      },
      {
        heading: 'Contactanos',
        body: 'Si tienes alguna pregunta o inquietud sobre este Aviso Legal, contactanos en info@toolkitonline.vip.',
      },
    ],
  },
  fr: {
    title: 'Avis de Non-Responsabilite',
    lastUpdated: 'Derniere mise a jour : Mars 2026',
    sections: [
      {
        heading: 'Avis General',
        body: 'Les informations fournies par ToolKit Online ("nous" ou "notre") sur toolkitonline.vip (le "Site Web") sont uniquement a des fins informatives et educatives. Tous les resultats generes par nos outils sont des estimations et des approximations. Ils ne doivent pas etre consideres comme un conseil professionnel de quelque nature que ce soit. Bien que nous nous efforcions de fournir des outils utiles et precis, les resultats produits par nos calculateurs, convertisseurs et autres utilitaires sont destines a servir uniquement de guide general. Vous ne devez pas vous fier uniquement a ces resultats pour prendre des decisions importantes sur le plan personnel, financier, medical ou juridique. Nous recommandons vivement de consulter des professionnels qualifies avant d\'entreprendre toute action basee sur les informations ou les resultats fournis par nos outils.',
      },
      {
        heading: 'Avis Relatif aux Outils Financiers',
        body: 'Nos outils financiers — y compris, mais sans s\'y limiter, le Calculateur de TVA, le Calculateur de Pret, le Calculateur Hypothecaire, le Calculateur d\'Investissement, le Calculateur d\'Interet Compose, le Calculateur de Salaire, le Calculateur de Marge Beneficiaire, le Calculateur de ROI, le Calculateur de Retraite et le Calculateur de Remboursement de Dettes — sont fournis uniquement a des fins informatives et educatives. Les resultats generes par ces outils ne constituent pas un conseil financier, un conseil en investissement, un conseil fiscal ou toute autre forme d\'orientation financiere professionnelle. Les calculs financiers sont bases sur des modeles simplifies et peuvent ne pas tenir compte de toutes les variables, frais, taxes, conditions du marche ou reglementations applicables a votre situation specifique. Les taux d\'interet, les taux d\'imposition et autres parametres financiers utilises dans les calculs peuvent ne pas refleter les conditions actuelles du marche. Consultez toujours un conseiller financier agree, un comptable ou un professionnel fiscal avant de prendre des decisions financieres. Nous ne sommes pas responsables des pertes financieres ou des dommages resultant de l\'utilisation de nos outils.',
      },
      {
        heading: 'Avis Relatif aux Outils de Sante',
        body: 'Nos outils lies a la sante — y compris, mais sans s\'y limiter, le Calculateur d\'IMC, le Calculateur de Calories, le Calculateur de Masse Grasse, le Calculateur de Poids Ideal, le Calculateur d\'Apport en Eau, le Calculateur de Sommeil, le Calculateur de Grossesse et le Calculateur d\'Allure — sont fournis uniquement a des fins informatives et educatives. Les resultats generes par ces outils ne constituent pas un avis medical, un diagnostic ou des recommandations de traitement. Les calculs de sante sont bases sur des formules generales et des moyennes de population qui peuvent ne pas etre appropriees a vos circonstances individuelles, vos antecedents medicaux ou vos conditions de sante. L\'IMC, les pourcentages de masse grasse, les besoins caloriques et autres indicateurs de sante ont des limites inherentes et doivent etre interpretes dans le contexte d\'une evaluation de sante complete. Consultez toujours un professionnel de sante qualifie, un medecin ou un dieteticien diplome avant de prendre des decisions concernant votre sante, votre alimentation, votre routine d\'exercice ou votre traitement medical. Ne negligez jamais un avis medical professionnel et ne retardez pas sa recherche en raison de quelque chose que vous avez lu ou calcule sur ce Site Web.',
      },
      {
        heading: 'Precision des Calculateurs',
        body: 'Nous faisons tout notre possible pour garantir que nos calculateurs et outils produisent des resultats precis. Cependant, nous ne pouvons pas garantir que tous les calculs sont exempts d\'erreurs ou que les resultats seront totalement exacts dans chaque situation. Nos outils utilisent des formules mathematiques et des algorithmes standards, mais les scenarios reels peuvent impliquer des variables supplementaires, des exceptions ou des complexites que nos outils ne peuvent pas entierement prendre en compte. Les arrondis, l\'arithmetique en virgule flottante et d\'autres facteurs de calcul peuvent provoquer de legeres divergences dans les resultats. Nous examinons et mettons a jour regulierement nos outils, mais des erreurs peuvent occasionnellement survenir. Si vous remarquez une imprecision dans nos outils, veuillez nous contacter a info@toolkitonline.vip afin que nous puissions enqueter et corriger le probleme rapidement.',
      },
      {
        heading: 'Liens vers des Tiers',
        body: 'Notre Site Web peut contenir des liens vers des sites web, services ou ressources de tiers qui ne sont pas detenus ou controles par ToolKit Online. Nous n\'avons aucun controle et n\'assumons aucune responsabilite quant au contenu, aux politiques de confidentialite, aux pratiques ou a la disponibilite de sites web ou services de tiers. L\'inclusion de tout lien n\'implique pas l\'approbation, la recommandation ou le soutien de ToolKit Online. Vous reconnaissez et acceptez que nous ne sommes pas responsables, directement ou indirectement, de tout dommage ou perte cause par l\'utilisation ou la confiance accordee au contenu, aux biens ou aux services disponibles sur ou via des sites web de tiers.',
      },
      {
        heading: 'Limitation de Responsabilite',
        body: 'Dans la mesure maximale permise par la loi applicable, ToolKit Online et ses operateurs ne seront pas responsables de dommages directs, indirects, accessoires, speciaux, consecutifs ou punitifs, y compris, mais sans s\'y limiter, la perte de profits, de donnees, d\'usage, de clientele ou d\'autres pertes intangibles, resultant de : (a) votre acces ou utilisation, ou l\'impossibilite d\'acceder ou d\'utiliser, le Site Web ou tout outil ; (b) des erreurs, imprecisions ou omissions dans le contenu, les resultats ou les calculs fournis par nos outils ; (c) tout acces non autorise a nos serveurs ou aux informations personnelles qui y sont stockees ; (d) toute interruption ou cessation de la transmission vers ou depuis le Site Web ; ou (e) toute decision ou action prise en se fondant sur les informations fournies par nos outils. Vous utilisez nos outils et vous fiez a leurs resultats entierement a vos propres risques.',
      },
      {
        heading: 'Aucune Relation Professionnelle',
        body: 'L\'utilisation de ce Site Web et de ses outils ne cree aucune relation professionnelle-client entre vous et ToolKit Online. Nous ne fournissons pas de services de conseil financier, medical, juridique, comptable ou de tout autre type professionnel. Les outils et les informations sur ce Site Web ne remplacent pas les conseils professionnels adaptes a vos besoins et circonstances individuels.',
      },
      {
        heading: 'Modifications de Cet Avis',
        body: 'Nous nous reservons le droit de modifier ou de mettre a jour cet Avis de Non-Responsabilite a tout moment sans preavis. Les modifications seront effectives immediatement apres leur publication sur cette page avec une date de revision mise a jour. Votre utilisation continue du Site Web apres toute modification constitue votre acceptation de l\'Avis revise. Nous vous encourageons a consulter regulierement cette page pour rester informe de toute mise a jour.',
      },
      {
        heading: 'Nous Contacter',
        body: 'Si vous avez des questions ou des preoccupations concernant cet Avis de Non-Responsabilite, veuillez nous contacter a info@toolkitonline.vip.',
      },
    ],
  },
  de: {
    title: 'Haftungsausschluss',
    lastUpdated: 'Letzte Aktualisierung: Marz 2026',
    sections: [
      {
        heading: 'Allgemeiner Haftungsausschluss',
        body: 'Die von ToolKit Online ("wir" oder "unser") auf toolkitonline.vip (die "Website") bereitgestellten Informationen dienen ausschliesslich zu Informations- und Bildungszwecken. Alle von unseren Werkzeugen generierten Ergebnisse sind Schatzungen und Naherungen. Sie sollten nicht als professionelle Beratung jeglicher Art betrachtet werden. Obwohl wir uns bemuhen, nutzliche und genaue Werkzeuge bereitzustellen, sind die von unseren Rechnern, Konvertern und anderen Hilfsmitteln erzeugten Ergebnisse nur als allgemeine Orientierung gedacht. Sie sollten sich nicht ausschliesslich auf diese Ergebnisse verlassen, um wichtige personliche, finanzielle, medizinische oder rechtliche Entscheidungen zu treffen. Wir empfehlen dringend, qualifizierte Fachleute zu konsultieren, bevor Sie Massnahmen auf der Grundlage der von unseren Werkzeugen bereitgestellten Informationen oder Ergebnisse ergreifen.',
      },
      {
        heading: 'Haftungsausschluss fur Finanzwerkzeuge',
        body: 'Unsere Finanzwerkzeuge — einschliesslich, aber nicht beschrankt auf den MwSt-Rechner, den Kreditrechner, den Hypothekenrechner, den Investitionsrechner, den Zinseszinsrechner, den Gehaltsrechner, den Gewinnmargenrechner, den ROI-Rechner, den Rentenrechner und den Schuldenabzahlungsrechner — werden ausschliesslich zu Informations- und Bildungszwecken bereitgestellt. Die von diesen Werkzeugen generierten Ergebnisse stellen keine Finanzberatung, Anlageberatung, Steuerberatung oder sonstige Form professioneller finanzieller Orientierung dar. Finanzberechnungen basieren auf vereinfachten Modellen und berucksichtigen moglicherweise nicht alle Variablen, Gebuhren, Steuern, Marktbedingungen oder Vorschriften, die auf Ihre spezifische Situation zutreffen. Zinssatze, Steuersatze und andere in den Berechnungen verwendete Finanzparameter spiegeln moglicherweise nicht die aktuellen Marktbedingungen wider. Konsultieren Sie immer einen lizenzierten Finanzberater, Steuerberater oder Wirtschaftsprufer, bevor Sie finanzielle Entscheidungen treffen. Wir sind nicht verantwortlich fur finanzielle Verluste oder Schaden, die aus der Nutzung unserer Werkzeuge resultieren.',
      },
      {
        heading: 'Haftungsausschluss fur Gesundheitswerkzeuge',
        body: 'Unsere gesundheitsbezogenen Werkzeuge — einschliesslich, aber nicht beschrankt auf den BMI-Rechner, den Kalorienrechner, den Korperfettrechner, den Idealgewichtrechner, den Wasseraufnahmerechner, den Schlafrechner, den Schwangerschaftsrechner und den Schrittmacherrechner — werden ausschliesslich zu Informations- und Bildungszwecken bereitgestellt. Die von diesen Werkzeugen generierten Ergebnisse stellen keine medizinische Beratung, Diagnose oder Behandlungsempfehlung dar. Gesundheitsberechnungen basieren auf allgemeinen Formeln und Bevolkerungsdurchschnitten, die moglicherweise nicht fur Ihre individuellen Umstande, Krankengeschichte oder Gesundheitszustande geeignet sind. BMI, Korperfettanteile, Kalorienbedarf und andere Gesundheitsmetriken haben inhарente Einschrankungen und sollten im Kontext einer umfassenden Gesundheitsbewertung interpretiert werden. Konsultieren Sie immer einen qualifizierten Gesundheitsfachmann, Arzt oder registrierten Ernahrungsberater, bevor Sie Entscheidungen uber Ihre Gesundheit, Ernahrung, Trainingsroutine oder medizinische Behandlung treffen. Ignorieren Sie niemals professionellen medizinischen Rat und verzogern Sie nicht dessen Einholung aufgrund von etwas, das Sie auf dieser Website gelesen oder berechnet haben.',
      },
      {
        heading: 'Genauigkeit der Rechner',
        body: 'Wir unternehmen alle Anstrengungen, um sicherzustellen, dass unsere Rechner und Werkzeuge genaue Ergebnisse liefern. Wir konnen jedoch nicht garantieren, dass alle Berechnungen fehlerfrei sind oder dass die Ergebnisse in jeder Situation vollstandig korrekt sein werden. Unsere Werkzeuge verwenden mathematische Standardformeln und Algorithmen, aber reale Szenarien konnen zusatzliche Variablen, Ausnahmen oder Komplexitaten beinhalten, die unsere Werkzeuge nicht vollstandig berucksichtigen konnen. Rundungen, Gleitkommaarithmetik und andere Berechnungsfaktoren konnen geringfugige Abweichungen in den Ergebnissen verursachen. Wir uberprufen und aktualisieren unsere Werkzeuge regelma\u00dfig, aber gelegentlich konnen Fehler auftreten. Wenn Sie eine Ungenauigkeit in unseren Werkzeugen bemerken, kontaktieren Sie uns bitte unter info@toolkitonline.vip, damit wir das Problem umgehend untersuchen und beheben konnen.',
      },
      {
        heading: 'Links zu Dritten',
        body: 'Unsere Website kann Links zu Websites, Diensten oder Ressourcen Dritter enthalten, die nicht im Besitz oder unter der Kontrolle von ToolKit Online stehen. Wir haben keine Kontrolle uber und ubernehmen keine Verantwortung fur den Inhalt, die Datenschutzrichtlinien, die Praktiken oder die Verfugbarkeit von Websites oder Diensten Dritter. Die Aufnahme eines Links impliziert keine Billigung, Empfehlung oder Unterstutzung durch ToolKit Online. Sie erkennen an und stimmen zu, dass wir nicht verantwortlich oder haftbar sind, direkt oder indirekt, fur Schaden oder Verluste, die durch die Nutzung von oder das Vertrauen auf Inhalte, Waren oder Dienstleistungen verursacht werden, die auf oder uber Websites Dritter verfugbar sind.',
      },
      {
        heading: 'Haftungsbeschrankung',
        body: 'Im maximal gesetzlich zulassigen Umfang haften ToolKit Online und seine Betreiber nicht fur direkte, indirekte, zufallige, besondere, Folge- oder Strafschaden, einschliesslich, aber nicht beschrankt auf entgangene Gewinne, Datenverlust, Nutzungsausfall, Verlust des Firmenwerts oder andere immaterielle Verluste, die sich ergeben aus: (a) Ihrem Zugang zu oder Ihrer Nutzung oder Unmoglichkeit des Zugangs oder der Nutzung der Website oder von Werkzeugen; (b) Fehlern, Ungenauigkeiten oder Auslassungen in den Inhalten, Ergebnissen oder Berechnungen unserer Werkzeuge; (c) unbefugtem Zugriff auf unsere Server oder dort gespeicherte personliche Informationen; (d) Unterbrechung oder Einstellung der Ubertragung von oder zur Website; oder (e) Entscheidungen oder Handlungen, die auf den von unseren Werkzeugen bereitgestellten Informationen basieren. Sie nutzen unsere Werkzeuge und verlassen sich auf deren Ergebnisse vollstandig auf eigenes Risiko.',
      },
      {
        heading: 'Keine Professionelle Beziehung',
        body: 'Die Nutzung dieser Website und ihrer Werkzeuge begrundet kein professionelles Mandats- oder Beratungsverhaltnis zwischen Ihnen und ToolKit Online. Wir erbringen keine Finanzberatungs-, Medizin-, Rechtsberatungs-, Buchhaltungs- oder sonstige professionelle Dienstleistungen. Die Werkzeuge und Informationen auf dieser Website ersetzen keine professionelle Beratung, die auf Ihre individuellen Bedurfnisse und Umstande zugeschnitten ist.',
      },
      {
        heading: 'Anderungen Dieses Haftungsausschlusses',
        body: 'Wir behalten uns das Recht vor, diesen Haftungsausschluss jederzeit ohne vorherige Ankundigung zu andern oder zu aktualisieren. Anderungen werden sofort nach Veroffentlichung auf dieser Seite mit einem aktualisierten Revisionsdatum wirksam. Ihre fortgesetzte Nutzung der Website nach Anderungen stellt Ihre Zustimmung zum geanderten Haftungsausschluss dar. Wir empfehlen Ihnen, diese Seite regelmassig zu uberprufen, um uber Aktualisierungen informiert zu bleiben.',
      },
      {
        heading: 'Kontakt',
        body: 'Wenn Sie Fragen oder Bedenken zu diesem Haftungsausschluss haben, kontaktieren Sie uns bitte unter info@toolkitonline.vip.',
      },
    ],
  },
  pt: {
    title: 'Aviso Legal',
    lastUpdated: 'Ultima atualizacao: Marco 2026',
    sections: [
      {
        heading: 'Aviso Legal Geral',
        body: 'As informacoes fornecidas pelo ToolKit Online ("nos" ou "nosso") em toolkitonline.vip (o "Site") sao exclusivamente para fins informativos e educacionais. Todos os resultados gerados pelas nossas ferramentas sao estimativas e aproximacoes. Nao devem ser considerados como aconselhamento profissional de qualquer tipo. Embora nos esforcemos para fornecer ferramentas uteis e precisas, os resultados produzidos pelas nossas calculadoras, conversores e outros utilitarios destinam-se a servir apenas como orientacao geral. Voce nao deve confiar exclusivamente nestes resultados para tomar decisoes importantes a nivel pessoal, financeiro, medico ou legal. Recomendamos fortemente consultar profissionais qualificados antes de tomar qualquer acao com base nas informacoes ou resultados fornecidos pelas nossas ferramentas.',
      },
      {
        heading: 'Aviso Legal de Ferramentas Financeiras',
        body: 'As nossas ferramentas financeiras — incluindo, mas nao se limitando a, a Calculadora de IVA, a Calculadora de Emprestimos, a Calculadora de Hipoteca, a Calculadora de Investimentos, a Calculadora de Juros Compostos, a Calculadora de Salario, a Calculadora de Margem de Lucro, a Calculadora de ROI, a Calculadora de Aposentadoria e a Calculadora de Quitacao de Dividas — sao fornecidas exclusivamente para fins informativos e educacionais. Os resultados gerados por estas ferramentas nao constituem aconselhamento financeiro, aconselhamento de investimento, aconselhamento fiscal ou qualquer outra forma de orientacao financeira profissional. Os calculos financeiros sao baseados em modelos simplificados e podem nao considerar todas as variaveis, taxas, impostos, condicoes de mercado ou regulamentacoes aplicaveis a sua situacao especifica. As taxas de juros, aliquotas fiscais e outros parametros financeiros utilizados nos calculos podem nao refletir as condicoes atuais do mercado. Consulte sempre um consultor financeiro licenciado, um contador ou um profissional fiscal antes de tomar decisoes financeiras. Nao somos responsaveis por quaisquer perdas financeiras ou danos resultantes do uso das nossas ferramentas.',
      },
      {
        heading: 'Aviso Legal de Ferramentas de Saude',
        body: 'As nossas ferramentas relacionadas com a saude — incluindo, mas nao se limitando a, a Calculadora de IMC, a Calculadora de Calorias, a Calculadora de Gordura Corporal, a Calculadora de Peso Ideal, a Calculadora de Ingestao de Agua, a Calculadora de Sono, a Calculadora de Gravidez e a Calculadora de Ritmo — sao fornecidas exclusivamente para fins informativos e educacionais. Os resultados gerados por estas ferramentas nao constituem aconselhamento medico, diagnostico ou recomendacoes de tratamento. Os calculos de saude sao baseados em formulas gerais e medias populacionais que podem nao ser apropriados para as suas circunstancias individuais, historico medico ou condicoes de saude. O IMC, as percentagens de gordura corporal, as necessidades caloricas e outras metricas de saude tem limitacoes inerentes e devem ser interpretados no contexto de uma avaliacao de saude abrangente. Consulte sempre um profissional de saude qualificado, um medico ou um nutricionista registado antes de tomar decisoes sobre a sua saude, dieta, rotina de exercicio ou tratamento medico. Nunca ignore o aconselhamento medico profissional nem atrase a sua procura por causa de algo que leu ou calculou neste Site.',
      },
      {
        heading: 'Precisao das Calculadoras',
        body: 'Fazemos todos os esforcos para garantir que as nossas calculadoras e ferramentas produzam resultados precisos. No entanto, nao podemos garantir que todos os calculos estejam livres de erros ou que os resultados sejam completamente exatos em todas as situacoes. As nossas ferramentas utilizam formulas matematicas e algoritmos padrao, mas os cenarios do mundo real podem envolver variaveis adicionais, excecoes ou complexidades que as nossas ferramentas nao podem considerar completamente. Arredondamentos, aritmetica de ponto flutuante e outros fatores computacionais podem causar pequenas discrepancias nos resultados. Revisamos e atualizamos regularmente as nossas ferramentas, mas erros podem ocasionalmente ocorrer. Se notar alguma imprecisao nas nossas ferramentas, contacte-nos em info@toolkitonline.vip para que possamos investigar e corrigir o problema prontamente.',
      },
      {
        heading: 'Links de Terceiros',
        body: 'O nosso Site pode conter links para sites, servicos ou recursos de terceiros que nao sao propriedade nem controlados pelo ToolKit Online. Nao temos controlo e nao assumimos responsabilidade pelo conteudo, politicas de privacidade, praticas ou disponibilidade de sites ou servicos de terceiros. A inclusao de qualquer link nao implica aprovacao, recomendacao ou endosso por parte do ToolKit Online. Voce reconhece e concorda que nao somos responsaveis, direta ou indiretamente, por quaisquer danos ou perdas causados pelo uso ou dependencia de conteudos, bens ou servicos disponiveis em sites de terceiros.',
      },
      {
        heading: 'Limitacao de Responsabilidade',
        body: 'Na maxima extensao permitida pela lei aplicavel, o ToolKit Online e os seus operadores nao serao responsaveis por quaisquer danos diretos, indiretos, incidentais, especiais, consequenciais ou punitivos, incluindo, mas nao se limitando a, perda de lucros, dados, uso, clientela ou outras perdas intangiveis, resultantes de: (a) o seu acesso ou uso, ou a impossibilidade de aceder ou usar, o Site ou qualquer ferramenta; (b) erros, imprecisoes ou omissoes no conteudo, resultados ou calculos fornecidos pelas nossas ferramentas; (c) qualquer acesso nao autorizado aos nossos servidores ou informacoes pessoais neles armazenadas; (d) qualquer interrupcao ou cessacao de transmissao de ou para o Site; ou (e) qualquer decisao ou acao tomada com base nas informacoes fornecidas pelas nossas ferramentas. Voce utiliza as nossas ferramentas e confia nos seus resultados inteiramente por sua conta e risco.',
      },
      {
        heading: 'Sem Relacao Profissional',
        body: 'O uso deste Site e das suas ferramentas nao cria qualquer relacao profissional-cliente entre voce e o ToolKit Online. Nao fornecemos servicos de consultoria financeira, medica, juridica, contabil ou de qualquer outro tipo profissional. As ferramentas e informacoes neste Site nao substituem o aconselhamento profissional adaptado as suas necessidades e circunstancias individuais.',
      },
      {
        heading: 'Alteracoes a Este Aviso Legal',
        body: 'Reservamo-nos o direito de modificar ou atualizar este Aviso Legal a qualquer momento sem aviso previo. As alteracoes serao efetivas imediatamente apos a publicacao nesta pagina com uma data de revisao atualizada. O seu uso continuado do Site apos quaisquer alteracoes constitui a sua aceitacao do Aviso Legal revisado. Encorajamo-lo a rever esta pagina periodicamente para se manter informado sobre quaisquer atualizacoes.',
      },
      {
        heading: 'Contacte-nos',
        body: 'Se tiver alguma questao ou preocupacao sobre este Aviso Legal, contacte-nos em info@toolkitonline.vip.',
      },
    ],
  },
};

export default function DisclaimerPage() {
  const params = useParams();
  const lang = (params?.lang as Locale) || 'en';
  const c = content[lang];

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <article className="prose prose-lg max-w-none">
        <h1 className="text-3xl font-bold mb-2">{c.title}</h1>
        <p className="text-sm text-gray-500 mb-8">{c.lastUpdated}</p>
        {c.sections.map((section, i) => (
          <div key={i} className="mb-6">
            <h2 className="text-xl font-semibold mb-2">{section.heading}</h2>
            <p className="text-gray-700 leading-relaxed">{section.body}</p>
          </div>
        ))}
      </article>
    </div>
  );
}
