'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'insulationCost', labels: { en: 'Insulation Cost ($)', it: 'Costo isolamento (€)', es: 'Costo aislamiento ($)', fr: 'Cout isolation (€)', de: 'Daemmungskosten (€)', pt: 'Custo isolamento (R$)' }, defaultValue: '3000' },
  { key: 'currentBill', labels: { en: 'Current Annual Energy ($)', it: 'Energia annuale attuale (€)', es: 'Energia anual actual ($)', fr: 'Energie annuelle actuelle (€)', de: 'Aktuelle Jahresenergie (€)', pt: 'Energia anual atual (R$)' }, defaultValue: '2400' },
  { key: 'expectedSavingsPercent', labels: { en: 'Expected Savings (%)', it: 'Risparmio atteso (%)', es: 'Ahorro esperado (%)', fr: 'Economies attendues (%)', de: 'Erwartete Ersparnis (%)', pt: 'Economia esperada (%)' }, defaultValue: '20', min: 5, max: 50 },
  { key: 'incentive', labels: { en: 'Tax Incentive ($)', it: 'Incentivo fiscale (€)', es: 'Incentivo fiscal ($)', fr: 'Incitation fiscale (€)', de: 'Steueranreiz (€)', pt: 'Incentivo fiscal (R$)' }, defaultValue: '500' },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'paybackYears', labels: { en: 'Payback Period (years)', it: 'Ammortamento (anni)', es: 'Amortizacion (anos)', fr: 'Amortissement (annees)', de: 'Amortisation (Jahre)', pt: 'Amortizacao (anos)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'tenYearROI', labels: { en: '10-Year ROI (%)', it: 'ROI 10 anni (%)', es: 'ROI 10 anos (%)', fr: 'ROI 10 ans (%)', de: '10-Jahres-ROI (%)', pt: 'ROI 10 anos (%)' }, color: 'green' as const, format: 'percent' as const },
  { key: 'tenYearNetSavings', labels: { en: '10-Year Net Savings', it: 'Risparmio netto 10 anni', es: 'Ahorro neto 10 anos', fr: 'Economies nettes 10 ans', de: '10-Jahres-Nettoeinsparung', pt: 'Economia liquida 10 anos' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const cost = v.insulationCost || 3000; const bill = v.currentBill || 2400; const pct = (v.expectedSavingsPercent || 20) / 100; const inc = v.incentive || 500;
  const annual = bill * pct; const net = cost - inc; const payback = annual > 0 ? net / annual : 99;
  const tenYear = annual * 10 - net; const roi = net > 0 ? (tenYear / net) * 100 : 0;
  return { annualSavings: Math.round(annual), paybackYears: Math.round(payback * 10) / 10, tenYearROI: Math.round(roi), tenYearNetSavings: Math.round(tenYear) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Insulation ROI Calculator: Calculate Your Savings', ['Home insulation is one of the highest-ROI home improvements, typically paying for itself in 2-5 years through reduced energy bills. Proper insulation keeps your home comfortable year-round.', 'This calculator estimates annual energy savings, payback period, and 10-year return on investment for insulation upgrades. The IRA provides a 30% tax credit up to $1,200 for insulation.', 'The type of insulation matters: attic insulation offers the highest ROI (15-25% energy savings), followed by wall insulation (10-20%) and floor/basement insulation (5-15%).', 'For related tools, see our <a href="/${lang}/tools/home-energy-audit-calculator">home energy audit calculator</a> and <a href="/${lang}/tools/heat-pump-calculator">heat pump calculator</a>.'], [{q:'What type of insulation has the best ROI?',a:'Attic insulation offers the best ROI, as heat rises. Adding or upgrading attic insulation can save 15-25% on heating and cooling.'},{q:'How much does insulation cost?',a:'Attic insulation costs $1,500-$3,500 for a typical home. Wall insulation ranges from $2,000-$6,000 for blown-in.'},{q:'Is there a tax credit for insulation?',a:'Yes, the Inflation Reduction Act provides a 30% tax credit up to $1,200/year for insulation improvements.'},{q:'How long does insulation last?',a:'Most insulation lasts 20-80+ years depending on the type. Fiberglass lasts 80-100 years; spray foam lasts 80+ years.'}]),
  it: mkSeo('Calcolatore ROI Isolamento', ['L\'isolamento e uno dei miglioramenti domestici con il ROI piu alto.', 'Questo calcolatore stima risparmio annuale, ammortamento e ROI in 10 anni.', 'L\'isolamento del sottotetto offre il ROI migliore (15-25% di risparmio).', 'Consulta il <a href="/${lang}/tools/home-energy-audit-calculator">calcolatore audit energetico</a>.'], [{q:'Quale tipo ha il miglior ROI?',a:'L\'isolamento del sottotetto, poiche il calore sale.'},{q:'Quanto costa?',a:'Sottotetto: 1.500-3.500€. Pareti: 2.000-6.000€.'},{q:'Ci sono incentivi fiscali?',a:'Si, molti paesi offrono detrazioni del 30% o piu.'},{q:'Quanto dura?',a:'20-80+ anni a seconda del tipo.'}]),
  es: mkSeo('Calculadora ROI Aislamiento', ['El aislamiento es una de las mejoras con mayor ROI.', 'Esta calculadora estima ahorro anual, amortizacion y ROI en 10 anos.', 'El aislamiento del atico ofrece el mejor ROI (15-25% de ahorro).', 'Consulta la <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Que tipo tiene mejor ROI?',a:'El aislamiento del atico, ya que el calor sube.'},{q:'Cuanto cuesta?',a:'Atico: $1,500-$3,500. Paredes: $2,000-$6,000.'},{q:'Hay credito fiscal?',a:'Si, muchos paises ofrecen deducciones del 30% o mas.'},{q:'Cuanto dura?',a:'20-80+ anos segun el tipo.'}]),
  fr: mkSeo('Calculateur ROI Isolation', ['L\'isolation est l\'une des ameliorations avec le meilleur ROI.', 'Ce calculateur estime economies annuelles, amortissement et ROI sur 10 ans.', 'L\'isolation des combles offre le meilleur ROI (15-25% d\'economies).', 'Consultez le <a href="/${lang}/tools/home-energy-audit-calculator">calculateur audit energetique</a>.'], [{q:'Quel type a le meilleur ROI?',a:'L\'isolation des combles, car la chaleur monte.'},{q:'Combien ca coute?',a:'Combles: 1 500-3 500€. Murs: 2 000-6 000€.'},{q:'Y a-t-il un credit d\'impot?',a:'Oui, de nombreux pays offrent des deductions de 30% ou plus.'},{q:'Combien de temps ca dure?',a:'20-80+ ans selon le type.'}]),
  de: mkSeo('Daemmung ROI Rechner', ['Daemmung ist eine der Hausverbesserungen mit dem hoechsten ROI.', 'Dieser Rechner schaetzt jaehrliche Ersparnis, Amortisation und 10-Jahres-ROI.', 'Dachbodenddaemmung bietet den besten ROI (15-25% Ersparnis).', 'Nutzen Sie den <a href="/${lang}/tools/home-energy-audit-calculator">Energieaudit-Rechner</a>.'], [{q:'Welcher Typ hat den besten ROI?',a:'Dachbodendaemmung, da Waerme aufsteigt.'},{q:'Was kostet es?',a:'Dachboden: 1.500-3.500€. Waende: 2.000-6.000€.'},{q:'Gibt es Steuergutschriften?',a:'Ja, viele Laender bieten 30% oder mehr Abzuege.'},{q:'Wie lange haelt es?',a:'20-80+ Jahre je nach Typ.'}]),
  pt: mkSeo('Calculadora ROI Isolamento', ['O isolamento e uma das melhorias com maior ROI.', 'Esta calculadora estima economia anual, amortizacao e ROI em 10 anos.', 'O isolamento do sotao oferece o melhor ROI (15-25% de economia).', 'Consulte a <a href="/${lang}/tools/home-energy-audit-calculator">calculadora auditoria energetica</a>.'], [{q:'Qual tipo tem melhor ROI?',a:'O isolamento do sotao, pois o calor sobe.'},{q:'Quanto custa?',a:'Sotao: R$1.500-3.500. Paredes: R$2.000-6.000.'},{q:'Ha credito fiscal?',a:'Sim, muitos paises oferecem deducoes de 30% ou mais.'},{q:'Quanto dura?',a:'20-80+ anos dependendo do tipo.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="insulation-roi-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
