'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'petAge', labels: { en: 'Pet Age (years)', it: 'Eta animale (anni)', es: 'Edad mascota (anos)', fr: 'Age animal (annees)', de: 'Tieralter (Jahre)', pt: 'Idade animal (anos)' }, defaultValue: '3', min: 0, max: 20 },
  { key: 'annualVetCosts', labels: { en: 'Annual Vet Costs ($)', it: 'Costi veterinari annuali (€)', es: 'Costos veterinarios ($)', fr: 'Frais veto annuels (€)', de: 'Jaehrliche Tierarztkosten (€)', pt: 'Custos veterinarios (R$)' }, defaultValue: '500' },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '250' },
];
const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'annualCoverage', labels: { en: 'Annual Coverage', it: 'Copertura annuale', es: 'Cobertura anual', fr: 'Couverture annuelle', de: 'Jaehrliche Deckung', pt: 'Cobertura anual' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'estimatedSavings', labels: { en: 'Est. Annual Savings', it: 'Risparmio annuale est.', es: 'Ahorro anual est.', fr: 'Economies annuelles est.', de: 'Geschaetzte Ersparnis', pt: 'Economia anual est.' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const baseCost = 40; const ageFactor = 1 + (v.petAge || 3) * 0.08; const dd = ((v.deductible || 250) - 100) * 0.05; const monthly = Math.max(10, baseCost * ageFactor - dd); const vet = v.annualVetCosts || 500;
  return { monthlyPremium: Math.round(monthly), annualPremium: Math.round(monthly * 12), annualCoverage: Math.round(vet * 2), estimatedSavings: Math.round(Math.max(0, vet - monthly * 12)) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Pet Insurance Calculator: Estimate Your Coverage Cost', ['Pet insurance helps cover unexpected veterinary costs. From emergency surgeries to chronic conditions, having coverage provides peace of mind and helps you make the best medical decisions for your pet.', 'This calculator estimates premiums based on pet age, expected vet costs, and deductible. Younger pets cost less to insure as they are less likely to develop age-related issues.', 'The average pet owner spends $1,000-$3,000/year on vet care, and a single emergency can cost $3,000-$10,000+. Pet insurance typically reimburses 70-90% of covered costs after the deductible.', 'For related tools, see our <a href="/${lang}/tools/insurance-deductible-calculator">insurance deductible calculator</a>.'], [{q:'Is pet insurance worth it?',a:'For most pet owners, yes — a single emergency surgery can cost $5,000+, far more than years of premiums.'},{q:'What does pet insurance cover?',a:'Most plans cover accidents, illnesses, surgeries, hospitalizations, medications, and diagnostic tests. Pre-existing conditions are excluded.'},{q:'When should I get pet insurance?',a:'The earlier the better — premiums are lower for younger pets and conditions that develop before coverage are pre-existing.'},{q:'How do deductibles work?',a:'You pay the deductible amount first each year. Higher deductibles mean lower premiums but more out-of-pocket costs.'}]),
  it: mkSeo('Calcolatore Assicurazione Animali', ['L\'assicurazione per animali copre costi veterinari imprevisti. Fornisce tranquillita e ti aiuta a prendere le migliori decisioni mediche per il tuo animale.', 'Questo calcolatore stima i premi in base all\'eta, costi veterinari attesi e franchigia.', 'Il proprietario medio spende 1.000-3.000 euro all\'anno in cure veterinarie.', 'Consulta il nostro <a href="/${lang}/tools/insurance-deductible-calculator">calcolatore franchigia</a>.'], [{q:'L\'assicurazione per animali vale la pena?',a:'Per la maggior parte dei proprietari si, un singolo intervento d\'emergenza puo costare oltre 5.000 euro.'},{q:'Cosa copre?',a:'Incidenti, malattie, interventi chirurgici, ricoveri e farmaci. Le condizioni preesistenti sono escluse.'},{q:'Quando dovrei attivarla?',a:'Prima possibile: i premi sono piu bassi per animali giovani.'},{q:'Come funziona la franchigia?',a:'Paghi la franchigia prima ogni anno, poi l\'assicurazione copre il resto.'}]),
  es: mkSeo('Calculadora Seguro de Mascotas', ['El seguro de mascotas cubre costos veterinarios inesperados.', 'Esta calculadora estima las primas segun edad, costos veterinarios y deducible.', 'El dueno promedio gasta $1,000-$3,000/ano en cuidado veterinario.', 'Consulta nuestra <a href="/${lang}/tools/insurance-deductible-calculator">calculadora de deducible</a>.'], [{q:'Vale la pena el seguro de mascotas?',a:'Para la mayoria si, una cirugia de emergencia puede costar $5,000+.'},{q:'Que cubre?',a:'Accidentes, enfermedades, cirugias, hospitalizaciones y medicamentos.'},{q:'Cuando debo contratarlo?',a:'Lo antes posible: las primas son menores para mascotas jovenes.'},{q:'Como funcionan los deducibles?',a:'Pagas el deducible primero cada ano antes de que el seguro cubra.'}]),
  fr: mkSeo('Calculateur Assurance Animaux', ['L\'assurance animaux couvre les frais veterinaires imprevus.', 'Ce calculateur estime les primes selon l\'age, les frais veto et la franchise.', 'Le proprietaire moyen depense 1 000-3 000 euros/an en soins veterinaires.', 'Consultez notre <a href="/${lang}/tools/insurance-deductible-calculator">calculateur de franchise</a>.'], [{q:'L\'assurance animaux en vaut-elle la peine?',a:'Pour la plupart des proprietaires oui, une chirurgie d\'urgence peut couter plus de 5 000 euros.'},{q:'Que couvre-t-elle?',a:'Accidents, maladies, chirurgies, hospitalisations et medicaments.'},{q:'Quand dois-je la souscrire?',a:'Le plus tot possible: les primes sont moins cheres pour les jeunes animaux.'},{q:'Comment fonctionne la franchise?',a:'Vous payez la franchise d\'abord chaque annee.'}]),
  de: mkSeo('Tierversicherungsrechner', ['Die Tierversicherung deckt unerwartete Tierarztkosten ab.', 'Dieser Rechner schaetzt Praemien basierend auf Alter, Tierarztkosten und Selbstbeteiligung.', 'Der durchschnittliche Tierbesitzer gibt 1.000-3.000 Euro/Jahr fuer Tierarztkosten aus.', 'Nutzen Sie unseren <a href="/${lang}/tools/insurance-deductible-calculator">Selbstbeteiligungsrechner</a>.'], [{q:'Lohnt sich eine Tierversicherung?',a:'Fuer die meisten Besitzer ja, eine Notoperation kann ueber 5.000 Euro kosten.'},{q:'Was wird abgedeckt?',a:'Unfaelle, Krankheiten, Operationen, Krankenhaus und Medikamente.'},{q:'Wann sollte ich sie abschliessen?',a:'So frueh wie moeglich: Praemien sind niedriger fuer junge Tiere.'},{q:'Wie funktioniert die Selbstbeteiligung?',a:'Sie zahlen die Selbstbeteiligung zuerst jedes Jahr.'}]),
  pt: mkSeo('Calculadora Seguro Pet', ['O seguro pet cobre custos veterinarios inesperados.', 'Esta calculadora estima premios com base na idade, custos veterinarios e franquia.', 'O dono medio gasta R$1.000-3.000/ano em cuidados veterinarios.', 'Consulte nossa <a href="/${lang}/tools/insurance-deductible-calculator">calculadora de franquia</a>.'], [{q:'O seguro pet vale a pena?',a:'Para a maioria dos donos sim, uma cirurgia de emergencia pode custar R$5.000+.'},{q:'O que cobre?',a:'Acidentes, doencas, cirurgias, hospitalizacoes e medicamentos.'},{q:'Quando devo contratar?',a:'O mais cedo possivel: premios sao menores para animais jovens.'},{q:'Como funciona a franquia?',a:'Voce paga a franquia primeiro a cada ano.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="pet-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
