'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'roofArea', labels: { en: 'Roof Area (sq ft)', it: 'Area tetto (mq)', es: 'Area techo (sq ft)', fr: 'Surface toit (m²)', de: 'Dachflaeche (m²)', pt: 'Area telhado (m²)' }, defaultValue: '400' },
  { key: 'sunHours', labels: { en: 'Avg Sun Hours/Day', it: 'Ore sole medie/giorno', es: 'Horas sol promedio/dia', fr: 'Heures soleil/jour', de: 'Sonnenstunden/Tag', pt: 'Horas sol/dia' }, defaultValue: '5', min: 1, max: 10, step: 0.5 },
  { key: 'electricityRate', labels: { en: 'Electricity Rate ($/kWh)', it: 'Tariffa elettrica (€/kWh)', es: 'Tarifa electrica ($/kWh)', fr: 'Tarif electricite (€/kWh)', de: 'Strompreis (€/kWh)', pt: 'Tarifa eletrica (R$/kWh)' }, defaultValue: '0.15', step: 0.01 },
  { key: 'currentBill', labels: { en: 'Current Monthly Bill ($)', it: 'Bolletta mensile attuale (€)', es: 'Factura mensual actual ($)', fr: 'Facture mensuelle (€)', de: 'Aktuelle Monatsrechnung (€)', pt: 'Conta mensal atual (R$)' }, defaultValue: '150' },
];
const results = [
  { key: 'annualSavings', labels: { en: 'Annual Savings', it: 'Risparmio annuale', es: 'Ahorro anual', fr: 'Economies annuelles', de: 'Jaehrliche Ersparnis', pt: 'Economia anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'monthlySavings', labels: { en: 'Monthly Savings', it: 'Risparmio mensile', es: 'Ahorro mensual', fr: 'Economies mensuelles', de: 'Monatliche Ersparnis', pt: 'Economia mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualProduction', labels: { en: 'Annual Production (kWh)', it: 'Produzione annuale (kWh)', es: 'Produccion anual (kWh)', fr: 'Production annuelle (kWh)', de: 'Jahresproduktion (kWh)', pt: 'Producao anual (kWh)' }, color: 'gray' as const, format: 'number' as const },
  { key: 'coveragePercent', labels: { en: 'Bill Coverage (%)', it: 'Copertura bolletta (%)', es: 'Cobertura factura (%)', fr: 'Couverture facture (%)', de: 'Rechnungsdeckung (%)', pt: 'Cobertura conta (%)' }, color: 'gray' as const, format: 'percent' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const roof = v.roofArea || 400; const sun = v.sunHours || 5; const rate = v.electricityRate || 0.15; const bill = v.currentBill || 150;
  const panelOutput = 0.02; // kW per sq ft
  const systemKW = roof * panelOutput; const annual = systemKW * sun * 365;
  const savings = annual * rate; const monthly = savings / 12;
  const coverage = bill > 0 ? Math.min(100, (monthly / bill) * 100) : 0;
  return { annualSavings: Math.round(savings), monthlySavings: Math.round(monthly), annualProduction: Math.round(annual), coveragePercent: Math.round(coverage) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Solar Savings Calculator: How Much Can You Save?', ['Solar panels can dramatically reduce or eliminate your electricity bills. The amount you save depends on your roof size, local sun hours, electricity rates, and current energy consumption.', 'This calculator estimates your potential annual and monthly savings from solar panels based on available roof area and average daily sun hours in your location.', 'The average US household saves $1,000-$2,500 per year with solar panels. In sunny states like California, Arizona, and Texas, savings can be even higher due to more sun hours and higher electricity rates.', 'For related tools, see our <a href="/${lang}/tools/solar-panel-roi-calculator">solar panel ROI calculator</a> and <a href="/${lang}/tools/solar-battery-calculator">solar battery calculator</a>.'], [{q:'How much can I save with solar panels?',a:'Most homeowners save $1,000-$2,500 per year, depending on system size, location, and electricity rates.'},{q:'Can solar panels eliminate my electric bill?',a:'In many cases yes. A properly sized system can offset 80-100% of your electricity usage through net metering.'},{q:'How many solar panels do I need?',a:'A typical home needs 20-30 panels (6-9 kW system) to offset most electricity usage.'},{q:'Do solar panels work on cloudy days?',a:'Yes, but at reduced efficiency (10-25% of peak output). Annual production accounts for cloudy days.'}]),
  it: mkSeo('Calcolatore Risparmio Solare', ['I pannelli solari possono ridurre drasticamente le tue bollette elettriche.', 'Questo calcolatore stima il risparmio potenziale annuale e mensile basato sull\'area del tetto e le ore di sole.', 'La famiglia media risparmia 1.000-2.500€ all\'anno con i pannelli solari.', 'Consulta il <a href="/${lang}/tools/solar-panel-roi-calculator">calcolatore ROI pannelli solari</a>.'], [{q:'Quanto posso risparmiare?',a:'La maggior parte dei proprietari risparmia 1.000-2.500€/anno.'},{q:'Possono eliminare la bolletta?',a:'In molti casi si, con un impianto dimensionato correttamente.'},{q:'Quanti pannelli servono?',a:'Una casa tipica ha bisogno di 20-30 pannelli (6-9 kW).'},{q:'Funzionano nei giorni nuvolosi?',a:'Si, ma a efficienza ridotta (10-25% della produzione massima).'}]),
  es: mkSeo('Calculadora de Ahorro Solar', ['Los paneles solares pueden reducir drasticamente tus facturas de electricidad.', 'Esta calculadora estima tu ahorro potencial anual y mensual basado en el area del techo y horas de sol.', 'El hogar promedio ahorra $1,000-$2,500 al ano con paneles solares.', 'Consulta la <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paneles solares</a>.'], [{q:'Cuanto puedo ahorrar?',a:'La mayoria ahorra $1,000-$2,500/ano.'},{q:'Pueden eliminar mi factura?',a:'En muchos casos si, con un sistema bien dimensionado.'},{q:'Cuantos paneles necesito?',a:'Una casa tipica necesita 20-30 paneles (6-9 kW).'},{q:'Funcionan en dias nublados?',a:'Si, pero a eficiencia reducida (10-25%).'}]),
  fr: mkSeo('Calculateur Economies Solaires', ['Les panneaux solaires peuvent reduire considerablement vos factures d\'electricite.', 'Ce calculateur estime vos economies potentielles basees sur la surface du toit et les heures d\'ensoleillement.', 'Le foyer moyen economise 1 000-2 500€/an avec des panneaux solaires.', 'Consultez le <a href="/${lang}/tools/solar-panel-roi-calculator">calculateur ROI panneaux solaires</a>.'], [{q:'Combien puis-je economiser?',a:'La plupart des proprietaires economisent 1 000-2 500€/an.'},{q:'Peuvent-ils eliminer ma facture?',a:'Dans de nombreux cas oui, avec un systeme bien dimensionne.'},{q:'Combien de panneaux me faut-il?',a:'Une maison typique a besoin de 20-30 panneaux (6-9 kW).'},{q:'Fonctionnent-ils par temps nuageux?',a:'Oui, mais a efficacite reduite (10-25%).'}]),
  de: mkSeo('Solar-Ersparnis-Rechner', ['Solarmodule koennen Ihre Stromrechnungen drastisch reduzieren.', 'Dieser Rechner schaetzt Ihre potenzielle jaehrliche und monatliche Ersparnis basierend auf Dachflaeche und Sonnenstunden.', 'Der durchschnittliche Haushalt spart 1.000-2.500€/Jahr mit Solarmodulen.', 'Nutzen Sie den <a href="/${lang}/tools/solar-panel-roi-calculator">Solaranlage ROI Rechner</a>.'], [{q:'Wie viel kann ich sparen?',a:'Die meisten Hausbesitzer sparen 1.000-2.500€/Jahr.'},{q:'Koennen sie meine Rechnung eliminieren?',a:'In vielen Faellen ja, mit einem richtig dimensionierten System.'},{q:'Wie viele Module brauche ich?',a:'Ein typisches Haus braucht 20-30 Module (6-9 kW).'},{q:'Funktionieren sie bei bewoelktem Wetter?',a:'Ja, aber mit reduzierter Effizienz (10-25%).'}]),
  pt: mkSeo('Calculadora de Economia Solar', ['Os paineis solares podem reduzir drasticamente suas contas de energia.', 'Esta calculadora estima sua economia potencial anual e mensal baseada na area do telhado e horas de sol.', 'A familia media economiza R$1.000-2.500/ano com paineis solares.', 'Consulte a <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paineis solares</a>.'], [{q:'Quanto posso economizar?',a:'A maioria dos proprietarios economiza R$1.000-2.500/ano.'},{q:'Podem eliminar minha conta?',a:'Em muitos casos sim, com um sistema bem dimensionado.'},{q:'Quantos paineis preciso?',a:'Uma casa tipica precisa de 20-30 paineis (6-9 kW).'},{q:'Funcionam em dias nublados?',a:'Sim, mas com eficiencia reduzida (10-25%).'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="solar-savings-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
