'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'dailyUsage', labels: { en: 'Daily Usage (kWh)', it: 'Consumo giornaliero (kWh)', es: 'Consumo diario (kWh)', fr: 'Consommation journaliere (kWh)', de: 'Taeglicher Verbrauch (kWh)', pt: 'Consumo diario (kWh)' }, defaultValue: '30' },
  { key: 'backupHours', labels: { en: 'Backup Hours Needed', it: 'Ore backup necessarie', es: 'Horas de respaldo', fr: 'Heures de secours', de: 'Benoetigte Backup-Stunden', pt: 'Horas backup necessarias' }, defaultValue: '12', min: 1, max: 48 },
  { key: 'solarProduction', labels: { en: 'Daily Solar Production (kWh)', it: 'Produzione solare giornaliera (kWh)', es: 'Produccion solar diaria (kWh)', fr: 'Production solaire journaliere (kWh)', de: 'Taegliche Solarproduktion (kWh)', pt: 'Producao solar diaria (kWh)' }, defaultValue: '25' },
  { key: 'batteryPrice', labels: { en: 'Battery Price ($/kWh)', it: 'Prezzo batteria (€/kWh)', es: 'Precio bateria ($/kWh)', fr: 'Prix batterie (€/kWh)', de: 'Batteriepreis (€/kWh)', pt: 'Preco bateria (R$/kWh)' }, defaultValue: '500' },
];
const results = [
  { key: 'requiredCapacity', labels: { en: 'Required Capacity (kWh)', it: 'Capacita richiesta (kWh)', es: 'Capacidad requerida (kWh)', fr: 'Capacite requise (kWh)', de: 'Benoetigte Kapazitaet (kWh)', pt: 'Capacidade necessaria (kWh)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'numPowerwalls', labels: { en: 'Powerwalls Needed', it: 'Powerwall necessari', es: 'Powerwalls necesarios', fr: 'Powerwalls necessaires', de: 'Benoetigte Powerwalls', pt: 'Powerwalls necessarios' }, color: 'gray' as const, format: 'number' as const },
  { key: 'estimatedCost', labels: { en: 'Estimated Cost', it: 'Costo stimato', es: 'Costo estimado', fr: 'Cout estime', de: 'Geschaetzte Kosten', pt: 'Custo estimado' }, color: 'red' as const, format: 'currency' as const },
  { key: 'excessSolar', labels: { en: 'Daily Excess Solar (kWh)', it: 'Solare in eccesso (kWh)', es: 'Exceso solar diario (kWh)', fr: 'Excedent solaire (kWh)', de: 'Taeglicher Solarueberschuss (kWh)', pt: 'Excesso solar diario (kWh)' }, color: 'green' as const, format: 'number' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const daily = v.dailyUsage || 30; const hours = v.backupHours || 12; const solar = v.solarProduction || 25; const price = v.batteryPrice || 500;
  const hourlyUsage = daily / 24; const needed = hourlyUsage * hours * 1.2; // 20% buffer
  const powerwalls = Math.ceil(needed / 13.5); // 13.5 kWh per Powerwall
  const cost = needed * price; const excess = Math.max(0, solar - daily);
  return { requiredCapacity: Math.round(needed * 10) / 10, numPowerwalls: powerwalls, estimatedCost: Math.round(cost), excessSolar: Math.round(excess * 10) / 10 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Solar Battery Size Calculator: How Much Storage Do You Need?', ['A solar battery storage system lets you store excess solar energy for use at night or during power outages. Properly sizing your battery ensures you maximize self-consumption and minimize grid dependence.', 'This calculator estimates the battery capacity you need based on your daily energy usage, desired backup hours, and solar production. It also estimates the number of Tesla Powerwall equivalents and total cost.', 'Battery prices have dropped significantly, from $1,000+/kWh in 2015 to $400-$600/kWh today. With the 30% federal tax credit, battery storage is increasingly affordable for homeowners.', 'For related tools, see our <a href="/${lang}/tools/solar-panel-roi-calculator">solar panel ROI calculator</a> and <a href="/${lang}/tools/solar-savings-calculator">solar savings calculator</a>.'], [{q:'How much battery storage do I need?',a:'For whole-home backup, typically 10-20 kWh (1-2 Powerwalls). For essentials-only backup, 5-10 kWh may suffice.'},{q:'How long do solar batteries last?',a:'Most lithium-ion batteries last 10-15 years with a warranty of 10 years or 70% capacity retention.'},{q:'Can I go completely off-grid?',a:'Technically yes, but it requires significant oversizing of both solar and battery systems, making it expensive.'},{q:'Are solar batteries worth the investment?',a:'In areas with high electricity rates, frequent outages, or no net metering, batteries offer good value. The 30% tax credit improves ROI significantly.'}]),
  it: mkSeo('Calcolatore Batteria Solare', ['Un sistema di accumulo solare ti permette di immagazzinare l\'energia in eccesso per la notte o durante i blackout.', 'Questo calcolatore stima la capacita necessaria basata sul consumo giornaliero e le ore di backup desiderate.', 'I prezzi delle batterie sono scesi significativamente negli ultimi anni.', 'Consulta il <a href="/${lang}/tools/solar-panel-roi-calculator">calcolatore ROI pannelli solari</a>.'], [{q:'Quanta capacita mi serve?',a:'Per un backup completo, 10-20 kWh. Per i soli essenziali, 5-10 kWh.'},{q:'Quanto durano?',a:'10-15 anni con garanzia di 10 anni.'},{q:'Posso andare completamente off-grid?',a:'Tecnicamente si, ma richiede un sovradimensionamento significativo.'},{q:'Valgono l\'investimento?',a:'Si, in aree con tariffe alte o blackout frequenti.'}]),
  es: mkSeo('Calculadora Bateria Solar', ['Un sistema de almacenamiento solar te permite guardar energia excedente para la noche o apagones.', 'Esta calculadora estima la capacidad necesaria basada en tu consumo diario y horas de respaldo.', 'Los precios de las baterias han bajado significativamente.', 'Consulta la <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paneles solares</a>.'], [{q:'Cuanta capacidad necesito?',a:'Para respaldo completo, 10-20 kWh. Solo esenciales, 5-10 kWh.'},{q:'Cuanto duran?',a:'10-15 anos con garantia de 10 anos.'},{q:'Puedo ir completamente off-grid?',a:'Tecnicamente si, pero requiere sobredimensionamiento.'},{q:'Valen la inversion?',a:'Si, en areas con tarifas altas o apagones frecuentes.'}]),
  fr: mkSeo('Calculateur Batterie Solaire', ['Un systeme de stockage solaire vous permet de stocker l\'energie excedentaire pour la nuit ou les coupures.', 'Ce calculateur estime la capacite necessaire basee sur votre consommation et les heures de secours souhaitees.', 'Les prix des batteries ont baisse significativement.', 'Consultez le <a href="/${lang}/tools/solar-panel-roi-calculator">calculateur ROI panneaux solaires</a>.'], [{q:'Quelle capacite me faut-il?',a:'Pour un backup complet, 10-20 kWh. Essentiels seulement, 5-10 kWh.'},{q:'Combien de temps durent-elles?',a:'10-15 ans avec garantie de 10 ans.'},{q:'Puis-je etre completement autonome?',a:'Techniquement oui, mais cela necessite un surdimensionnement.'},{q:'Valent-elles l\'investissement?',a:'Oui, dans les zones a tarifs eleves ou coupures frequentes.'}]),
  de: mkSeo('Solarbatterie-Rechner', ['Ein Solarspeichersystem ermoeglicht die Speicherung ueberschuessiger Solarenergie fuer die Nacht oder Stromausfaelle.', 'Dieser Rechner schaetzt die benoetigte Kapazitaet basierend auf Ihrem Verbrauch und gewuenschten Backup-Stunden.', 'Die Batteriepreise sind in den letzten Jahren deutlich gesunken.', 'Nutzen Sie den <a href="/${lang}/tools/solar-panel-roi-calculator">Solaranlage ROI Rechner</a>.'], [{q:'Wie viel Kapazitaet brauche ich?',a:'Fuer Voll-Backup: 10-20 kWh. Nur Wesentliches: 5-10 kWh.'},{q:'Wie lange halten sie?',a:'10-15 Jahre mit 10 Jahren Garantie.'},{q:'Kann ich komplett autark sein?',a:'Technisch ja, erfordert aber erhebliche Ueberdimensionierung.'},{q:'Lohnt sich die Investition?',a:'Ja, bei hohen Stromtarifen oder haeufigen Ausfaellen.'}]),
  pt: mkSeo('Calculadora Bateria Solar', ['Um sistema de armazenamento solar permite guardar energia excedente para a noite ou falta de energia.', 'Esta calculadora estima a capacidade necessaria baseada no seu consumo diario e horas de backup.', 'Os precos das baterias cairam significativamente.', 'Consulte a <a href="/${lang}/tools/solar-panel-roi-calculator">calculadora ROI paineis solares</a>.'], [{q:'Quanta capacidade preciso?',a:'Para backup completo, 10-20 kWh. Apenas essenciais, 5-10 kWh.'},{q:'Quanto duram?',a:'10-15 anos com garantia de 10 anos.'},{q:'Posso ficar completamente off-grid?',a:'Tecnicamente sim, mas requer superdimensionamento.'},{q:'Valem o investimento?',a:'Sim, em areas com tarifas altas ou quedas frequentes.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="solar-battery-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
