'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'propertyValue', labels: { en: 'Property Value ($)', it: 'Valore proprieta (€)', es: 'Valor propiedad ($)', fr: 'Valeur propriete (€)', de: 'Immobilienwert (€)', pt: 'Valor propriedade (R$)' }, defaultValue: '300000' },
  { key: 'floodZone', labels: { en: 'Flood Zone Risk (1-5)', it: 'Rischio zona alluvione (1-5)', es: 'Riesgo zona inundacion (1-5)', fr: 'Risque zone inondation (1-5)', de: 'Hochwasserzonenrisiko (1-5)', pt: 'Risco zona enchente (1-5)' }, defaultValue: '3', min: 1, max: 5 },
  { key: 'elevation', labels: { en: 'Floors Above Ground', it: 'Piani sopra il suolo', es: 'Pisos sobre el suelo', fr: 'Etages au-dessus du sol', de: 'Stockwerke ueber Boden', pt: 'Andares acima do solo' }, defaultValue: '1', min: 0, max: 5 },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '1000' },
];
const results = [
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'green' as const, format: 'currency' as const },
  { key: 'buildingCoverage', labels: { en: 'Building Coverage', it: 'Copertura edificio', es: 'Cobertura edificio', fr: 'Couverture batiment', de: 'Gebaeudedeckung', pt: 'Cobertura edificio' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'contentsCoverage', labels: { en: 'Contents Coverage', it: 'Copertura contenuti', es: 'Cobertura contenidos', fr: 'Couverture contenu', de: 'Inhaltsdeckung', pt: 'Cobertura conteudo' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const prop = v.propertyValue || 300000; const zone = v.floodZone || 3; const elev = v.elevation || 1; const ded = v.deductible || 1000;
  const zoneMultiplier = [0.3, 0.5, 1.0, 2.0, 3.5][Math.min(4, Math.max(0, zone - 1))];
  const elevDiscount = elev * 0.15; const dedDiscount = (ded - 500) * 0.05;
  const annual = Math.max(200, prop * 0.003 * zoneMultiplier * (1 - elevDiscount) - dedDiscount);
  return { annualPremium: Math.round(annual), monthlyPremium: Math.round(annual / 12), buildingCoverage: Math.round(Math.min(prop, 250000)), contentsCoverage: Math.round(Math.min(prop * 0.4, 100000)) };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Flood Insurance Calculator: Estimate Your Premium', ['Flood insurance protects your home and belongings from flood damage, which is not covered by standard homeowners insurance. The National Flood Insurance Program (NFIP) provides coverage up to $250,000 for buildings and $100,000 for contents.', 'This calculator estimates your flood insurance premium based on property value, flood zone risk level, building elevation, and deductible amount. High-risk zones (A and V) require significantly higher premiums.', 'Even homes outside high-risk flood zones can flood. About 25% of flood claims come from moderate-to-low risk areas. FEMA reports that just one inch of flooding can cause $25,000+ in damage.', 'For related tools, see our <a href="/${lang}/tools/home-insurance-calculator">home insurance calculator</a> and <a href="/${lang}/tools/umbrella-insurance-calculator">umbrella insurance calculator</a>.'], [{q:'Do I need flood insurance?',a:'If you are in a high-risk flood zone with a federally-backed mortgage, yes. Even in low-risk areas, flood insurance is recommended as standard homeowners policies exclude flood damage.'},{q:'How much does flood insurance cost?',a:'Average NFIP premiums range from $700-$1,500/year. High-risk zones can cost $2,000-$5,000+ per year.'},{q:'What does flood insurance cover?',a:'Building coverage includes the structure, foundation, electrical/plumbing, HVAC, and appliances. Contents coverage includes furniture, clothing, and electronics.'},{q:'Is there a waiting period?',a:'Yes, NFIP policies have a 30-day waiting period before coverage begins. Plan ahead before flood season.'}]),
  it: mkSeo('Calcolatore Assicurazione Alluvione', ['L\'assicurazione alluvione protegge la tua casa dai danni da inondazione, non coperti dalle polizze standard.', 'Questo calcolatore stima il premio in base a valore proprieta, zona di rischio, elevazione e franchigia.', 'Anche le case fuori dalle zone ad alto rischio possono essere allagate. Il 25% delle richieste proviene da zone a rischio moderato.', 'Consulta il <a href="/${lang}/tools/home-insurance-calculator">calcolatore assicurazione casa</a>.'], [{q:'Ho bisogno dell\'assicurazione alluvione?',a:'Se sei in zona ad alto rischio con mutuo, si. E raccomandata anche in zone a basso rischio.'},{q:'Quanto costa?',a:'I premi medi vanno da 700 a 1.500€/anno. Zone ad alto rischio: 2.000-5.000€+.'},{q:'Cosa copre?',a:'Struttura, fondamenta, impianti e contenuti della casa.'},{q:'C\'e un periodo di attesa?',a:'Si, 30 giorni prima che la copertura sia attiva.'}]),
  es: mkSeo('Calculadora Seguro contra Inundaciones', ['El seguro contra inundaciones protege tu hogar de danos por inundacion.', 'Esta calculadora estima tu prima segun valor, zona de riesgo, elevacion y deducible.', 'Incluso casas fuera de zonas de alto riesgo pueden inundarse. El 25% de los reclamos viene de zonas de riesgo moderado.', 'Consulta la <a href="/${lang}/tools/home-insurance-calculator">calculadora de seguro de hogar</a>.'], [{q:'Necesito seguro contra inundaciones?',a:'Si estas en zona de alto riesgo con hipoteca, si.'},{q:'Cuanto cuesta?',a:'Primas promedio de $700-$1,500/ano.'},{q:'Que cubre?',a:'Estructura, cimientos, instalaciones y contenidos.'},{q:'Hay periodo de espera?',a:'Si, 30 dias antes de que la cobertura sea activa.'}]),
  fr: mkSeo('Calculateur Assurance Inondation', ['L\'assurance inondation protege votre maison des dommages d\'inondation.', 'Ce calculateur estime votre prime selon la valeur, la zone de risque, l\'elevation et la franchise.', 'Meme les maisons hors zones a haut risque peuvent etre inondees.', 'Consultez le <a href="/${lang}/tools/home-insurance-calculator">calculateur assurance habitation</a>.'], [{q:'Ai-je besoin d\'une assurance inondation?',a:'Si vous etes en zone a haut risque avec un pret, oui.'},{q:'Combien ca coute?',a:'Primes moyennes de 700-1 500€/an.'},{q:'Que couvre-t-elle?',a:'Structure, fondations, installations et contenus.'},{q:'Y a-t-il un delai d\'attente?',a:'Oui, 30 jours avant que la couverture soit active.'}]),
  de: mkSeo('Hochwasserversicherungsrechner', ['Die Hochwasserversicherung schuetzt Ihr Haus vor Hochwasserschaeden.', 'Dieser Rechner schaetzt Ihre Praemie basierend auf Wert, Risikozone, Hoehe und Selbstbeteiligung.', 'Auch Haeuser ausserhalb von Hochrisikozonen koennen ueberflutet werden.', 'Nutzen Sie den <a href="/${lang}/tools/home-insurance-calculator">Hausversicherungsrechner</a>.'], [{q:'Brauche ich eine Hochwasserversicherung?',a:'In Hochrisikozonen mit Hypothek ja.'},{q:'Was kostet sie?',a:'Durchschnittlich 700-1.500€/Jahr.'},{q:'Was deckt sie ab?',a:'Gebaeude, Fundament, Installationen und Inhalt.'},{q:'Gibt es eine Wartezeit?',a:'Ja, 30 Tage bevor der Schutz aktiv wird.'}]),
  pt: mkSeo('Calculadora Seguro contra Enchentes', ['O seguro contra enchentes protege sua casa de danos por inundacao.', 'Esta calculadora estima seu premio com base no valor, zona de risco, elevacao e franquia.', 'Mesmo casas fora de zonas de alto risco podem ser inundadas.', 'Consulte a <a href="/${lang}/tools/home-insurance-calculator">calculadora de seguro residencial</a>.'], [{q:'Preciso de seguro contra enchentes?',a:'Se voce esta em zona de alto risco com financiamento, sim.'},{q:'Quanto custa?',a:'Premios medios de R$700-1.500/ano.'},{q:'O que cobre?',a:'Estrutura, fundacao, instalacoes e conteudo.'},{q:'Ha periodo de espera?',a:'Sim, 30 dias antes da cobertura ser ativa.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="flood-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
