'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'boatValue', labels: { en: 'Boat Value ($)', it: 'Valore barca (€)', es: 'Valor bote ($)', fr: 'Valeur bateau (€)', de: 'Bootswert (€)', pt: 'Valor barco (R$)' }, defaultValue: '25000' },
  { key: 'boatLength', labels: { en: 'Boat Length (ft)', it: 'Lunghezza barca (m)', es: 'Longitud bote (ft)', fr: 'Longueur bateau (m)', de: 'Bootslaenge (m)', pt: 'Comprimento barco (m)' }, defaultValue: '22', min: 10, max: 80 },
  { key: 'boatAge', labels: { en: 'Boat Age (years)', it: 'Eta barca (anni)', es: 'Antiguedad bote (anos)', fr: 'Age bateau (annees)', de: 'Bootsalter (Jahre)', pt: 'Idade barco (anos)' }, defaultValue: '5', min: 0, max: 40 },
  { key: 'deductible', labels: { en: 'Deductible ($)', it: 'Franchigia (€)', es: 'Deducible ($)', fr: 'Franchise (€)', de: 'Selbstbeteiligung (€)', pt: 'Franquia (R$)' }, defaultValue: '500' },
];
const results = [
  { key: 'annualPremium', labels: { en: 'Annual Premium', it: 'Premio annuale', es: 'Prima anual', fr: 'Prime annuelle', de: 'Jahrespraemie', pt: 'Premio anual' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'green' as const, format: 'currency' as const },
  { key: 'hullCoverage', labels: { en: 'Hull Coverage', it: 'Copertura scafo', es: 'Cobertura casco', fr: 'Couverture coque', de: 'Rumpfdeckung', pt: 'Cobertura casco' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'liabilityCoverage', labels: { en: 'Liability Coverage', it: 'Copertura RC', es: 'Cobertura responsabilidad', fr: 'Couverture RC', de: 'Haftpflichtdeckung', pt: 'Cobertura RC' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const value = v.boatValue || 25000; const length = v.boatLength || 22; const age = v.boatAge || 5; const ded = v.deductible || 500;
  const basePct = 0.015; const lengthFactor = length > 30 ? 1.4 : length > 25 ? 1.2 : 1.0;
  const ageFactor = Math.max(0.5, 1 - age * 0.02); const dedDiscount = (ded - 250) * 0.08;
  const annual = Math.max(150, value * basePct * lengthFactor * ageFactor - dedDiscount);
  return { annualPremium: Math.round(annual), monthlyPremium: Math.round(annual / 12), hullCoverage: Math.round(value * ageFactor), liabilityCoverage: 300000 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Boat Insurance Calculator: Estimate Your Premium', ['Boat insurance protects your watercraft from damage, theft, and liability claims. Premiums vary based on boat value, size, age, and how you use it.', 'This calculator estimates your annual premium based on boat value, length, age, and deductible. Larger and more powerful boats cost more to insure.', 'The average boat insurance premium is 1-2% of the boat value per year, or $200-$500 for a typical recreational boat.', 'For related tools, see our <a href="/${lang}/tools/car-insurance-calculator">car insurance calculator</a> and <a href="/${lang}/tools/umbrella-insurance-calculator">umbrella insurance calculator</a>.'], [{q:'Do I need boat insurance?',a:'While not always legally required, boat insurance is essential to protect your investment and cover liability.'},{q:'How much does it cost?',a:'Typically 1-2% of boat value per year, or $200-$500 for recreational boats.'},{q:'What does it cover?',a:'Hull damage, theft, liability, towing, and personal effects on board.'},{q:'Does it cover hurricanes?',a:'Most policies cover storm damage, but some coastal areas may have named-storm deductibles.'}]),
  it: mkSeo('Calcolatore Assicurazione Barca', ['L\'assicurazione barca protegge la tua imbarcazione da danni, furto e responsabilita civile.', 'Questo calcolatore stima il premio annuale in base a valore, lunghezza, eta e franchigia.', 'Il premio medio e l\'1-2% del valore della barca per anno.', 'Consulta il <a href="/${lang}/tools/car-insurance-calculator">calcolatore assicurazione auto</a>.'], [{q:'Mi serve l\'assicurazione barca?',a:'Non sempre obbligatoria, ma essenziale per proteggere il tuo investimento.'},{q:'Quanto costa?',a:'Tipicamente l\'1-2% del valore della barca per anno.'},{q:'Cosa copre?',a:'Danni allo scafo, furto, responsabilita civile e rimorchio.'},{q:'Copre gli uragani?',a:'La maggior parte delle polizze copre i danni da tempesta.'}]),
  es: mkSeo('Calculadora de Seguro de Bote', ['El seguro de bote protege tu embarcacion contra danos, robo y responsabilidad.', 'Esta calculadora estima tu prima anual segun valor, longitud, antiguedad y deducible.', 'La prima promedio es 1-2% del valor del bote por ano.', 'Consulta la <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro de auto</a>.'], [{q:'Necesito seguro de bote?',a:'No siempre obligatorio, pero esencial para proteger tu inversion.'},{q:'Cuanto cuesta?',a:'Tipicamente 1-2% del valor por ano.'},{q:'Que cubre?',a:'Danos al casco, robo, responsabilidad civil y remolque.'},{q:'Cubre huracanes?',a:'La mayoria cubre danos por tormentas.'}]),
  fr: mkSeo('Calculateur Assurance Bateau', ['L\'assurance bateau protege votre embarcation contre les dommages, le vol et la responsabilite.', 'Ce calculateur estime votre prime annuelle selon la valeur, la longueur, l\'age et la franchise.', 'La prime moyenne est de 1-2% de la valeur du bateau par an.', 'Consultez le <a href="/${lang}/tools/car-insurance-calculator">calculateur assurance auto</a>.'], [{q:'Ai-je besoin d\'une assurance bateau?',a:'Pas toujours obligatoire, mais essentielle pour proteger votre investissement.'},{q:'Combien ca coute?',a:'Typiquement 1-2% de la valeur par an.'},{q:'Que couvre-t-elle?',a:'Dommages a la coque, vol, responsabilite civile et remorquage.'},{q:'Couvre-t-elle les ouragans?',a:'La plupart couvrent les dommages de tempete.'}]),
  de: mkSeo('Bootsversicherungsrechner', ['Die Bootsversicherung schuetzt Ihr Wasserfahrzeug vor Schaeden, Diebstahl und Haftungsanspruechen.', 'Dieser Rechner schaetzt Ihre Jahrespraemie basierend auf Wert, Laenge, Alter und Selbstbeteiligung.', 'Die durchschnittliche Praemie betraegt 1-2% des Bootswerts pro Jahr.', 'Nutzen Sie den <a href="/${lang}/tools/car-insurance-calculator">Kfz-Versicherungsrechner</a>.'], [{q:'Brauche ich eine Bootsversicherung?',a:'Nicht immer vorgeschrieben, aber essentiell zum Schutz Ihrer Investition.'},{q:'Was kostet sie?',a:'Typisch 1-2% des Werts pro Jahr.'},{q:'Was deckt sie ab?',a:'Rumpfschaeden, Diebstahl, Haftpflicht und Abschleppen.'},{q:'Deckt sie Hurrikane ab?',a:'Die meisten Policen decken Sturmschaeden ab.'}]),
  pt: mkSeo('Calculadora de Seguro de Barco', ['O seguro de barco protege sua embarcacao contra danos, roubo e responsabilidade.', 'Esta calculadora estima seu premio anual com base no valor, comprimento, idade e franquia.', 'O premio medio e 1-2% do valor do barco por ano.', 'Consulte a <a href="/${lang}/tools/car-insurance-calculator">calculadora de seguro auto</a>.'], [{q:'Preciso de seguro de barco?',a:'Nem sempre obrigatorio, mas essencial para proteger seu investimento.'},{q:'Quanto custa?',a:'Tipicamente 1-2% do valor por ano.'},{q:'O que cobre?',a:'Danos ao casco, roubo, responsabilidade civil e reboque.'},{q:'Cobre furacoes?',a:'A maioria cobre danos por tempestades.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="boat-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
