'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';

const fields = [
  { key: 'age', labels: { en: 'Your Age', it: 'Eta', es: 'Edad', fr: 'Age', de: 'Alter', pt: 'Idade' }, defaultValue: '35', min: 18, max: 80 },
  { key: 'familySize', labels: { en: 'Family Size', it: 'Nucleo familiare', es: 'Tamano familia', fr: 'Taille famille', de: 'Familiengroesse', pt: 'Tamanho familia' }, defaultValue: '3', min: 1, max: 10 },
  { key: 'annualIncome', labels: { en: 'Annual Income ($)', it: 'Reddito annuale (€)', es: 'Ingreso anual ($)', fr: 'Revenu annuel (€)', de: 'Jahreseinkommen (€)', pt: 'Renda anual (R$)' }, defaultValue: '50000' },
];

const results = [
  { key: 'monthlyPremium', labels: { en: 'Monthly Premium', it: 'Premio mensile', es: 'Prima mensual', fr: 'Prime mensuelle', de: 'Monatspraemie', pt: 'Premio mensal' }, color: 'blue' as const, format: 'currency' as const },
  { key: 'annualCost', labels: { en: 'Annual Cost', it: 'Costo annuale', es: 'Costo anual', fr: 'Cout annuel', de: 'Jahreskosten', pt: 'Custo anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'deductible', labels: { en: 'Est. Deductible', it: 'Franchigia stimata', es: 'Deducible est.', fr: 'Franchise est.', de: 'Geschaetzte SB', pt: 'Franquia est.' }, color: 'gray' as const, format: 'currency' as const },
  { key: 'subsidy', labels: { en: 'Potential Subsidy', it: 'Sussidio potenziale', es: 'Subsidio potencial', fr: 'Subvention potentielle', de: 'Moeglicher Zuschuss', pt: 'Subsidio potencial' }, color: 'gray' as const, format: 'currency' as const },
];

function calculate(v: Record<string, number>): Record<string, number> {
  const ageFactor = 1 + ((v.age || 35) - 30) * 0.02;
  const familyFactor = 1 + ((v.familySize || 1) - 1) * 0.6;
  const baseMonthly = 350;
  const monthly = baseMonthly * Math.max(0.6, ageFactor) * familyFactor;
  const income = v.annualIncome || 50000;
  const subsidy = income < 60000 ? Math.max(0, (60000 - income) / 60000 * monthly * 0.7) : 0;
  return { monthlyPremium: Math.round(monthly - subsidy), annualCost: Math.round((monthly - subsidy) * 12), deductible: 4500, subsidy: Math.round(subsidy * 12) };
}

const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: { title: 'Health Insurance Calculator: Estimate Your Premium', paragraphs: ['A health insurance calculator helps estimate monthly premiums based on age, family size, and income. Understanding your expected costs helps you choose the right plan during open enrollment and budget for healthcare expenses throughout the year.', 'This calculator factors in age (older individuals pay more), family size (each additional family member adds about 60% to the base cost), and income level to estimate potential subsidies. The Affordable Care Act provides premium tax credits for households earning between 100-400% of the federal poverty level.', 'Health insurance plans are categorized as Bronze, Silver, Gold, or Platinum, each with different premium and out-of-pocket cost tradeoffs. Bronze plans have the lowest premiums but highest deductibles ($7,000+), while Platinum plans have the highest premiums but lowest out-of-pocket costs.', 'For related financial planning, check our <a href="/${lang}/tools/hsa-calculator">HSA calculator</a> to project tax-advantaged health savings, or the <a href="/${lang}/tools/salary-calculator">salary calculator</a> to understand your take-home pay after deductions.'], faq: [
    { q: 'How are health insurance premiums calculated?', a: 'Premiums are based on age, location, tobacco use, plan category (Bronze/Silver/Gold/Platinum), and family size. Income determines subsidy eligibility but does not directly affect the base premium.' },
    { q: 'What subsidies are available for health insurance?', a: 'Premium tax credits are available through the ACA marketplace for households earning 100-400% of the federal poverty level. Cost-sharing reductions lower deductibles and copays for Silver plan enrollees below 250% FPL.' },
    { q: 'What is the difference between deductible and out-of-pocket maximum?', a: 'The deductible is the amount you pay before insurance kicks in. The out-of-pocket maximum is the most you will pay in a year; after reaching it, insurance covers 100% of covered services.' },
    { q: 'When can I enroll in health insurance?', a: 'Open enrollment typically runs November 1 - January 15. Special enrollment periods are available after qualifying life events like marriage, birth of a child, job loss, or moving.' },
  ] },
  it: { title: 'Calcolatore Assicurazione Sanitaria: Stima il Premio', paragraphs: ['Un calcolatore di assicurazione sanitaria aiuta a stimare i premi mensili in base a eta, nucleo familiare e reddito.', 'Questo calcolatore tiene conto dell\'eta, della dimensione della famiglia e del livello di reddito per stimare eventuali sussidi.', 'I piani assicurativi sanitari offrono diversi compromessi tra premi e costi a carico del paziente.', 'Per la pianificazione finanziaria, consulta il nostro <a href="/${lang}/tools/hsa-calculator">calcolatore HSA</a>.'], faq: [{ q: 'Come vengono calcolati i premi dell\'assicurazione sanitaria?', a: 'I premi si basano su eta, posizione, uso tabacco, tipo di piano e dimensione famiglia.' }, { q: 'Quali sussidi sono disponibili?', a: 'Crediti d\'imposta sui premi sono disponibili per famiglie con redditi sotto determinate soglie.' }, { q: 'Qual e la differenza tra franchigia e massimale?', a: 'La franchigia e l\'importo che paghi prima che l\'assicurazione intervenga. Il massimale e il massimo che pagherai in un anno.' }, { q: 'Quando posso iscrivermi?', a: 'L\'iscrizione aperta e tipicamente in periodi specifici dell\'anno, con eccezioni per eventi di vita qualificanti.' }] },
  es: { title: 'Calculadora de Seguro Medico: Estima Tu Prima', paragraphs: ['Una calculadora de seguro medico ayuda a estimar primas mensuales basadas en edad, tamano familiar e ingresos.', 'Esta calculadora considera la edad, tamano de familia y nivel de ingresos para estimar subsidios potenciales.', 'Los planes de seguro medico ofrecen diferentes equilibrios entre primas y costos de bolsillo.', 'Consulta nuestra <a href="/${lang}/tools/hsa-calculator">calculadora HSA</a> para ahorros de salud.'], faq: [{ q: 'Como se calculan las primas de seguro medico?', a: 'Las primas se basan en edad, ubicacion, uso de tabaco, tipo de plan y tamano familiar.' }, { q: 'Que subsidios estan disponibles?', a: 'Creditos fiscales de prima estan disponibles para hogares con ingresos bajo ciertos umbrales.' }, { q: 'Cual es la diferencia entre deducible y maximo de bolsillo?', a: 'El deducible es lo que pagas antes de que el seguro cubra. El maximo de bolsillo es lo maximo que pagaras en un ano.' }, { q: 'Cuando puedo inscribirme?', a: 'La inscripcion abierta es tipicamente en periodos especificos, con excepciones por eventos de vida calificantes.' }] },
  fr: { title: 'Calculateur Assurance Sante: Estimez Votre Prime', paragraphs: ['Un calculateur d\'assurance sante aide a estimer les primes mensuelles selon l\'age, la taille de la famille et les revenus.', 'Ce calculateur prend en compte l\'age, la taille de la famille et le niveau de revenu pour estimer les subventions potentielles.', 'Les plans d\'assurance sante offrent differents compromis entre primes et frais a votre charge.', 'Consultez notre <a href="/${lang}/tools/hsa-calculator">calculateur HSA</a> pour l\'epargne sante.'], faq: [{ q: 'Comment les primes d\'assurance sante sont-elles calculees?', a: 'Les primes sont basees sur l\'age, l\'emplacement, l\'usage du tabac, le type de plan et la taille de la famille.' }, { q: 'Quelles subventions sont disponibles?', a: 'Des credits d\'impot sur les primes sont disponibles pour les menages sous certains seuils de revenus.' }, { q: 'Quelle est la difference entre franchise et plafond?', a: 'La franchise est ce que vous payez avant que l\'assurance intervienne. Le plafond est le maximum que vous paierez par an.' }, { q: 'Quand puis-je m\'inscrire?', a: 'L\'inscription ouverte se fait pendant des periodes specifiques, avec des exceptions pour les evenements de vie qualifiants.' }] },
  de: { title: 'Krankenversicherungsrechner: Schaetzen Sie Ihre Praemie', paragraphs: ['Ein Krankenversicherungsrechner hilft, monatliche Praemien basierend auf Alter, Familiengroesse und Einkommen zu schaetzen.', 'Dieser Rechner beruecksichtigt Alter, Familiengroesse und Einkommensniveau fuer moegliche Zuschuesse.', 'Krankenversicherungsplaene bieten verschiedene Abwaegungen zwischen Praemien und Eigenkosten.', 'Nutzen Sie unseren <a href="/${lang}/tools/hsa-calculator">HSA-Rechner</a> fuer steuerbeguenstigte Gesundheitsersparnisse.'], faq: [{ q: 'Wie werden Krankenversicherungspraemien berechnet?', a: 'Praemien basieren auf Alter, Standort, Tabakkonsum, Plantyp und Familiengroesse.' }, { q: 'Welche Zuschuesse gibt es?', a: 'Steuerliche Praemienkredite sind fuer Haushalte unter bestimmten Einkommensgrenzen verfuegbar.' }, { q: 'Was ist der Unterschied zwischen Selbstbeteiligung und Hoechstgrenze?', a: 'Die Selbstbeteiligung ist der Betrag, den Sie zahlen, bevor die Versicherung einspringt. Die Hoechstgrenze ist das Maximum, das Sie pro Jahr zahlen.' }, { q: 'Wann kann ich mich anmelden?', a: 'Die offene Einschreibung findet zu bestimmten Zeiten statt, mit Ausnahmen fuer qualifizierende Lebensereignisse.' }] },
  pt: { title: 'Calculadora de Seguro Saude: Estime Seu Premio', paragraphs: ['Uma calculadora de seguro saude ajuda a estimar premios mensais com base em idade, tamanho da familia e renda.', 'Esta calculadora considera idade, tamanho da familia e nivel de renda para estimar subsidios potenciais.', 'Os planos de seguro saude oferecem diferentes equilibrios entre premios e custos diretos.', 'Consulte nossa <a href="/${lang}/tools/hsa-calculator">calculadora HSA</a> para economia em saude.'], faq: [{ q: 'Como sao calculados os premios de seguro saude?', a: 'Os premios sao baseados em idade, localizacao, uso de tabaco, tipo de plano e tamanho da familia.' }, { q: 'Quais subsidios estao disponiveis?', a: 'Creditos fiscais de premio estao disponiveis para familias abaixo de certos limites de renda.' }, { q: 'Qual a diferenca entre franquia e teto maximo?', a: 'A franquia e o que voce paga antes do seguro cobrir. O teto maximo e o maximo que voce pagara por ano.' }, { q: 'Quando posso me inscrever?', a: 'A inscricao aberta ocorre em periodos especificos, com excecoes para eventos de vida qualificantes.' }] },
};

export default function HealthInsuranceCalculator() {
  return <InsuranceCalculatorPage toolSlug="health-insurance-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />;
}
