'use client';
import InsuranceCalculatorPage from '@/components/InsuranceCalculatorPage';
import type { Locale } from '@/lib/translations';
const fields = [
  { key: 'homeSize', labels: { en: 'Home Size (sq ft)', it: 'Superficie casa (mq)', es: 'Tamano casa (sq ft)', fr: 'Surface maison (m²)', de: 'Hausgroesse (m²)', pt: 'Tamanho casa (m²)' }, defaultValue: '2000' },
  { key: 'homeAge', labels: { en: 'Home Age (years)', it: 'Eta casa (anni)', es: 'Antiguedad casa (anos)', fr: 'Age maison (annees)', de: 'Hausalter (Jahre)', pt: 'Idade casa (anos)' }, defaultValue: '25', min: 0, max: 100 },
  { key: 'monthlyBill', labels: { en: 'Monthly Energy Bill ($)', it: 'Bolletta mensile energia (€)', es: 'Factura mensual energia ($)', fr: 'Facture energie mensuelle (€)', de: 'Monatliche Energierechnung (€)', pt: 'Conta energia mensal (R$)' }, defaultValue: '200' },
  { key: 'insulationLevel', labels: { en: 'Insulation (1=poor, 5=excellent)', it: 'Isolamento (1=scarso, 5=ottimo)', es: 'Aislamiento (1=pobre, 5=excelente)', fr: 'Isolation (1=mauvaise, 5=excellente)', de: 'Daemmung (1=schlecht, 5=ausgezeichnet)', pt: 'Isolamento (1=ruim, 5=excelente)' }, defaultValue: '3', min: 1, max: 5 },
];
const results = [
  { key: 'annualCost', labels: { en: 'Annual Energy Cost', it: 'Costo energia annuale', es: 'Costo energia anual', fr: 'Cout energie annuel', de: 'Jaehrliche Energiekosten', pt: 'Custo energia anual' }, color: 'red' as const, format: 'currency' as const },
  { key: 'efficiencyScore', labels: { en: 'Efficiency Score (/100)', it: 'Punteggio efficienza (/100)', es: 'Puntuacion eficiencia (/100)', fr: 'Score efficacite (/100)', de: 'Effizienzwert (/100)', pt: 'Pontuacao eficiencia (/100)' }, color: 'blue' as const, format: 'number' as const },
  { key: 'potentialSavings', labels: { en: 'Potential Annual Savings', it: 'Risparmio potenziale annuo', es: 'Ahorro potencial anual', fr: 'Economies potentielles/an', de: 'Moegliche Jahresersparnis', pt: 'Economia potencial anual' }, color: 'green' as const, format: 'currency' as const },
  { key: 'costPerSqFt', labels: { en: 'Cost Per Sq Ft', it: 'Costo per mq', es: 'Costo por sq ft', fr: 'Cout par m²', de: 'Kosten pro m²', pt: 'Custo por m²' }, color: 'gray' as const, format: 'currency' as const },
];
function calculate(v: Record<string, number>): Record<string, number> {
  const size = v.homeSize || 2000; const age = v.homeAge || 25; const bill = v.monthlyBill || 200; const insul = v.insulationLevel || 3;
  const annual = bill * 12; const agePenalty = Math.max(0, (age - 10) * 0.5);
  const insulBonus = (insul - 1) * 15; const score = Math.max(20, Math.min(100, 80 - agePenalty + insulBonus));
  const savingsPercent = Math.max(0, (100 - score) * 0.4) / 100;
  return { annualCost: Math.round(annual), efficiencyScore: Math.round(score), potentialSavings: Math.round(annual * savingsPercent), costPerSqFt: Math.round((annual / size) * 100) / 100 };
}
const mkSeo = (t: string, p: string[], f: { q: string; a: string }[]) => ({ title: t, paragraphs: p, faq: f });
const seo: Record<Locale, { title: string; paragraphs: string[]; faq: { q: string; a: string }[] }> = {
  en: mkSeo('Home Energy Audit Calculator: Find Your Savings', ['A home energy audit identifies where your home is wasting energy and how to reduce consumption. This calculator provides a quick efficiency assessment based on your home characteristics and energy bills.', 'Older homes typically lose 25-40% of heating and cooling energy through inadequate insulation, air leaks, and outdated systems. Even simple upgrades can cut energy bills by 15-30%.', 'The average US household spends $2,000-$3,000/year on energy. An energy audit can identify $500-$1,000+ in annual savings opportunities through insulation, sealing, and equipment upgrades.', 'For related tools, see our <a href="/${lang}/tools/insulation-roi-calculator">insulation ROI calculator</a> and <a href="/${lang}/tools/heat-pump-calculator">heat pump calculator</a>.'], [{q:'What is a home energy audit?',a:'An assessment of how your home uses energy, identifying inefficiencies and recommending improvements to reduce waste and lower bills.'},{q:'How much can an energy audit save?',a:'Most homeowners can save 15-30% on energy bills by implementing audit recommendations, or $300-$900 per year.'},{q:'What does a professional audit cost?',a:'A professional energy audit typically costs $200-$500 but can identify thousands in savings over time. Many utilities offer free or subsidized audits.'},{q:'What are the most common energy wastes?',a:'Air leaks around windows/doors, insufficient insulation, outdated HVAC systems, and inefficient lighting are the most common.'}]),
  it: mkSeo('Calcolatore Audit Energetico Casa', ['Un audit energetico identifica dove la tua casa spreca energia.', 'Le case vecchie perdono il 25-40% dell\'energia di riscaldamento.', 'La famiglia media spende 2.000-3.000€/anno in energia.', 'Consulta il <a href="/${lang}/tools/insulation-roi-calculator">calcolatore ROI isolamento</a>.'], [{q:'Cos\'e un audit energetico?',a:'Una valutazione di come la tua casa usa l\'energia, con raccomandazioni per ridurre gli sprechi.'},{q:'Quanto posso risparmiare?',a:'Il 15-30% sulle bollette, o 300-900€/anno.'},{q:'Quanto costa un audit professionale?',a:'200-500€ ma identifica migliaia di euro in risparmi.'},{q:'Quali sono gli sprechi piu comuni?',a:'Infiltrazioni d\'aria, isolamento insufficiente, impianti HVAC vecchi, illuminazione inefficiente.'}]),
  es: mkSeo('Calculadora Auditoria Energetica', ['Una auditoria energetica identifica donde tu casa desperdicia energia.', 'Las casas antiguas pierden 25-40% de la energia de climatizacion.', 'El hogar promedio gasta $2,000-$3,000/ano en energia.', 'Consulta la <a href="/${lang}/tools/insulation-roi-calculator">calculadora ROI aislamiento</a>.'], [{q:'Que es una auditoria energetica?',a:'Una evaluacion de como tu casa usa la energia con recomendaciones de mejora.'},{q:'Cuanto puedo ahorrar?',a:'15-30% en facturas de energia, o $300-$900/ano.'},{q:'Cuanto cuesta una auditoria profesional?',a:'$200-$500 pero identifica miles en ahorros.'},{q:'Cuales son los desperdicios mas comunes?',a:'Fugas de aire, aislamiento insuficiente, sistemas HVAC viejos.'}]),
  fr: mkSeo('Calculateur Audit Energetique', ['Un audit energetique identifie ou votre maison gaspille de l\'energie.', 'Les maisons anciennes perdent 25-40% de l\'energie de chauffage.', 'Le foyer moyen depense 2 000-3 000€/an en energie.', 'Consultez le <a href="/${lang}/tools/insulation-roi-calculator">calculateur ROI isolation</a>.'], [{q:'Qu\'est-ce qu\'un audit energetique?',a:'Une evaluation de la consommation energetique avec des recommandations d\'amelioration.'},{q:'Combien puis-je economiser?',a:'15-30% sur les factures, soit 300-900€/an.'},{q:'Combien coute un audit professionnel?',a:'200-500€ mais identifie des milliers d\'economies.'},{q:'Quels sont les gaspillages les plus courants?',a:'Fuites d\'air, isolation insuffisante, systemes HVAC anciens.'}]),
  de: mkSeo('Energieaudit-Rechner', ['Ein Energieaudit identifiziert, wo Ihr Haus Energie verschwendet.', 'Aeltere Haeuser verlieren 25-40% der Heizenergie.', 'Der durchschnittliche Haushalt gibt 2.000-3.000€/Jahr fuer Energie aus.', 'Nutzen Sie den <a href="/${lang}/tools/insulation-roi-calculator">Daemmung ROI Rechner</a>.'], [{q:'Was ist ein Energieaudit?',a:'Eine Bewertung des Energieverbrauchs mit Verbesserungsempfehlungen.'},{q:'Wie viel kann ich sparen?',a:'15-30% bei den Energierechnungen, oder 300-900€/Jahr.'},{q:'Was kostet ein professionelles Audit?',a:'200-500€, identifiziert aber Tausende an Einsparungen.'},{q:'Was sind die haeufigsten Verschwendungen?',a:'Luftlecks, unzureichende Daemmung, veraltete HVAC-Systeme.'}]),
  pt: mkSeo('Calculadora Auditoria Energetica', ['Uma auditoria energetica identifica onde sua casa desperdioca energia.', 'Casas antigas perdem 25-40% da energia de climatizacao.', 'A familia media gasta R$2.000-3.000/ano em energia.', 'Consulte a <a href="/${lang}/tools/insulation-roi-calculator">calculadora ROI isolamento</a>.'], [{q:'O que e uma auditoria energetica?',a:'Uma avaliacao do uso de energia da sua casa com recomendacoes de melhoria.'},{q:'Quanto posso economizar?',a:'15-30% nas contas de energia, ou R$300-900/ano.'},{q:'Quanto custa uma auditoria profissional?',a:'R$200-500 mas identifica milhares em economias.'},{q:'Quais sao os desperdicios mais comuns?',a:'Vazamentos de ar, isolamento insuficiente, sistemas HVAC antigos.'}]),
};
export default function Page() { return <InsuranceCalculatorPage toolSlug="home-energy-audit-calculator" fields={fields} results={results} calculate={calculate} seoContent={seo} />; }
