'use client';
import { useParams } from 'next/navigation';
import { type Locale } from '@/lib/translations';

const content: Record<Locale, { title: string; lastUpdated: string; sections: { heading: string; body: string }[] }> = {
  en: {
    title: 'Terms of Service',
    lastUpdated: 'Last updated: March 2026',
    sections: [
      {
        heading: 'Acceptance of Terms',
        body: 'By accessing and using ToolKit Online (toolkitonline.vip), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website.',
      },
      {
        heading: 'Description of Service',
        body: 'ToolKit Online provides free online tools including calculators, converters, text utilities, and developer tools. All tools run in your browser and are provided free of charge.',
      },
      {
        heading: 'Use of the Service',
        body: 'You may use our tools for personal and commercial purposes. You agree not to misuse the service, attempt to disrupt its operation, or use automated systems to access the site in a manner that sends more request messages to our servers than a human can reasonably produce using a standard web browser.',
      },
      {
        heading: 'Accuracy and Disclaimer',
        body: 'While we strive to provide accurate and reliable tools, ToolKit Online is provided "as is" and "as available" without any warranties of any kind. We do not guarantee the accuracy, completeness, or usefulness of any results generated by our tools. You use the results at your own risk.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'In no event shall ToolKit Online, its operators, or contributors be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the service.',
      },
      {
        heading: 'Intellectual Property',
        body: 'The content, design, and code of ToolKit Online are protected by copyright and other intellectual property laws. You may not reproduce, distribute, or create derivative works from our website without prior written consent.',
      },
      {
        heading: 'Third-Party Advertising',
        body: 'We display advertisements through Google AdSense. These ads may use cookies to serve personalized content. Your interaction with third-party advertisements is governed by the respective third party\'s terms and privacy policies.',
      },
      {
        heading: 'Changes to Terms',
        body: 'We reserve the right to modify these Terms of Service at any time. Changes will be posted on this page with an updated date. Continued use of the site after changes constitutes acceptance of the new terms.',
      },
      {
        heading: 'Contact',
        body: 'For questions about these Terms of Service, contact us at info@toolkitonline.vip.',
      },
    ],
  },
  it: {
    title: 'Termini di Servizio',
    lastUpdated: 'Ultimo aggiornamento: Marzo 2026',
    sections: [
      {
        heading: 'Accettazione dei Termini',
        body: 'Accedendo e utilizzando ToolKit Online (toolkitonline.vip), accetti di essere vincolato da questi Termini di Servizio. Se non sei d\'accordo con una qualsiasi parte di questi termini, ti preghiamo di non utilizzare il nostro sito.',
      },
      {
        heading: 'Descrizione del Servizio',
        body: 'ToolKit Online fornisce strumenti online gratuiti tra cui calcolatori, convertitori, utilità di testo e strumenti per sviluppatori. Tutti gli strumenti funzionano nel tuo browser e sono forniti gratuitamente.',
      },
      {
        heading: 'Utilizzo del Servizio',
        body: 'Puoi utilizzare i nostri strumenti per scopi personali e commerciali. Accetti di non abusare del servizio, tentare di interromperne il funzionamento o utilizzare sistemi automatizzati per accedere al sito in modo eccessivo.',
      },
      {
        heading: 'Accuratezza e Esclusione di Responsabilità',
        body: 'Sebbene ci impegniamo a fornire strumenti accurati e affidabili, ToolKit Online è fornito "così com\'è" e "come disponibile" senza garanzie di alcun tipo. Non garantiamo l\'accuratezza, la completezza o l\'utilità dei risultati generati dai nostri strumenti. Li utilizzi a tuo rischio.',
      },
      {
        heading: 'Limitazione di Responsabilità',
        body: 'In nessun caso ToolKit Online, i suoi operatori o collaboratori saranno responsabili per danni diretti, indiretti, incidentali, speciali, consequenziali o punitivi derivanti dall\'uso del servizio.',
      },
      {
        heading: 'Proprietà Intellettuale',
        body: 'Il contenuto, il design e il codice di ToolKit Online sono protetti dal diritto d\'autore e da altre leggi sulla proprietà intellettuale. Non è consentito riprodurre, distribuire o creare opere derivate dal nostro sito senza previo consenso scritto.',
      },
      {
        heading: 'Pubblicità di Terze Parti',
        body: 'Mostriamo annunci pubblicitari tramite Google AdSense. Questi annunci possono utilizzare cookie per fornire contenuti personalizzati. La tua interazione con gli annunci di terze parti è regolata dai rispettivi termini e politiche sulla privacy.',
      },
      {
        heading: 'Modifiche ai Termini',
        body: 'Ci riserviamo il diritto di modificare questi Termini di Servizio in qualsiasi momento. Le modifiche saranno pubblicate su questa pagina con una data aggiornata. L\'uso continuato del sito dopo le modifiche costituisce accettazione dei nuovi termini.',
      },
      {
        heading: 'Contatti',
        body: 'Per domande su questi Termini di Servizio, contattaci a info@toolkitonline.vip.',
      },
    ],
  },
  es: {
    title: 'Términos de Servicio',
    lastUpdated: 'Última actualización: Marzo 2026',
    sections: [
      {
        heading: 'Aceptación de los Términos',
        body: 'Al acceder y utilizar ToolKit Online (toolkitonline.vip), aceptas estar sujeto a estos Términos de Servicio. Si no estás de acuerdo con alguna parte de estos términos, por favor no uses nuestro sitio.',
      },
      {
        heading: 'Descripción del Servicio',
        body: 'ToolKit Online proporciona herramientas en línea gratuitas que incluyen calculadoras, convertidores, utilidades de texto y herramientas para desarrolladores. Todas las herramientas funcionan en tu navegador y se proporcionan de forma gratuita.',
      },
      {
        heading: 'Uso del Servicio',
        body: 'Puedes usar nuestras herramientas con fines personales y comerciales. Aceptas no abusar del servicio, intentar interrumpir su funcionamiento ni utilizar sistemas automatizados para acceder al sitio de manera excesiva.',
      },
      {
        heading: 'Precisión y Descargo de Responsabilidad',
        body: 'Aunque nos esforzamos por proporcionar herramientas precisas y fiables, ToolKit Online se proporciona "tal cual" y "según disponibilidad" sin garantías de ningún tipo. No garantizamos la precisión, integridad o utilidad de los resultados generados por nuestras herramientas. Los usas bajo tu propio riesgo.',
      },
      {
        heading: 'Limitación de Responsabilidad',
        body: 'En ningún caso ToolKit Online, sus operadores o colaboradores serán responsables de daños directos, indirectos, incidentales, especiales, consecuentes o punitivos derivados del uso del servicio.',
      },
      {
        heading: 'Propiedad Intelectual',
        body: 'El contenido, diseño y código de ToolKit Online están protegidos por derechos de autor y otras leyes de propiedad intelectual. No puedes reproducir, distribuir ni crear obras derivadas de nuestro sitio sin consentimiento previo por escrito.',
      },
      {
        heading: 'Publicidad de Terceros',
        body: 'Mostramos anuncios a través de Google AdSense. Estos anuncios pueden usar cookies para ofrecer contenido personalizado. Tu interacción con anuncios de terceros se rige por los términos y políticas de privacidad de dichos terceros.',
      },
      {
        heading: 'Cambios en los Términos',
        body: 'Nos reservamos el derecho de modificar estos Términos de Servicio en cualquier momento. Los cambios se publicarán en esta página con una fecha actualizada. El uso continuado del sitio después de los cambios constituye la aceptación de los nuevos términos.',
      },
      {
        heading: 'Contacto',
        body: 'Para preguntas sobre estos Términos de Servicio, contáctanos en info@toolkitonline.vip.',
      },
    ],
  },
  fr: {
    title: 'Conditions d\'Utilisation',
    lastUpdated: 'Dernière mise à jour : Mars 2026',
    sections: [
      {
        heading: 'Acceptation des Conditions',
        body: 'En accédant et en utilisant ToolKit Online (toolkitonline.vip), vous acceptez d\'être lié par ces Conditions d\'Utilisation. Si vous n\'acceptez pas une partie de ces conditions, veuillez ne pas utiliser notre site.',
      },
      {
        heading: 'Description du Service',
        body: 'ToolKit Online fournit des outils en ligne gratuits comprenant des calculatrices, des convertisseurs, des utilitaires de texte et des outils pour développeurs. Tous les outils fonctionnent dans votre navigateur et sont fournis gratuitement.',
      },
      {
        heading: 'Utilisation du Service',
        body: 'Vous pouvez utiliser nos outils à des fins personnelles et commerciales. Vous acceptez de ne pas abuser du service, de ne pas tenter de perturber son fonctionnement ou d\'utiliser des systèmes automatisés pour accéder au site de manière excessive.',
      },
      {
        heading: 'Exactitude et Avertissement',
        body: 'Bien que nous nous efforcions de fournir des outils précis et fiables, ToolKit Online est fourni "tel quel" et "selon disponibilité" sans aucune garantie. Nous ne garantissons pas l\'exactitude, l\'exhaustivité ou l\'utilité des résultats générés par nos outils. Vous les utilisez à vos propres risques.',
      },
      {
        heading: 'Limitation de Responsabilité',
        body: 'En aucun cas ToolKit Online, ses opérateurs ou contributeurs ne pourront être tenus responsables de dommages directs, indirects, accessoires, spéciaux, consécutifs ou punitifs résultant de l\'utilisation du service.',
      },
      {
        heading: 'Propriété Intellectuelle',
        body: 'Le contenu, le design et le code de ToolKit Online sont protégés par le droit d\'auteur et d\'autres lois sur la propriété intellectuelle. Vous ne pouvez pas reproduire, distribuer ou créer des œuvres dérivées de notre site sans consentement écrit préalable.',
      },
      {
        heading: 'Publicité Tierce',
        body: 'Nous affichons des publicités via Google AdSense. Ces publicités peuvent utiliser des cookies pour diffuser du contenu personnalisé. Votre interaction avec les publicités tierces est régie par les conditions et politiques de confidentialité respectives.',
      },
      {
        heading: 'Modifications des Conditions',
        body: 'Nous nous réservons le droit de modifier ces Conditions d\'Utilisation à tout moment. Les modifications seront publiées sur cette page avec une date mise à jour. L\'utilisation continue du site après les modifications constitue l\'acceptation des nouvelles conditions.',
      },
      {
        heading: 'Contact',
        body: 'Pour toute question concernant ces Conditions d\'Utilisation, contactez-nous à info@toolkitonline.vip.',
      },
    ],
  },
  de: {
    title: 'Nutzungsbedingungen',
    lastUpdated: 'Letzte Aktualisierung: März 2026',
    sections: [
      {
        heading: 'Annahme der Bedingungen',
        body: 'Durch den Zugriff auf und die Nutzung von ToolKit Online (toolkitonline.vip) erklären Sie sich mit diesen Nutzungsbedingungen einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, nutzen Sie bitte unsere Website nicht.',
      },
      {
        heading: 'Beschreibung des Dienstes',
        body: 'ToolKit Online bietet kostenlose Online-Werkzeuge einschließlich Rechner, Umrechner, Text-Utilities und Entwickler-Tools. Alle Werkzeuge laufen in Ihrem Browser und werden kostenlos bereitgestellt.',
      },
      {
        heading: 'Nutzung des Dienstes',
        body: 'Sie dürfen unsere Werkzeuge für persönliche und gewerbliche Zwecke nutzen. Sie erklären sich damit einverstanden, den Dienst nicht zu missbrauchen, seinen Betrieb nicht zu stören oder automatisierte Systeme für übermäßigen Zugriff zu verwenden.',
      },
      {
        heading: 'Genauigkeit und Haftungsausschluss',
        body: 'Obwohl wir uns bemühen, genaue und zuverlässige Werkzeuge bereitzustellen, wird ToolKit Online "wie besehen" und "wie verfügbar" ohne jegliche Gewährleistung bereitgestellt. Wir garantieren nicht die Genauigkeit, Vollständigkeit oder Nützlichkeit der von unseren Werkzeugen generierten Ergebnisse. Die Nutzung erfolgt auf eigenes Risiko.',
      },
      {
        heading: 'Haftungsbeschränkung',
        body: 'In keinem Fall haften ToolKit Online, seine Betreiber oder Mitwirkenden für direkte, indirekte, zufällige, besondere, Folge- oder Strafschäden, die sich aus der Nutzung des Dienstes ergeben.',
      },
      {
        heading: 'Geistiges Eigentum',
        body: 'Der Inhalt, das Design und der Code von ToolKit Online sind durch Urheberrecht und andere Gesetze zum Schutz geistigen Eigentums geschützt. Sie dürfen unsere Website nicht ohne vorherige schriftliche Zustimmung reproduzieren, verbreiten oder abgeleitete Werke erstellen.',
      },
      {
        heading: 'Werbung Dritter',
        body: 'Wir zeigen Werbung über Google AdSense an. Diese Anzeigen können Cookies verwenden, um personalisierte Inhalte zu liefern. Ihre Interaktion mit Werbung Dritter unterliegt den jeweiligen Bedingungen und Datenschutzrichtlinien.',
      },
      {
        heading: 'Änderungen der Bedingungen',
        body: 'Wir behalten uns das Recht vor, diese Nutzungsbedingungen jederzeit zu ändern. Änderungen werden auf dieser Seite mit einem aktualisierten Datum veröffentlicht. Die fortgesetzte Nutzung der Website nach Änderungen gilt als Annahme der neuen Bedingungen.',
      },
      {
        heading: 'Kontakt',
        body: 'Bei Fragen zu diesen Nutzungsbedingungen kontaktieren Sie uns unter info@toolkitonline.vip.',
      },
    ],
  },
  pt: {
    title: 'Termos de Serviço',
    lastUpdated: 'Última atualização: Março 2026',
    sections: [
      {
        heading: 'Aceitação dos Termos',
        body: 'Ao acessar e usar o ToolKit Online (toolkitonline.vip), você concorda em ficar vinculado a estes Termos de Serviço. Se você não concordar com qualquer parte destes termos, por favor não use nosso site.',
      },
      {
        heading: 'Descrição do Serviço',
        body: 'O ToolKit Online fornece ferramentas online gratuitas incluindo calculadoras, conversores, utilitários de texto e ferramentas para desenvolvedores. Todas as ferramentas funcionam no seu navegador e são fornecidas gratuitamente.',
      },
      {
        heading: 'Uso do Serviço',
        body: 'Você pode usar nossas ferramentas para fins pessoais e comerciais. Você concorda em não abusar do serviço, tentar interromper seu funcionamento ou usar sistemas automatizados para acessar o site de maneira excessiva.',
      },
      {
        heading: 'Precisão e Isenção de Responsabilidade',
        body: 'Embora nos esforcemos para fornecer ferramentas precisas e confiáveis, o ToolKit Online é fornecido "como está" e "conforme disponível" sem garantias de qualquer tipo. Não garantimos a precisão, integridade ou utilidade dos resultados gerados por nossas ferramentas. Você os usa por sua conta e risco.',
      },
      {
        heading: 'Limitação de Responsabilidade',
        body: 'Em nenhum caso o ToolKit Online, seus operadores ou colaboradores serão responsáveis por danos diretos, indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso do serviço.',
      },
      {
        heading: 'Propriedade Intelectual',
        body: 'O conteúdo, design e código do ToolKit Online são protegidos por direitos autorais e outras leis de propriedade intelectual. Você não pode reproduzir, distribuir ou criar obras derivadas do nosso site sem consentimento prévio por escrito.',
      },
      {
        heading: 'Publicidade de Terceiros',
        body: 'Exibimos anúncios através do Google AdSense. Esses anúncios podem usar cookies para oferecer conteúdo personalizado. Sua interação com anúncios de terceiros é regida pelos respectivos termos e políticas de privacidade.',
      },
      {
        heading: 'Alterações nos Termos',
        body: 'Reservamo-nos o direito de modificar estes Termos de Serviço a qualquer momento. As alterações serão publicadas nesta página com uma data atualizada. O uso continuado do site após as alterações constitui aceitação dos novos termos.',
      },
      {
        heading: 'Contato',
        body: 'Para perguntas sobre estes Termos de Serviço, entre em contato conosco em info@toolkitonline.vip.',
      },
    ],
  },
};

export default function TermsPage() {
  const params = useParams();
  const lang = (params?.lang as Locale) || 'en';
  const c = content[lang];

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <article className="prose prose-lg max-w-none">
        <h1 className="text-3xl font-bold mb-2">{c.title}</h1>
        <p className="text-sm text-gray-500 mb-8">{c.lastUpdated}</p>
        {c.sections.map((section, i) => (
          <div key={i} className="mb-6">
            <h2 className="text-xl font-semibold mb-2">{section.heading}</h2>
            <p className="text-gray-700 leading-relaxed">{section.body}</p>
          </div>
        ))}
      </article>
    </div>
  );
}
